/*
 * jce_default_main.inc.h — JCE default application entry-point body.
 *
 * Single-include "drop-in" implementation of app_init / app_update /
 * app_draw / app_exit + the helpers they need.  New JCE projects ship
 * a thin src/main.c that does nothing but:
 *
 *     #include "_embedded_bundles.h"         // generated by CMake
 *     #include <jce/application/jce_default_main.inc.h>
 *     static JceAppDesc proj_get_desc(void) { ... ; d.init=app_init; ... }
 *     JCE_MAIN(proj_get_desc)
 *
 * Including this header anywhere ELSE than the project's main TU is
 * undefined: it defines static globals + static functions named
 * app_init/app_update/app_draw/app_exit.  Engine upgrades reach old
 * projects automatically because the body lives in the SDK header,
 * not in a per-project copy of main.c.
 *
 * "Eject":  Project Settings → Eject main.c writes the inlined body
 * into the project's src/main.c so the user can edit it freely.  At
 * that point the project stops tracking engine upgrades — by design.
 */
#ifndef JCE_DEFAULT_MAIN_INC_H
#define JCE_DEFAULT_MAIN_INC_H

#include <jce/api_app.h>
#include <jce/application/jce_main.h>
#include <jce/application/jce_project.h>
#include <jce/application/jce_runtime.h>
#include <jce/middleware/audio/jce_audio.h>
#include <jce/middleware/scene/jce_scene.h>
#include <jce/middleware/scene/jce_ui_canvas.h>
#include <jce/middleware/scene/jce_vcam_system.h>
#include <jce/os/core/jce_filesystem.h>
#include <jce/os/core/jce_log.h>
#include <jce/os/core/jce_math.h>
#include <jce/os/platform/jce_input.h>
#include <jce/os/platform/jce_keys.h>
#include <jce/os/platform/jce_window.h>
#include <jce/renderer/jce_camera.h>
#include <jce/renderer/jce_mesh.h>
#include <jce/renderer/jce_renderer.h>
#include <jce/renderer/jce_scene_renderer.h>
#include <jce/renderer/jce_views.h>
#include <jce/resource/jce_bundle_loader.h>
#include <jce/resource/jce_model_importer.h>
#include <jce/resource/jce_pak_loader.h>
#include <jce/resource/jce_scene_serial.h>
#include <jce/resource/jce_world_streamer.h>

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef JCE_PROJECT_EMBEDDED_BUNDLE_COUNT
#  define JCE_PROJECT_EMBEDDED_BUNDLE_COUNT 0
typedef struct { const char *name; const void *data; const size_t *size; }
        JceProjectEmbeddedBundle;
static const JceProjectEmbeddedBundle jce_project_embedded_bundles[1] = {{0}};
#endif

/* Owned by this TU; created in app_init, freed in app_exit. */
static JceProject       *s_project        = NULL;
static JceScene         *s_scene          = NULL;
static JceCamera        *s_camera         = NULL;
static JceSceneRenderer *s_scene_renderer = NULL;
static JceUICanvas      *s_ui_canvas      = NULL;
static JceFileSystem    *s_bundle_fs      = NULL;
static JceBundleFile   **s_bundle_files   = NULL;
static int               s_bundle_count   = 0;
static JcePakArchive    *s_engine_pak     = NULL;
static const JceServices*s_svc            = NULL;
static JceRuntime       *s_runtime        = NULL;
static float             s_last_dt        = 0.016f;
static bool              s_jump_edge      = false;
/* Open-world chunk streamer — created only when the startup scene's
 * authored streaming settings are enabled (World Streaming panel). */
static JceWorldStreamer *s_world_streamer = NULL;
static JceFileSystem    *s_stream_fs      = NULL;   /* owned only when not bundle-backed */

/* Runtime mesh cache (path → JceMesh*).
 *
 * The scene renderer calls cbs.load_mesh for every mesh-renderer entity
 * once PER render pass — shadow cascades + depth pre-pass + main pass —
 * i.e. many times per entity per frame.  jce_model_importer_load_pak
 * runs a full pipeline on every call: ZSTD-decompress the asset out of
 * the PAK, a complete Assimp import (GenSmoothNormals + CalcTangentSpace
 * + PreTransformVertices) and a fresh GPU vertex/index buffer upload.
 *
 * Without a cache the deployed exe re-imports every mesh every frame,
 * which both tanks the frame rate and leaks bgfx buffers.  The editor
 * never hits this because its load_mesh callback is backed by the editor
 * asset cache; the standalone runtime must provide its own.  Meshes are
 * owned here and destroyed in app_exit. */
#define JCE_DEFAULT_MESH_CACHE_MAX 256
static struct {
    char     path[256];
    JceMesh *mesh;
    bool     used;
    bool     failed;
} s_mesh_cache[JCE_DEFAULT_MESH_CACHE_MAX];
static int s_mesh_cache_count = 0;
/* s_yaw / s_pitch removed: camera owns its own yaw/pitch now and
 * we stopped using the third-person orbit math that depended on them. */

/* Mount every bundle baked into `.rdata` by CMake's embed step.
 * Memory-resident JPAKs are a borrowed view of the exe's read-only
 * segment, so the runtime never copies and the binary stays a
 * genuinely single self-contained file (no sidecar bundles/). */
static void jce_default_mount_project_bundles(void)
{
#if JCE_PROJECT_EMBEDDED_BUNDLE_COUNT > 0
    s_bundle_fs = jce_fs_create();
    if (!s_bundle_fs) {
        LOG_WARN("app", "%s", "jce_fs_create failed — bundles not mounted");
        return;
    }
    s_bundle_files = (JceBundleFile **)calloc(
        (size_t)JCE_PROJECT_EMBEDDED_BUNDLE_COUNT,
        sizeof(JceBundleFile *));
    if (!s_bundle_files) return;
    for (int i = 0; jce_project_embedded_bundles[i].name; ++i) {
        const char    *name = jce_project_embedded_bundles[i].name;
        const void    *data = jce_project_embedded_bundles[i].data;
        size_t         sz   = *jce_project_embedded_bundles[i].size;
        JceBundleFile *bf   = jce_bundle_file_open_memory(
                                  s_bundle_fs, data, sz, name);
        if (!bf) {
            LOG_WARN("app", "jce_bundle_file_open_memory failed: %s", name);
            continue;
        }
        s_bundle_files[s_bundle_count++] = bf;
        LOG_INFO("app", "bundle mounted (embed): %s (%zu bytes)", name, sz);
    }
#endif
}

static void jce_default_unmount_project_bundles(void)
{
    /* Detach overlays from the engine PAK before destroying the
     * bundle archives so a future jce_pak_find on svc->pak doesn't
     * walk into freed memory. */
    if (s_engine_pak) {
        for (int i = 0; i < s_bundle_count; ++i) {
            JcePakArchive *bp = s_bundle_files[i]
                ? (JcePakArchive *)jce_bundle_file_pak(s_bundle_files[i])
                : NULL;
            if (bp) jce_pak_overlay_remove(s_engine_pak, bp);
        }
        s_engine_pak = NULL;
    }
    for (int i = 0; i < s_bundle_count; ++i) {
        if (s_bundle_files[i]) jce_bundle_file_close(s_bundle_files[i]);
    }
    free(s_bundle_files);
    s_bundle_files = NULL;
    s_bundle_count = 0;
    if (s_bundle_fs) { jce_fs_destroy(s_bundle_fs); s_bundle_fs = NULL; }
}

/* Resolve <startup_scene> from any mounted bundle first; fall back to
 * the cooked tree on disk (`<exe_dir>/<cooked_assets>/<startup_scene>`).
 * cooked_assets defaults to "resources/_cooked" when omitted. */
static bool jce_default_load_startup_scene(const JceProject *proj)
{
    const char *scene_path = (proj && proj->startup_scene && proj->startup_scene[0])
                             ? proj->startup_scene : NULL;
    if (!scene_path) {
        for (int i = 0; i < s_bundle_count; ++i) {
            const char *sp = jce_bundle_file_scene_path(s_bundle_files[i]);
            if (sp && sp[0]) {
                scene_path = sp;
                LOG_INFO("app", "startup_scene unset; using bundle scene: %s", sp);
                break;
            }
        }
    }
    if (!scene_path) return false;

    s_scene = jce_scene_create();
    if (!s_scene) { LOG_ERROR("app", "%s", "jce_scene_create failed"); return false; }

    if (s_bundle_fs &&
        jce_scene_serial_load_vfs(s_scene, s_bundle_fs, scene_path)) {
        LOG_INFO("app", "startup scene loaded (bundle): %s", scene_path);
        return true;
    }

    char base[1024] = {0};
    if (!jce_fs_host_get_base_path(base, sizeof(base))) {
        LOG_WARN("app", "%s", "could not determine executable directory");
        jce_scene_destroy(s_scene); s_scene = NULL;
        return false;
    }
    const char *cooked = (proj && proj->cooked_assets && proj->cooked_assets[0])
                         ? proj->cooked_assets : "resources/_cooked";
    char path[1024];
    int n = snprintf(path, sizeof(path), "%s%s/%s", base, cooked, scene_path);
    if (n <= 0 || n >= (int)sizeof(path)) {
        LOG_WARN("app", "%s", "startup scene path too long");
        jce_scene_destroy(s_scene); s_scene = NULL;
        return false;
    }
    if (!jce_scene_serial_load_file(s_scene, path)) {
        LOG_ERROR("app", "failed to load startup scene: %s", path);
        jce_scene_destroy(s_scene); s_scene = NULL;
        return false;
    }
    LOG_INFO("app", "startup scene loaded: %s", path);
    return true;
}

/* Build the world streamer from the startup scene's authored streaming
 * settings.  FS source: when bundles are mounted, chunk fragments stream
 * out of the bundle VFS (s_bundle_fs); otherwise a private fs mounting
 * <exe_dir>/<cooked_assets> is created (same base the startup scene
 * loaded from), so fragment paths stay project-relative either way. */
static void jce_default_init_world_streaming(const JceProject *proj)
{
    if (!s_scene) return;

    const JceSceneStreamingSettings *st =
        jce_scene_get_streaming_settings(s_scene);
    if (!st || !st->enabled || st->chunk_count == 0) return;

    JceFileSystem *fs = s_bundle_fs;
    if (!fs) {
        char base[1024] = {0};
        if (!jce_fs_host_get_base_path(base, sizeof(base))) {
            LOG_WARN("app", "%s", "world streaming: no base path — disabled");
            return;
        }
        const char *cooked = (proj && proj->cooked_assets && proj->cooked_assets[0])
                             ? proj->cooked_assets : "resources/_cooked";
        char root[1024];
        int n = snprintf(root, sizeof(root), "%s%s", base, cooked);
        if (n <= 0 || n >= (int)sizeof(root)) return;

        s_stream_fs = jce_fs_create();
        if (!s_stream_fs) return;
        jce_fs_mount_dir(s_stream_fs, "", root);
        fs = s_stream_fs;
    }

    JceWorldStreamConfig wsc = jce_world_stream_config_default();
    wsc.mode            = (st->mode == 1) ? JCE_STREAM_RECTANGULAR
                                          : JCE_STREAM_RADIAL;
    wsc.load_radius     = st->load_radius;
    wsc.unload_radius   = st->unload_radius;
    wsc.max_pending     = st->max_pending;
    wsc.budget_mb       = st->budget_mb;
    wsc.frame_budget_ms = st->frame_budget_ms;
    /* Cooperative mode: chunk apply spawns entities + GPU resources, which
     * must happen on the main/render thread (no thread pool is passed). */
    wsc.single_thread   = true;

    s_world_streamer = jce_world_streamer_create(&wsc, s_scene, fs, NULL);
    if (!s_world_streamer) {
        LOG_WARN("app", "%s", "world streamer creation failed — streaming disabled");
        if (s_stream_fs) { jce_fs_destroy(s_stream_fs); s_stream_fs = NULL; }
        return;
    }
    jce_world_streamer_register_from_scene_settings(s_world_streamer, st);
    LOG_INFO("app", "world streaming active (%u chunks, r=%.0f/%.0f)",
             jce_world_streamer_chunk_count(s_world_streamer),
             wsc.load_radius, wsc.unload_radius);
}

static JceMesh *s_default_load_mesh(const char *path, void *ud)
{
    (void)ud;
    /* Load .glb / .gltf / .obj geometry from the overlaid PAK chain.
     * When a bundle is mounted (jce_pak_overlay_push), the PAK walk
     * automatically finds files inside the bundle, including
     * bundle-converted _external/<hash>.glb meshes.
     *
     * Results are cached by path: the renderer calls this many times per
     * frame (once per shadow cascade / depth / main pass per entity), and
     * each import is expensive (decompress + Assimp + GPU upload). */
    if (!s_engine_pak || !path || path[0] == '\0') return NULL;

    for (int i = 0; i < s_mesh_cache_count; ++i) {
        if (s_mesh_cache[i].used &&
            strncmp(s_mesh_cache[i].path, path,
                    sizeof s_mesh_cache[i].path) == 0)
            return s_mesh_cache[i].failed ? NULL : s_mesh_cache[i].mesh;
    }

    JceMesh *mesh = jce_model_importer_load_pak(s_engine_pak, path);

    if (s_mesh_cache_count < JCE_DEFAULT_MESH_CACHE_MAX) {
        int idx = s_mesh_cache_count++;
        snprintf(s_mesh_cache[idx].path, sizeof s_mesh_cache[idx].path,
                 "%s", path);
        s_mesh_cache[idx].mesh   = mesh;
        s_mesh_cache[idx].used   = true;
        s_mesh_cache[idx].failed = (mesh == NULL);
    }
    return mesh;
}

static bool app_init(const JceServices *svc, void *ud)
{
    (void)ud;
    s_svc = svc;
    jce_default_mount_project_bundles();

    /* Promote bundle[0] as base render PAK when project ships no
     * cooked tree (jbundle-only projects).  Otherwise overlay all
     * bundles behind svc->pak so engine subsystems see one merged
     * archive. */
    s_engine_pak = svc ? (JcePakArchive *)svc->pak : NULL;
    if (s_engine_pak) {
        for (int i = 0; i < s_bundle_count; ++i) {
            JcePakArchive *bp =
                (JcePakArchive *)jce_bundle_file_pak(s_bundle_files[i]);
            if (bp) jce_pak_overlay_push(s_engine_pak, bp);
        }
    } else if (s_bundle_count > 0) {
        s_engine_pak =
            (JcePakArchive *)jce_bundle_file_pak(s_bundle_files[0]);
        for (int i = 1; i < s_bundle_count; ++i) {
            JcePakArchive *bp =
                (JcePakArchive *)jce_bundle_file_pak(s_bundle_files[i]);
            if (bp && s_engine_pak)
                jce_pak_overlay_push(s_engine_pak, bp);
        }
        if (s_engine_pak)
            LOG_INFO("app", "no engine PAK — promoted bundle '%s' as render PAK",
                     jce_bundle_file_id(s_bundle_files[0]));
    }

    s_project = jce_project_load(".");
    if (!s_project)
        LOG_WARN("app", "%s", "jce_project.json not found — running with defaults");
    jce_default_load_startup_scene(s_project);

    JceCameraDesc cam_desc = {0};
    cam_desc.mode       = JCE_CAMERA_PERSPECTIVE;
    cam_desc.position   = jce_v3(0.0f, 2.0f, 5.0f);
    cam_desc.target     = jce_v3(0.0f, 0.5f, 0.0f);
    cam_desc.up         = jce_v3(0.0f, 1.0f, 0.0f);
    cam_desc.fov_deg    = 60.0f;
    cam_desc.near_plane = 0.1f;
    cam_desc.far_plane  = 1000.0f;
    s_camera = jce_camera_create(&cam_desc);

    if (svc && svc->renderer) {
        JceSceneRendererCallbacks cbs = {0};
        cbs.load_mesh = s_default_load_mesh;
        s_scene_renderer = jce_scene_renderer_create(
                               svc->renderer, s_engine_pak, &cbs);
        /* A shipped game is always "playing": enable the animation
         * state-machine / auto-locomotion driver that the editor only
         * turns on during Play (otherwise authored .anim_sm.json bindings
         * and auto_speed stay inert in deployed exes). */
        if (s_scene_renderer)
            jce_scene_renderer_set_anim_sm_active(s_scene_renderer, true);
    }
    if (!s_scene_renderer)
        LOG_WARN("app", "%s", "jce_scene_renderer_create failed — scene will not render");

    /* ECS-UI (Canvas/UIImage/UIText/UIButton) overlay renderer.  Authored UI
     * components in the scene render in the deployed game exactly as they
     * preview in the editor game-view. */
    if (svc && svc->renderer) {
        s_ui_canvas = jce_ui_canvas_create(svc->renderer, s_engine_pak);
        if (!s_ui_canvas)
            LOG_WARN("app", "%s", "jce_ui_canvas_create failed — ECS-UI will not render");
    }

    if (s_scene) {
        JceRuntimeDesc rd = (JceRuntimeDesc){0};
        rd.scene          = s_scene;
        rd.pak            = s_engine_pak;
        rd.audio          = svc ? svc->audio : NULL;
        rd.enable_physics = true;

        /* Game L10n: prefer the on-disk cooked tree's i18n dir
         * (<exe_dir>/<cooked_assets>/i18n) so shipped games hot-load
         * locale edits; bundle-embedded exes fall through to rd.pak's
         * "i18n/<locale>.json" source inside jce_runtime_create.  The
         * initial locale comes from jce.ini ([app] locale=zh_cn) when
         * set; otherwise the runtime auto-detects from the OS. */
        static char s_loc_dir[1024];
        {
            char base[1024] = {0};
            if (jce_fs_host_get_base_path(base, sizeof(base))) {
                const char *cooked =
                    (s_project && s_project->cooked_assets &&
                     s_project->cooked_assets[0])
                    ? s_project->cooked_assets : "resources/_cooked";
                int n = snprintf(s_loc_dir, sizeof(s_loc_dir),
                                 "%s%s/i18n", base, cooked);
                if (n > 0 && n < (int)sizeof(s_loc_dir) &&
                    jce_fs_host_exists_dir(s_loc_dir))
                    rd.locales_dir = s_loc_dir;
            }
        }
        rd.locale = (svc && svc->config && svc->config->locale[0])
                    ? svc->config->locale : NULL;

        s_runtime = jce_runtime_create(&rd);
        if (!s_runtime)
            LOG_WARN("app", "%s", "jce_runtime_create failed — physics/audio inactive");
    }

    /* Open-world streaming (no-op unless the scene's streaming settings
     * are enabled and carry registered chunks). */
    jce_default_init_world_streaming(s_project);

    /* Unconditional cursor capture so FPS-look feels like editor Play. */
    if (svc && svc->window) {
        jce_window_set_relative_mouse_mode(svc->window, true);
        jce_window_set_mouse_grab        (svc->window, true);
    }
    return true;
}

/* Editor-authored action map drives movement when the action exists;
 * the raw scancode is the fallback so a missing/renamed action never
 * strands the player. The engine already loads input_actions.json and
 * updates the map every frame (QW-input-actions) — this is the consumer
 * side that was historically missing. */
static bool dm_act_down(const JceInput *in, const JceInputActions *acts,
                        const char *name, int fallback_key)
{
    if (acts) {
        int id = jce_action_find(acts, name);
        if (id >= 0) return jce_action_down(acts, id);
    }
    return jce_input_key_down(in, fallback_key);
}

static void app_update(float dt, void *ud)
{
    (void)ud;
    s_last_dt = dt;
    if (!s_svc || !s_svc->input) return;
    const JceInput *in = s_svc->input;
    const JceInputActions *acts = s_svc->actions;

    /* Movement is camera-relative (W = into-the-screen) just like the
     * editor's Play view, so look direction defines move direction.
     * Only a unit DIRECTION plus button state is pushed — speeds and the
     * jump arc come from the scene's CharacterController component, so
     * the deployed exe and the editor share the same authored feel. */
    if (s_runtime) {
        JceRuntimeInput ri = (JceRuntimeInput){0};

        float fx = 0.0f, fz = 0.0f, rx = 0.0f, rz = 0.0f;
        if (s_camera) {
            jce_vec3 fwd   = jce_camera_get_forward(s_camera);
            jce_vec3 right = jce_camera_get_right  (s_camera);
            fwd.y = 0.0f; right.y = 0.0f;
            float fl = sqrtf(fwd.x*fwd.x   + fwd.z*fwd.z);
            float rl = sqrtf(right.x*right.x + right.z*right.z);
            if (fl > 0.0001f) { fx = fwd.x/fl;   fz = fwd.z/fl;   }
            if (rl > 0.0001f) { rx = right.x/rl; rz = right.z/rl; }
        }
        float wx = 0.0f, wz = 0.0f;
        if (dm_act_down(in, acts, "move_forward", JCE_KEY_W)) { wx += fx; wz += fz; }
        if (dm_act_down(in, acts, "move_back",    JCE_KEY_S)) { wx -= fx; wz -= fz; }
        if (dm_act_down(in, acts, "move_right",   JCE_KEY_D)) { wx += rx; wz += rz; }
        if (dm_act_down(in, acts, "move_left",    JCE_KEY_A)) { wx -= rx; wz -= rz; }
        float wlen = sqrtf(wx*wx + wz*wz);
        if (wlen > 0.0001f) { wx /= wlen; wz /= wlen; }
        ri.walk_x = wx;
        ri.walk_z = wz;

        bool jump_now = dm_act_down(in, acts, "jump", JCE_KEY_SPACE);
        ri.jump_pressed = jump_now && !s_jump_edge;
        ri.jump_held    = jump_now;
        s_jump_edge     = jump_now;
        ri.speed_mult   = 1.0f;
        ri.sprint = dm_act_down(in, acts, "sprint", JCE_KEY_LSHIFT) ||
                    jce_input_key_down(in, JCE_KEY_RSHIFT);
        if (jce_input_key_down(in, JCE_KEY_LCTRL)  ||
            jce_input_key_down(in, JCE_KEY_RCTRL))  ri.speed_mult = 0.25f;
        jce_runtime_set_input(s_runtime, &ri);
        jce_runtime_step(s_runtime, dt);
    }

    /* Drive chunk streaming from the live camera position (cooperative
     * mode: pending loads/applies run inside this call, on this thread). */
    if (s_world_streamer && s_camera)
        jce_world_streamer_update(s_world_streamer,
                                  jce_camera_get_position(s_camera));

    if (!s_camera) return;

    /* Cinemachine-style VCam override — parity with the editor game view
     * (jce_panel_game_view.cpp does the same in Play mode): when the scene
     * has any active VirtualCamera, its damped blended pose drives the live
     * camera and wins over both mouse-look and the player-follow / free-fly
     * logic below for this frame.  When no VCam is active, `vout` is left
     * untouched and we fall through to the FPS controls. */
    if (s_scene) {
        JceVcamOutput vout;
        bool has_vcam = false;
        jce_vcam_system_evaluate(s_scene, dt, &vout, &has_vcam);
        if (has_vcam) {
            jce_camera_set_position(s_camera,
                jce_v3(vout.position[0], vout.position[1], vout.position[2]));
            jce_camera_look_at(s_camera,
                jce_v3(vout.target[0], vout.target[1], vout.target[2]));
            jce_camera_set_fov(s_camera, vout.fov_deg);
            return;
        }
    }

    /* Always-on FPS look: cursor is grabbed in app_init so delta is
     * pure mouse motion.  Mirror editor panel_game_view convention:
     *  - +dx → look right
     *  - -dy → look up (mouse-up = look-up; standard non-inverted) */
    {
        float dx = 0.0f, dy = 0.0f;
        jce_input_mouse_delta(in, &dx, &dy);
        if (dx != 0.0f || dy != 0.0f) {
            const float sens = 0.0025f;
            jce_camera_rotate(s_camera, dx * sens, -dy * sens);
        }
    }

    jce_vec3 player_pos;
    if (s_runtime && jce_runtime_get_player_position(s_runtime, &player_pos)) {
        /* First-person: snap camera to the player's eye position each
         * frame.  We do NOT call set_target — camera_rotate already
         * owns the look direction; set_target would call look_at and
         * stomp the yaw/pitch every frame. */
        jce_vec3 eye = jce_v3(player_pos.x,
                              player_pos.y + 1.6f,
                              player_pos.z);
        jce_camera_set_position(s_camera, eye);
    } else {
        float speed = 20.0f;
        if (jce_input_key_down(in, JCE_KEY_LSHIFT) ||
            jce_input_key_down(in, JCE_KEY_RSHIFT)) speed *= 3.0f;
        if (jce_input_key_down(in, JCE_KEY_LCTRL)  ||
            jce_input_key_down(in, JCE_KEY_RCTRL))  speed *= 0.25f;
        float step = speed * dt;
        if (jce_input_key_down(in, JCE_KEY_W)) jce_camera_move_forward(s_camera,  step);
        if (jce_input_key_down(in, JCE_KEY_S)) jce_camera_move_forward(s_camera, -step);
        if (jce_input_key_down(in, JCE_KEY_D)) jce_camera_move_right  (s_camera,  step);
        if (jce_input_key_down(in, JCE_KEY_A)) jce_camera_move_right  (s_camera, -step);
        if (jce_input_key_down(in, JCE_KEY_E) ||
            jce_input_key_down(in, JCE_KEY_SPACE)) jce_camera_move_up(s_camera,  step);
        if (jce_input_key_down(in, JCE_KEY_Q)) jce_camera_move_up     (s_camera, -step);
    }
}

static void app_draw(const JceServices *svc, void *ud)
{
    (void)ud;
    if (!svc || !svc->renderer || !s_scene_renderer || !s_scene || !s_camera)
        return;
    jce_renderer_begin_frame_3d(svc->renderer, svc->window,
                                s_camera, JCE_VIEW_MAIN_3D);
    JceSceneRenderConfig cfg = jce_scene_render_config_default();
    jce_scene_renderer_render(s_scene_renderer, s_scene, s_camera,
                              JCE_VIEW_MAIN_3D, s_last_dt, &cfg);

    /* ECS-UI overlay on top of the 3D scene, into the backbuffer on the
     * dedicated UI view.  Pointer is NULL: the deployed app grabs the cursor
     * for FPS-look, so authored UI is presentational here (HUD / labels /
     * backgrounds); interactive pointer feeding is a follow-up. */
    if (s_ui_canvas && svc->window) {
        uint32_t sw = 0, sh = 0;
        jce_window_get_size(svc->window, &sw, &sh);
        if (sw > 0 && sh > 0)
            jce_ui_canvas_render(s_ui_canvas, s_scene, JCE_VIEW_UI, UINT16_MAX,
                                 (float)sw, (float)sh, NULL, s_last_dt);
    }
}

static void app_exit(void *ud)
{
    (void)ud;
    /* Streamer first: destroying it removes its streamed entities from
     * s_scene and detaches from the fs before either is torn down. */
    if (s_world_streamer) { jce_world_streamer_destroy(s_world_streamer);  s_world_streamer = NULL; }
    if (s_stream_fs)      { jce_fs_destroy(s_stream_fs);                   s_stream_fs      = NULL; }
    if (s_runtime)        { jce_runtime_destroy(s_runtime);              s_runtime        = NULL; }
    if (s_ui_canvas)      { jce_ui_canvas_destroy(s_ui_canvas);          s_ui_canvas      = NULL; }
    if (s_scene_renderer) { jce_scene_renderer_destroy(s_scene_renderer); s_scene_renderer = NULL; }
    /* Destroy cached meshes (owned here) before tearing the rest down. */
    for (int i = 0; i < s_mesh_cache_count; ++i) {
        if (s_mesh_cache[i].used && s_mesh_cache[i].mesh)
            jce_mesh_destroy(s_mesh_cache[i].mesh);
    }
    s_mesh_cache_count = 0;
    if (s_camera)         { jce_camera_destroy(s_camera);                 s_camera         = NULL; }
    if (s_scene)          { jce_scene_destroy(s_scene);                   s_scene          = NULL; }
    jce_default_unmount_project_bundles();
    if (s_project)        { jce_project_free(s_project);                  s_project        = NULL; }
    s_svc = NULL;
}

#endif /* JCE_DEFAULT_MAIN_INC_H */
