/*
 * jce_default_main.inc.h — JCE default application entry-point body.
 *
 * Single-include "drop-in" implementation of app_init / app_update /
 * app_draw / app_exit + the helpers they need.  New JCE projects ship
 * a thin src/main.c that does nothing but:
 *
 *     #include "_embedded_bundles.h"         // generated by CMake
 *     #include <jce/application/jce_default_main.inc.h>
 *     static JceAppDesc proj_get_desc(void) { ... ; d.init=app_init; ... }
 *     JCE_MAIN(proj_get_desc)
 *
 * Including this header anywhere ELSE than the project's main TU is
 * undefined: it defines static globals + static functions named
 * app_init/app_update/app_draw/app_exit.  Engine upgrades reach old
 * projects automatically because the body lives in the SDK header,
 * not in a per-project copy of main.c.
 *
 * "Eject":  Project Settings → Eject main.c writes the inlined body
 * into the project's src/main.c so the user can edit it freely.  At
 * that point the project stops tracking engine upgrades — by design.
 */
#ifndef JCE_DEFAULT_MAIN_INC_H
#define JCE_DEFAULT_MAIN_INC_H

#include <jce/api_app.h>
#include <jce/application/jce_main.h>
#include <jce/application/jce_project.h>
#include <jce/application/jce_runtime.h>
#include <jce/middleware/audio/jce_audio.h>
#include <jce/middleware/physics/jce_physics_layers.h>  /* layer matrix load (Top 4) */
#include <jce/middleware/scene/jce_scene.h>
#include <jce/middleware/scene/jce_ui_canvas.h>
#include <jce/middleware/scene/jce_vcam_system.h>
#include <jce/os/core/jce_filesystem.h>
#include <jce/os/core/jce_log.h>
#include <jce/os/core/jce_math.h>
#include <jce/os/core/jce_thread.h>           /* async chunk-load thread pool */
#include <jce/os/platform/jce_input.h>
#include <jce/os/platform/jce_keys.h>
#include <jce/os/platform/jce_window.h>
#include <jce/os/platform/jce_window_event.h>  /* JCE_MOUSE_BUTTON_LEFT */
#include <jce/renderer/jce_camera.h>
#include <jce/renderer/jce_lowlevel.h>        /* jce_gfx_caps (homogeneous depth) */
#include <jce/renderer/jce_mesh.h>
#include <jce/renderer/jce_occlusion_culler.h> /* GPU-query occlusion culling (M5) */
#include <jce/renderer/jce_offscreen_target.h> /* offscreen scene target (postfx, Top 1) */
#include <jce/renderer/jce_render_settings.h>  /* project quality settings (Top 5) */
#include <jce/renderer/jce_renderer.h>
#include <jce/renderer/jce_scene_renderer.h>
#include <jce/renderer/jce_texture.h>          /* global mip bias (lod, Top 5) */
#include <jce/renderer/jce_views.h>
#include <jce/resource/jce_bundle_loader.h>
#include <jce/resource/jce_model_importer.h>
#include <jce/resource/jce_pak_loader.h>
#include <jce/resource/jce_scene_serial.h>
#include <jce/resource/jce_world_streamer.h>

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef JCE_PROJECT_EMBEDDED_BUNDLE_COUNT
#  define JCE_PROJECT_EMBEDDED_BUNDLE_COUNT 0
typedef struct { const char *name; const void *data; const size_t *size; }
        JceProjectEmbeddedBundle;
static const JceProjectEmbeddedBundle jce_project_embedded_bundles[1] = {{0}};
#endif

/* Owned by this TU; created in app_init, freed in app_exit. */
static JceProject       *s_project        = NULL;
static JceScene         *s_scene          = NULL;
static JceCamera        *s_camera         = NULL;
static JceSceneRenderer *s_scene_renderer = NULL;
/* Offscreen scene target for the authored postfx chain (Top 1).  Created lazily
 * on the first frame a scene has any active postfx effect; NULL until then so
 * scenes without postfx stay on the zero-overhead direct-to-backbuffer path. */
static JceOffscreenTarget *s_post_target  = NULL;
static JceUICanvas      *s_ui_canvas      = NULL;
/* GPU-query occlusion culler (M5): activates two-pass coherence culling in the
 * shipped runtime so a dense world skips fully-hidden geometry (previously this
 * ran ONLY in the editor scene-view).  Created in app_init after the renderer +
 * scene renderer exist, set into every per-frame scene render config
 * (s_default_scene_cfg), destroyed in app_exit.  NULL when JCE_DISABLE_OCCLUSION
 * is set (A/B + safety hatch) or hardware queries are unsupported (silent
 * always-visible fallback). */
static JceOcclusionCuller *s_occlusion_culler = NULL;
/* Project-wide quality settings (Top 5): loaded once in app_init from the
 * cooked render_settings.json (build-exported from Project Settings > Quality),
 * folded into the scene render config as the project DEFAULT.  Per-scene
 * JceSceneRenderingSettings still override inside the renderer. */
static JceRenderSettings s_render_settings;
static bool              s_render_settings_loaded = false;
static JceFileSystem    *s_bundle_fs      = NULL;
static JceBundleFile   **s_bundle_files   = NULL;
static int               s_bundle_count   = 0;
static JcePakArchive    *s_engine_pak     = NULL;
static const JceServices*s_svc            = NULL;
static JceRuntime       *s_runtime        = NULL;
static float             s_last_dt        = 0.016f;
static bool              s_jump_edge      = false;
/* FPS-look cursor capture.  Captured (relative mouse + grab) ⇒ mouse drives
 * camera look and authored UI is presentational.  Tab toggles capture off so
 * the cursor is freed and in-game UIButtons become clickable (FEATURE 4.1):
 * while uncaptured we feed a real pointer into the canvas and dispatch clicks
 * to the gameplay script VM.  Starts captured to preserve the FPS feel. */
static bool              s_cursor_captured = true;
/* Open-world chunk streamer — created only when the startup scene's
 * authored streaming settings are enabled (World Streaming panel). */
static JceWorldStreamer *s_world_streamer = NULL;
static JceFileSystem    *s_stream_fs      = NULL;   /* owned only when not bundle-backed */
/* Background worker pool for async chunk loads (disk read + JSON-byte staging
 * off-thread; scene apply/spawn stays on the main thread).  Owned here for the
 * app lifetime; destroyed at shutdown AFTER the streamer (whose destroy joins
 * all in-flight chunk tasks first) so no worker dereferences a freed fs/scene. */
static JceThreadPool    *s_stream_pool    = NULL;

/* Runtime mesh cache (path → JceMesh*).
 *
 * The scene renderer calls cbs.load_mesh for every mesh-renderer entity
 * once PER render pass — shadow cascades + depth pre-pass + main pass —
 * i.e. many times per entity per frame.  jce_model_importer_load_pak
 * runs a full pipeline on every call: ZSTD-decompress the asset out of
 * the PAK, a complete Assimp import (GenSmoothNormals + CalcTangentSpace
 * + PreTransformVertices) and a fresh GPU vertex/index buffer upload.
 *
 * Without a cache the deployed exe re-imports every mesh every frame,
 * which both tanks the frame rate and leaks bgfx buffers.  The editor
 * never hits this because its load_mesh callback is backed by the editor
 * asset cache; the standalone runtime must provide its own.  Meshes are
 * owned here and destroyed in app_exit. */
#define JCE_DEFAULT_MESH_CACHE_MAX 256
static struct {
    char     path[256];
    JceMesh *mesh;
    bool     used;
    bool     failed;
} s_mesh_cache[JCE_DEFAULT_MESH_CACHE_MAX];
static int s_mesh_cache_count = 0;
/* s_yaw / s_pitch removed: camera owns its own yaw/pitch now and
 * we stopped using the third-person orbit math that depended on them. */

/* Mount every bundle baked into `.rdata` by CMake's embed step.
 * Memory-resident JPAKs are a borrowed view of the exe's read-only
 * segment, so the runtime never copies and the binary stays a
 * genuinely single self-contained file (no sidecar bundles/). */
static void jce_default_mount_project_bundles(void)
{
#if JCE_PROJECT_EMBEDDED_BUNDLE_COUNT > 0
    s_bundle_fs = jce_fs_create();
    if (!s_bundle_fs) {
        LOG_WARN("app", "%s", "jce_fs_create failed — bundles not mounted");
        return;
    }
    s_bundle_files = (JceBundleFile **)calloc(
        (size_t)JCE_PROJECT_EMBEDDED_BUNDLE_COUNT,
        sizeof(JceBundleFile *));
    if (!s_bundle_files) return;
    for (int i = 0; jce_project_embedded_bundles[i].name; ++i) {
        const char    *name = jce_project_embedded_bundles[i].name;
        const void    *data = jce_project_embedded_bundles[i].data;
        size_t         sz   = *jce_project_embedded_bundles[i].size;
        JceBundleFile *bf   = jce_bundle_file_open_memory(
                                  s_bundle_fs, data, sz, name);
        if (!bf) {
            LOG_WARN("app", "jce_bundle_file_open_memory failed: %s", name);
            continue;
        }
        s_bundle_files[s_bundle_count++] = bf;
        LOG_INFO("app", "bundle mounted (embed): %s (%zu bytes)", name, sz);
    }
#endif
}

static void jce_default_unmount_project_bundles(void)
{
    /* Detach overlays from the engine PAK before destroying the
     * bundle archives so a future jce_pak_find on svc->pak doesn't
     * walk into freed memory. */
    if (s_engine_pak) {
        for (int i = 0; i < s_bundle_count; ++i) {
            JcePakArchive *bp = s_bundle_files[i]
                ? (JcePakArchive *)jce_bundle_file_pak(s_bundle_files[i])
                : NULL;
            if (bp) jce_pak_overlay_remove(s_engine_pak, bp);
        }
        s_engine_pak = NULL;
    }
    for (int i = 0; i < s_bundle_count; ++i) {
        if (s_bundle_files[i]) jce_bundle_file_close(s_bundle_files[i]);
    }
    free(s_bundle_files);
    s_bundle_files = NULL;
    s_bundle_count = 0;
    if (s_bundle_fs) { jce_fs_destroy(s_bundle_fs); s_bundle_fs = NULL; }
}

/* Resolve <startup_scene> from any mounted bundle first; fall back to
 * the cooked tree on disk (`<exe_dir>/<cooked_assets>/<startup_scene>`).
 * cooked_assets defaults to "resources/_cooked" when omitted. */
static bool jce_default_load_startup_scene(const JceProject *proj)
{
    const char *scene_path = (proj && proj->startup_scene && proj->startup_scene[0])
                             ? proj->startup_scene : NULL;
    if (!scene_path) {
        for (int i = 0; i < s_bundle_count; ++i) {
            const char *sp = jce_bundle_file_scene_path(s_bundle_files[i]);
            if (sp && sp[0]) {
                scene_path = sp;
                LOG_INFO("app", "startup_scene unset; using bundle scene: %s", sp);
                break;
            }
        }
    }
    if (!scene_path) return false;

    s_scene = jce_scene_create();
    if (!s_scene) { LOG_ERROR("app", "%s", "jce_scene_create failed"); return false; }

    if (s_bundle_fs &&
        jce_scene_serial_load_vfs(s_scene, s_bundle_fs, scene_path)) {
        LOG_INFO("app", "startup scene loaded (bundle): %s", scene_path);
        return true;
    }

    char base[1024] = {0};
    if (!jce_fs_host_get_base_path(base, sizeof(base))) {
        LOG_WARN("app", "%s", "could not determine executable directory");
        jce_scene_destroy(s_scene); s_scene = NULL;
        return false;
    }
    const char *cooked = (proj && proj->cooked_assets && proj->cooked_assets[0])
                         ? proj->cooked_assets : "resources/_cooked";
    char path[1024];
    int n = snprintf(path, sizeof(path), "%s%s/%s", base, cooked, scene_path);
    if (n <= 0 || n >= (int)sizeof(path)) {
        LOG_WARN("app", "%s", "startup scene path too long");
        jce_scene_destroy(s_scene); s_scene = NULL;
        return false;
    }
    if (!jce_scene_serial_load_file(s_scene, path)) {
        LOG_ERROR("app", "failed to load startup scene: %s", path);
        jce_scene_destroy(s_scene); s_scene = NULL;
        return false;
    }
    LOG_INFO("app", "startup scene loaded: %s", path);
    return true;
}

/* World-streamer entity callbacks (streaming M3): wire a freshly-streamed
 * chunk's entities into the live runtime gameplay (scripts + on_start, triggers,
 * NPCs, runtime bodies) and release them again on cell unload, so gameplay lives
 * in streamed cells instead of just rendering.  `user` is the JceRuntime*.  The
 * despawn fires while the ids are still valid (BEFORE the streamer destroys the
 * scene entities), so the runtime can drop every per-entity reference first. */
static void s_default_streamer_spawn_cb(const uint64_t *ids, uint32_t count,
                                        void *user)
{
    jce_runtime_spawn_gameplay_for_ids((JceRuntime *)user, ids, count);
}

static void s_default_streamer_despawn_cb(const uint64_t *ids, uint32_t count,
                                          void *user)
{
    jce_runtime_despawn_gameplay_for_ids((JceRuntime *)user, ids, count);
}

/* VRAM ceiling: report a streamed chunk's REAL GPU footprint to the streaming
 * budget by summing its entities' resolved model VB+IB+texture bytes from the
 * scene renderer's cache (jce_scene_renderer_entities_vram_bytes).  `user` is
 * unused (the renderer + scene are file-statics).  Returns 0 before the scene
 * renderer / scene exist or while a chunk's async model decodes are still in
 * flight; the streamer then keeps its per-entity estimate and re-queries over a
 * short window so the figure converges to real bytes. */
static uint64_t s_default_streamer_residency_cb(const uint64_t *ids,
                                                uint32_t count, void *user)
{
    (void)user;
    if (!s_scene_renderer || !s_scene) return 0;
    return jce_scene_renderer_entities_vram_bytes(s_scene_renderer, s_scene,
                                                  ids, count);
}

/* Build the world streamer from the startup scene's authored streaming
 * settings.  FS source: when bundles are mounted, chunk fragments stream
 * out of the bundle VFS (s_bundle_fs); otherwise a private fs mounting
 * <exe_dir>/<cooked_assets> is created (same base the startup scene
 * loaded from), so fragment paths stay project-relative either way. */
static void jce_default_init_world_streaming(const JceProject *proj)
{
    if (!s_scene) return;

    const JceSceneStreamingSettings *st =
        jce_scene_get_streaming_settings(s_scene);
    if (!st || !st->enabled || st->chunk_count == 0) return;

    JceFileSystem *fs = s_bundle_fs;
    if (!fs) {
        char base[1024] = {0};
        if (!jce_fs_host_get_base_path(base, sizeof(base))) {
            LOG_WARN("app", "%s", "world streaming: no base path — disabled");
            return;
        }
        const char *cooked = (proj && proj->cooked_assets && proj->cooked_assets[0])
                             ? proj->cooked_assets : "resources/_cooked";
        char root[1024];
        int n = snprintf(root, sizeof(root), "%s%s", base, cooked);
        if (n <= 0 || n >= (int)sizeof(root)) return;

        s_stream_fs = jce_fs_create();
        if (!s_stream_fs) return;
        jce_fs_mount_dir(s_stream_fs, "", root);
        fs = s_stream_fs;
    }

    JceWorldStreamConfig wsc = jce_world_stream_config_default();
    wsc.mode            = (st->mode == 1) ? JCE_STREAM_RECTANGULAR
                                          : JCE_STREAM_RADIAL;
    wsc.load_radius     = st->load_radius;
    wsc.unload_radius   = st->unload_radius;
    wsc.max_pending     = st->max_pending;
    wsc.budget_mb       = st->budget_mb;
    wsc.frame_budget_ms = st->frame_budget_ms;

    /* Chunk disk-read + JSON-byte staging run on a small worker pool; the
     * scene apply (entity + GPU-resource spawn) stays time-sliced on the
     * main/render thread inside jce_world_streamer_update.  This removes the
     * per-cell synchronous-read frame hitch.  Web has no real threads, so keep
     * the cooperative single-thread path there. */
    JceThreadPool *pool = NULL;
#if !JCE_PLATFORM_WEB
    pool = jce_thread_pool_create(3);
#endif
    wsc.single_thread   = (pool == NULL);  /* async iff we have a pool */

    s_world_streamer = jce_world_streamer_create(&wsc, s_scene, fs, pool);
    if (!s_world_streamer) {
        LOG_WARN("app", "%s", "world streamer creation failed — streaming disabled");
        if (pool) jce_thread_pool_destroy(pool);
        if (s_stream_fs) { jce_fs_destroy(s_stream_fs); s_stream_fs = NULL; }
        return;
    }
    s_stream_pool = pool;
    jce_world_streamer_register_from_scene_settings(s_world_streamer, st);
    /* Wire streamed-cell entities into the live runtime gameplay (streaming M3):
     * a script / trigger / NPC authored in a streamed chunk comes alive (on_start
     * / on_update, trigger observer, body) instead of only rendering, and is
     * released cleanly on cell unload.  No-op when no runtime (physics disabled). */
    if (s_runtime)
        jce_world_streamer_set_entity_callbacks(s_world_streamer,
                                                s_default_streamer_spawn_cb,
                                                s_default_streamer_despawn_cb,
                                                s_runtime);

    /* VRAM ceiling: report real per-chunk GPU residency to the budget AND arm
     * the renderer's model-cache eviction so freeing ECS entities on cell
     * unload actually frees their GPU mesh/texture.  The model cache is the
     * dominant streamed-VRAM consumer, so give it the streaming budget as its
     * ceiling (bytes).  Both no-ops when budget_mb == 0 (unlimited) or there is
     * no scene renderer. */
    if (s_scene_renderer) {
        jce_world_streamer_set_residency_query(
            s_world_streamer, s_default_streamer_residency_cb, NULL);
        if (st->budget_mb > 0)
            jce_scene_renderer_set_model_vram_budget(
                s_scene_renderer,
                (uint64_t)st->budget_mb * 1024ULL * 1024ULL);
    }
    /* HLOD far-skyline proxy swap: hide a cell's cheap always-resident proxy
     * box ("HLOD_<gx>_<gz>") once its detailed geometry streams in, show it
     * again on unload.  Shared engine impl (jce_world_streamer_attach_hlod) —
     * the SAME code the editor uses — so the standalone exe no longer
     * double-draws / z-fights the proxy over the real streamed buildings.  The
     * runtime has no extra per-chunk concern, so no chained callback. */
    jce_world_streamer_attach_hlod(s_world_streamer, s_scene, NULL, NULL);
    LOG_INFO("app", "world streaming active (%u chunks, r=%.0f/%.0f)",
             jce_world_streamer_chunk_count(s_world_streamer),
             wsc.load_radius, wsc.unload_radius);
}

/* Resolve an asset-relative path (as written in scene JSON) to an absolute
 * path jce_fs_host_read_all can open, by anchoring it under the staged cooked
 * tree (<exe_dir>/<cooked_assets>/).  The shipped exe runs with CWD == exe dir
 * (or any other dir), never the cooked-tree root, so engine-side file loads
 * that bypass the PAK (anim state machines, terrain meta/bin, HDR, etc.) would
 * otherwise be opened relative to the process CWD and fail — the same class of
 * bug the editor avoids by installing its own resolver.  Returns false (leave
 * the path as-is) for already-absolute inputs or when the anchored file does
 * not exist, so PAK-backed and embedded-bundle projects are unaffected. */
static bool s_default_resolve_path(const char *in, char *out, int outsz, void *ud)
{
    (void)ud;
    if (!in || !in[0] || !out || outsz <= 0) return false;
    /* Already absolute (drive letter, UNC, or POSIX root) → use as-is. */
    if (in[0] == '/' || in[0] == '\\' ||
        (in[0] && in[1] == ':')) return false;

    char base[1024] = {0};
    if (!jce_fs_host_get_base_path(base, sizeof(base))) return false;
    const char *cooked = (s_project && s_project->cooked_assets &&
                          s_project->cooked_assets[0])
                         ? s_project->cooked_assets : "resources/_cooked";
    int n = snprintf(out, (size_t)outsz, "%s%s/%s", base, cooked, in);
    if (n <= 0 || n >= outsz) return false;
    return jce_fs_host_exists_file(out);
}

static JceMesh *s_default_load_mesh(const char *path, void *ud)
{
    (void)ud;
    /* Load .glb / .gltf / .obj geometry from the overlaid PAK chain.
     * When a bundle is mounted (jce_pak_overlay_push), the PAK walk
     * automatically finds files inside the bundle, including
     * bundle-converted _external/<hash>.glb meshes.
     *
     * Results are cached by path: the renderer calls this many times per
     * frame (once per shadow cascade / depth / main pass per entity), and
     * each import is expensive (decompress + Assimp + GPU upload). */
    if (!s_engine_pak || !path || path[0] == '\0') return NULL;

    for (int i = 0; i < s_mesh_cache_count; ++i) {
        if (s_mesh_cache[i].used &&
            strncmp(s_mesh_cache[i].path, path,
                    sizeof s_mesh_cache[i].path) == 0)
            return s_mesh_cache[i].failed ? NULL : s_mesh_cache[i].mesh;
    }

    JceMesh *mesh = jce_model_importer_load_pak(s_engine_pak, path);

    if (s_mesh_cache_count < JCE_DEFAULT_MESH_CACHE_MAX) {
        int idx = s_mesh_cache_count++;
        snprintf(s_mesh_cache[idx].path, sizeof s_mesh_cache[idx].path,
                 "%s", path);
        s_mesh_cache[idx].mesh   = mesh;
        s_mesh_cache[idx].used   = true;
        s_mesh_cache[idx].failed = (mesh == NULL);
    }
    return mesh;
}

/* Renderer anim-event hook → runtime script dispatch (P1 anim-events).  The
 * scene renderer fires this for every authored animation frame event in the
 * (prev,cur] clip-time window; we forward it to the firing entity's gameplay
 * script (on_anim_event) through the runtime.  `user` is the JceRuntime*. */
static void s_default_anim_event_cb(uint64_t entity, const JceAnimEvent *ev,
                                    void *user)
{
    jce_runtime_dispatch_anim_event((JceRuntime *)user, entity, ev);
}

/* Renderer anim-state hook → runtime script dispatch (state-enter/exit).  The
 * scene renderer fires this once whenever a bound animation state machine's
 * active state changes; we forward it to the entity's gameplay script
 * (on_state_exit / on_state_enter) through the runtime.  `user` is the
 * JceRuntime*. */
static void s_default_anim_state_cb(uint64_t entity, const char *from_state,
                                    const char *to_state, void *user)
{
    jce_runtime_dispatch_anim_state((JceRuntime *)user, entity,
                                    from_state, to_state);
}

/* Renderer ground-query hook → runtime physics raycast (Foot IK).  The scene
 * renderer calls this per foot to find the ground under the ankle. */
static bool s_default_ground_query_cb(uint64_t entity, const float origin[3],
                                      const float dir[3], float max_dist,
                                      float *out_hit_y, float out_normal[3],
                                      void *user)
{
    (void)entity;
    return jce_runtime_ground_raycast((JceRuntime *)user, origin, dir, max_dist,
                                      out_hit_y, out_normal);
}

static bool app_init(const JceServices *svc, void *ud)
{
    (void)ud;
    s_svc = svc;
    jce_default_mount_project_bundles();

    /* Promote bundle[0] as base render PAK when project ships no
     * cooked tree (jbundle-only projects).  Otherwise overlay all
     * bundles behind svc->pak so engine subsystems see one merged
     * archive. */
    s_engine_pak = svc ? (JcePakArchive *)svc->pak : NULL;
    if (s_engine_pak) {
        for (int i = 0; i < s_bundle_count; ++i) {
            JcePakArchive *bp =
                (JcePakArchive *)jce_bundle_file_pak(s_bundle_files[i]);
            if (bp) jce_pak_overlay_push(s_engine_pak, bp);
        }
    } else if (s_bundle_count > 0) {
        s_engine_pak =
            (JcePakArchive *)jce_bundle_file_pak(s_bundle_files[0]);
        for (int i = 1; i < s_bundle_count; ++i) {
            JcePakArchive *bp =
                (JcePakArchive *)jce_bundle_file_pak(s_bundle_files[i]);
            if (bp && s_engine_pak)
                jce_pak_overlay_push(s_engine_pak, bp);
        }
        if (s_engine_pak)
            LOG_INFO("app", "no engine PAK — promoted bundle '%s' as render PAK",
                     jce_bundle_file_id(s_bundle_files[0]));
    }

    s_project = jce_project_load(".");
    if (!s_project)
        LOG_WARN("app", "%s", "jce_project.json not found — running with defaults");
    jce_default_load_startup_scene(s_project);

    JceCameraDesc cam_desc = {0};
    cam_desc.mode       = JCE_CAMERA_PERSPECTIVE;
    cam_desc.position   = jce_v3(0.0f, 2.0f, 5.0f);
    cam_desc.target     = jce_v3(0.0f, 0.5f, 0.0f);
    cam_desc.up         = jce_v3(0.0f, 1.0f, 0.0f);
    cam_desc.fov_deg    = 60.0f;
    cam_desc.near_plane = 0.1f;
    cam_desc.far_plane  = 1000.0f;
    s_camera = jce_camera_create(&cam_desc);

    if (svc && svc->renderer) {
        JceSceneRendererCallbacks cbs = {0};
        cbs.load_mesh    = s_default_load_mesh;
        /* Anchor engine-side relative file loads (anim state machines, terrain
         * meta/bin, HDR, ...) under the staged cooked tree so they resolve in a
         * shipped exe whose CWD is not the cooked-tree root.  Mirrors the
         * editor's own resolver; harmless for PAK/bundle-only projects (returns
         * false → path used as-is). */
        cbs.resolve_path = s_default_resolve_path;
        s_scene_renderer = jce_scene_renderer_create(
                               svc->renderer, s_engine_pak, &cbs);
        /* A shipped game is always "playing": enable the animation
         * state-machine / auto-locomotion driver that the editor only
         * turns on during Play (otherwise authored .anim_sm.json bindings
         * and auto_speed stay inert in deployed exes). */
        if (s_scene_renderer)
            jce_scene_renderer_set_anim_sm_active(s_scene_renderer, true);
    }
    if (!s_scene_renderer)
        LOG_WARN("app", "%s", "jce_scene_renderer_create failed — scene will not render");

    /* Occlusion culler (M5): activate GPU-query two-pass coherence culling in
     * the shipped runtime, mirroring the editor scene-view.  Only the engine's
     * embedded 'color' program is needed for the depth-only proxy draws, so this
     * works in a shipped exe (engine shaders are embedded; see JCE_EMBED_ENGINE
     * _SHADERS).  Opt-OUT via JCE_DISABLE_OCCLUSION=1 (A/B + safety hatch, mirrors
     * JCE_DISABLE_WCACHE).  Uses the default proxy view (254); the runtime has a
     * single scene-render path per frame so no second culler shares the view. */
    if (svc && svc->renderer) {
        const char *dis = getenv("JCE_DISABLE_OCCLUSION");
        if (dis && dis[0] && dis[0] != '0') {
            LOG_INFO("app", "%s",
                     "JCE_DISABLE_OCCLUSION set — runtime occlusion culling OFF");
        } else {
            JceShaderSet oc_shaders;
            memset(&oc_shaders, 0, sizeof(oc_shaders));
            JceShaderHandle ch = jce_renderer_get_program_color(svc->renderer);
            oc_shaders.color.idx = ch.idx;
            JceOcclusionConfig oc_cfg = jce_occlusion_config_default();
            s_occlusion_culler = jce_occlusion_culler_create(&oc_cfg, &oc_shaders);
            if (!s_occlusion_culler)
                LOG_WARN("app", "%s",
                         "occlusion culler creation failed (runtime culling disabled)");
        }
    }

    /* ECS-UI (Canvas/UIImage/UIText/UIButton) overlay renderer.  Authored UI
     * components in the scene render in the deployed game exactly as they
     * preview in the editor game-view. */
    if (svc && svc->renderer) {
        s_ui_canvas = jce_ui_canvas_create(svc->renderer, s_engine_pak);
        if (!s_ui_canvas)
            LOG_WARN("app", "%s", "jce_ui_canvas_create failed — ECS-UI will not render");
    }

    /* Physics layer collision matrix (Top 4 — last-mile parity with editor
     * Play): load the project's authored matrix BEFORE jce_runtime_create so
     * bodies spawn with the correct (group,mask) collision filter, exactly like
     * the editor pushes it before its own runtime create.  The build exports it
     * into the cooked tree as `physics_layers.json` (jce.physlayers.v1); absent
     * ⇒ engine default (all layers collide).  Host-fs only (loose cooked tree —
     * the default stage_loose package layout). */
    {
        char base[1024] = {0};
        if (jce_fs_host_get_base_path(base, sizeof(base))) {
            const char *cooked = (s_project && s_project->cooked_assets &&
                                  s_project->cooked_assets[0])
                                 ? s_project->cooked_assets : "resources/_cooked";
            char lpath[1024];
            int n = snprintf(lpath, sizeof(lpath), "%s%s/physics_layers.json",
                             base, cooked);
            if (n > 0 && n < (int)sizeof(lpath) &&
                jce_physics_layer_matrix_load_json(lpath))
                LOG_INFO("app", "physics layer matrix loaded: %s", lpath);
        }
    }

    /* Project-wide quality settings (Top 5): load the build-exported
     * render_settings.json from the cooked tree.  lod_bias applies globally
     * now; the shadow tier folds into the scene render config each frame via
     * s_default_scene_cfg().  Missing file ⇒ engine defaults. */
    {
        char base[1024] = {0};
        if (jce_fs_host_get_base_path(base, sizeof(base))) {
            const char *cooked = (s_project && s_project->cooked_assets &&
                                  s_project->cooked_assets[0])
                                 ? s_project->cooked_assets : "resources/_cooked";
            char rpath[1024];
            int n = snprintf(rpath, sizeof(rpath), "%s%s/render_settings.json",
                             base, cooked);
            if (n > 0 && n < (int)sizeof(rpath) &&
                jce_render_settings_load_json(rpath, &s_render_settings)) {
                s_render_settings_loaded = true;
                jce_texture_set_global_mip_bias((int8_t)s_render_settings.lod_bias);
                /* Window-period graphics: vsync + MSAA are swapchain reset
                 * flags, applied here via a GPU reset (the renderer is already
                 * created).  HDR is handled by the pipeline's internal HDR
                 * offscreen target + tonemap, not a backbuffer flag. */
                if (svc && svc->renderer) {
                    jce_renderer_set_vsync(svc->renderer, s_render_settings.vsync != 0);
                    jce_renderer_set_msaa(svc->renderer, s_render_settings.msaa);
                }
                /* Grass rendering project gate (Stage 1b.6). */
                if (s_scene_renderer)
                    jce_scene_renderer_set_grass_enabled(s_scene_renderer,
                        s_render_settings.grass_enabled != 0);
                LOG_INFO("app", "render settings loaded: %s (vsync=%d msaa=%d)",
                         rpath, s_render_settings.vsync, s_render_settings.msaa);
            }
        }
    }

    if (s_scene) {
        JceRuntimeDesc rd = (JceRuntimeDesc){0};
        rd.scene          = s_scene;
        rd.pak            = s_engine_pak;
        rd.audio          = svc ? svc->audio : NULL;
        rd.enable_physics = true;

        /* Game L10n: prefer the on-disk cooked tree's i18n dir
         * (<exe_dir>/<cooked_assets>/i18n) so shipped games hot-load
         * locale edits; bundle-embedded exes fall through to rd.pak's
         * "i18n/<locale>.json" source inside jce_runtime_create.  The
         * initial locale comes from jce.ini ([app] locale=zh_cn) when
         * set; otherwise the runtime auto-detects from the OS. */
        static char s_loc_dir[1024];
        {
            char base[1024] = {0};
            if (jce_fs_host_get_base_path(base, sizeof(base))) {
                const char *cooked =
                    (s_project && s_project->cooked_assets &&
                     s_project->cooked_assets[0])
                    ? s_project->cooked_assets : "resources/_cooked";
                int n = snprintf(s_loc_dir, sizeof(s_loc_dir),
                                 "%s%s/i18n", base, cooked);
                if (n > 0 && n < (int)sizeof(s_loc_dir) &&
                    jce_fs_host_exists_dir(s_loc_dir))
                    rd.locales_dir = s_loc_dir;
            }
        }
        rd.locale = (svc && svc->config && svc->config->locale[0])
                    ? svc->config->locale : NULL;

        s_runtime = jce_runtime_create(&rd);
        if (!s_runtime)
            LOG_WARN("app", "%s", "jce_runtime_create failed — physics/audio inactive");

        /* Route animation frame events into the gameplay script VM: the scene
         * renderer (which advances the event tracks) now forwards each fired
         * event to the firing entity's on_anim_event script handler via the
         * runtime.  Both handles exist here; harmless if either is NULL. */
        if (s_scene_renderer && s_runtime)
            jce_scene_renderer_set_anim_event_fn(s_scene_renderer,
                                                 s_default_anim_event_cb,
                                                 s_runtime);
        /* Route animation state-machine state changes into the script VM so
         * authored on_state_enter / on_state_exit handlers fire (mirrors the
         * frame-event wiring above). */
        if (s_scene_renderer && s_runtime)
            jce_scene_renderer_set_anim_state_fn(s_scene_renderer,
                                                 s_default_anim_state_cb,
                                                 s_runtime);
        /* Foot IK: install the renderer's ground-query hook to the runtime's
         * physics raycast so authored FootIk components adapt feet to terrain. */
        if (s_scene_renderer && s_runtime)
            jce_scene_renderer_set_ground_query_fn(s_scene_renderer,
                                                   s_default_ground_query_cb,
                                                   s_runtime);
    }

    /* Open-world streaming (no-op unless the scene's streaming settings
     * are enabled and carry registered chunks). */
    jce_default_init_world_streaming(s_project);

    /* Unconditional cursor capture so FPS-look feels like editor Play. */
    if (svc && svc->window) {
        jce_window_set_relative_mouse_mode(svc->window, true);
        jce_window_set_mouse_grab        (svc->window, true);
    }
    return true;
}

/* Editor-authored action map drives movement when the action exists;
 * the raw scancode is the fallback so a missing/renamed action never
 * strands the player. The engine already loads input_actions.json and
 * updates the map every frame (QW-input-actions) — this is the consumer
 * side that was historically missing. */
static bool dm_act_down(const JceInput *in, const JceInputActions *acts,
                        const char *name, int fallback_key)
{
    if (acts) {
        int id = jce_action_find(acts, name);
        if (id >= 0) return jce_action_down(acts, id);
    }
    return jce_input_key_down(in, fallback_key);
}

static void app_update(float dt, void *ud)
{
    (void)ud;
    s_last_dt = dt;
    if (!s_svc || !s_svc->input) return;
    const JceInput *in = s_svc->input;
    const JceInputActions *acts = s_svc->actions;

    /* Tab toggles FPS-look cursor capture.  Uncaptured ⇒ a free OS cursor the
     * player can click in-game UI with (FEATURE 4.1); captured ⇒ classic
     * mouse-look.  Apply the window mode change on the edge only. */
    if (jce_input_key_pressed(in, JCE_KEY_TAB)) {
        s_cursor_captured = !s_cursor_captured;
        if (s_svc->window) {
            jce_window_set_relative_mouse_mode(s_svc->window, s_cursor_captured);
            jce_window_set_mouse_grab        (s_svc->window, s_cursor_captured);
        }
    }

    /* Movement is camera-relative (W = into-the-screen) just like the
     * editor's Play view, so look direction defines move direction.
     * Only a unit DIRECTION plus button state is pushed — speeds and the
     * jump arc come from the scene's CharacterController component, so
     * the deployed exe and the editor share the same authored feel. */
    if (s_runtime) {
        JceRuntimeInput ri = (JceRuntimeInput){0};

        float fx = 0.0f, fz = 0.0f, rx = 0.0f, rz = 0.0f;
        if (s_camera) {
            jce_vec3 fwd   = jce_camera_get_forward(s_camera);
            jce_vec3 right = jce_camera_get_right  (s_camera);
            fwd.y = 0.0f; right.y = 0.0f;
            float fl = sqrtf(fwd.x*fwd.x   + fwd.z*fwd.z);
            float rl = sqrtf(right.x*right.x + right.z*right.z);
            if (fl > 0.0001f) { fx = fwd.x/fl;   fz = fwd.z/fl;   }
            if (rl > 0.0001f) { rx = right.x/rl; rz = right.z/rl; }
        }
        float wx = 0.0f, wz = 0.0f;
        if (dm_act_down(in, acts, "move_forward", JCE_KEY_W)) { wx += fx; wz += fz; }
        if (dm_act_down(in, acts, "move_back",    JCE_KEY_S)) { wx -= fx; wz -= fz; }
        if (dm_act_down(in, acts, "move_right",   JCE_KEY_D)) { wx += rx; wz += rz; }
        if (dm_act_down(in, acts, "move_left",    JCE_KEY_A)) { wx -= rx; wz -= rz; }
        float wlen = sqrtf(wx*wx + wz*wz);
        if (wlen > 0.0001f) { wx /= wlen; wz /= wlen; }
        ri.walk_x = wx;
        ri.walk_z = wz;

        bool jump_now = dm_act_down(in, acts, "jump", JCE_KEY_SPACE);
        ri.jump_pressed = jump_now && !s_jump_edge;
        ri.jump_held    = jump_now;
        s_jump_edge     = jump_now;
        ri.speed_mult   = 1.0f;
        ri.sprint = dm_act_down(in, acts, "sprint", JCE_KEY_LSHIFT) ||
                    jce_input_key_down(in, JCE_KEY_RSHIFT);
        ri.attack_pressed = dm_act_down(in, acts, "attack", JCE_KEY_J);
        if (jce_input_key_down(in, JCE_KEY_LCTRL)  ||
            jce_input_key_down(in, JCE_KEY_RCTRL))  ri.speed_mult = 0.25f;
        jce_runtime_set_input(s_runtime, &ri);
        /* Bind the live action map so gameplay scripts can read authored verbs
         * and axes by name (jce.is_action_down / get_axis), beyond the fixed
         * walk/jump/sprint/attack fields above. */
        jce_runtime_set_actions(s_runtime, acts);
        jce_runtime_step(s_runtime, dt);
    }

    /* Drive chunk streaming from the live camera position (cooperative
     * mode: pending loads/applies run inside this call, on this thread). */
    if (s_world_streamer && s_camera)
        jce_world_streamer_update(s_world_streamer,
                                  jce_camera_get_position(s_camera));

    if (!s_camera) return;

    /* Cinemachine-style VCam override — parity with the editor game view
     * (jce_panel_game_view.cpp does the same in Play mode): when the scene
     * has any active VirtualCamera, its damped blended pose drives the live
     * camera and wins over both mouse-look and the player-follow / free-fly
     * logic below for this frame.  When no VCam is active, `vout` is left
     * untouched and we fall through to the FPS controls. */
    if (s_scene) {
        JceVcamOutput vout;
        bool has_vcam = false;
        jce_vcam_system_evaluate(s_scene, dt, &vout, &has_vcam);
        if (has_vcam) {
            jce_camera_set_position(s_camera,
                jce_v3(vout.position[0], vout.position[1], vout.position[2]));
            jce_camera_look_at(s_camera,
                jce_v3(vout.target[0], vout.target[1], vout.target[2]));
            jce_camera_set_fov(s_camera, vout.fov_deg);
            return;
        }
    }

    /* FPS look while the cursor is captured: cursor is grabbed so delta is
     * pure mouse motion.  Mirror editor panel_game_view convention:
     *  - +dx → look right
     *  - -dy → look up (mouse-up = look-up; standard non-inverted)
     * While uncaptured (Tab) the mouse is a free UI cursor and must not
     * steer the camera. */
    if (s_cursor_captured) {
        float dx = 0.0f, dy = 0.0f;
        jce_input_mouse_delta(in, &dx, &dy);
        if (dx != 0.0f || dy != 0.0f) {
            const float sens = 0.0025f;
            jce_camera_rotate(s_camera, dx * sens, -dy * sens);
        }
    }

    /* Detach-cam toggle (default_main only): F flips first-person player-follow
     * <-> free-fly.  Editor viewports have their own cameras and are unaffected.
     * Manual rising-edge guard (down && !prev) — no key_pressed helper assumed.
     * JCE_KEY_F == 9 (jce_keys.h:29). */
    static bool s_free_cam      = false;
    static bool s_free_cam_prev = false;
    bool f_now = jce_input_key_down(in, JCE_KEY_F);
    if (f_now && !s_free_cam_prev) s_free_cam = !s_free_cam;
    s_free_cam_prev = f_now;

    jce_vec3 player_pos;
    if (!s_free_cam && s_runtime && jce_runtime_get_player_position(s_runtime, &player_pos)) {
        /* Third-person follow: orbit the camera behind+above the player and
         * look past them, so the playable character stays visible (showcase /
         * Genshin-style).  Mouse yaw orbits the rig; F toggles to free-fly.
         * Shared with the editor Game View (jce_camera_third_person_follow) so
         * editor-Play and the runtime frame the scene identically (WYSIWYG). */
        jce_camera_third_person_follow(s_camera, player_pos);
    } else {
        float speed = 20.0f;
        if (jce_input_key_down(in, JCE_KEY_LSHIFT) ||
            jce_input_key_down(in, JCE_KEY_RSHIFT)) speed *= 3.0f;
        if (jce_input_key_down(in, JCE_KEY_LCTRL)  ||
            jce_input_key_down(in, JCE_KEY_RCTRL))  speed *= 0.25f;
        float step = speed * dt;
        if (jce_input_key_down(in, JCE_KEY_W)) jce_camera_move_forward(s_camera,  step);
        if (jce_input_key_down(in, JCE_KEY_S)) jce_camera_move_forward(s_camera, -step);
        if (jce_input_key_down(in, JCE_KEY_D)) jce_camera_move_right  (s_camera,  step);
        if (jce_input_key_down(in, JCE_KEY_A)) jce_camera_move_right  (s_camera, -step);
        if (jce_input_key_down(in, JCE_KEY_E) ||
            jce_input_key_down(in, JCE_KEY_SPACE)) jce_camera_move_up(s_camera,  step);
        if (jce_input_key_down(in, JCE_KEY_Q)) jce_camera_move_up     (s_camera, -step);
    }
}

/* Build the scene render config from defaults, folding in the project-wide
 * quality settings (Top 5) as the DEFAULT.  Per-scene JceSceneRenderingSettings
 * still override these inside jce_scene_renderer_render. */
static JceSceneRenderConfig s_default_scene_cfg(void)
{
    JceSceneRenderConfig c = jce_scene_render_config_default();
    if (s_render_settings_loaded) {
        if (s_render_settings.shadow_quality <= 0)    c.draw_shadows    = false;
        if (s_render_settings.shadow_map_size > 0)    c.shadow_map_size = (uint16_t)s_render_settings.shadow_map_size;
        if (s_render_settings.shadow_cascades > 0)    c.csm_cascades    = (uint8_t)s_render_settings.shadow_cascades;
        if (s_render_settings.shadow_distance > 0.0f) c.shadow_distance = s_render_settings.shadow_distance;
    }
    /* Two-pass GPU-query occlusion culling (M5): the renderer drives begin_frame
     * / entity_visible / submit_query internally from this pointer.  NULL (when
     * disabled / unsupported) keeps the old always-visible behaviour. */
    c.occlusion_culler = s_occlusion_culler;
    return c;
}

static void app_draw(const JceServices *svc, void *ud)
{
    (void)ud;
    if (!svc || !svc->renderer || !s_scene_renderer || !s_scene || !s_camera)
        return;

    /* Scene render (Top 1 — shipped postfx parity with the editor game view).
     * When the scene authors any post-processing effect, render into an
     * offscreen HDR target and run the engine's OWN postfx pipeline (the same
     * one jce_scene_renderer_render configures from JceSceneRenderingSettings),
     * then present to the backbuffer.  Otherwise — the common case — keep the
     * zero-overhead direct-to-backbuffer path.  Any failure in the postfx path
     * falls through to the direct path so the window is never black. */
    bool present_done = false;
    uint32_t sw = 0, sh = 0;
    if (svc->window) jce_window_get_size(svc->window, &sw, &sh);
    JcePostFXPipeline *pfx = jce_scene_renderer_get_postfx(s_scene_renderer);
    if (pfx && sw > 0 && sh > 0) {
        if (!s_post_target) {
            s_post_target = jce_offscreen_target_create(svc->renderer,
                                                        JCE_VIEW_RUNTIME_GAME);
            /* Re-base the post views high so present (base+20, Stage-1a.5
             * worst case with 6-mip bloom pyramid) never collides with the
             * offscreen target's shadow/fog sub-views (30..46).  100+20=120
             * stays well below ImGui (250).  Safe in shipped exe: no editor
             * preview/pick shares the pipeline. */
            if (s_post_target) jce_postfx_set_view_base(pfx, 100);
        }
        if (s_post_target) {
            float aspect = (float)sw / (float)sh;
            jce_mat4 view = jce_camera_view(s_camera);
            jce_mat4 proj = jce_camera_proj(s_camera, aspect,
                                            jce_gfx_caps().homogeneous_depth);
            /* HDR target: force tone mapping so the PBR linear output maps to
             * display range (else washed out).  No-op on the RGBA8 fallback. */
            if (jce_offscreen_target_is_hdr(s_post_target))
                jce_postfx_enable(pfx, JCE_POSTFX_TONEMAP, true);
            if (jce_offscreen_target_prepare(s_post_target, sw, sh,
                                             view.raw[0], proj.raw[0],
                                             0x000000FFu, "RuntimeScene")) {
                JceSceneRenderConfig pcfg = s_default_scene_cfg();
                uint16_t base = jce_offscreen_target_get_view_id(s_post_target);
                /* Postfx path renders into the offscreen target — bind the
                 * occlusion proxy view to its FBO so the proxy depth test reads
                 * the depth the color pass wrote (not the backbuffer → would
                 * make occlusion inert or false-cull visible geometry).  The
                 * no-postfx path below keeps the default UINT16_MAX (backbuffer),
                 * which is exactly where it draws. */
                pcfg.scene_frame_buffer =
                    jce_offscreen_target_get_frame_buffer(s_post_target);
                pcfg.viewport_width  = sw;
                pcfg.viewport_height = sh;
                jce_scene_renderer_render(s_scene_renderer, s_scene, s_camera,
                                          base, s_last_dt, &pcfg);
                bool any_effect = false;
                for (int i = 0; i < JCE_POSTFX_COUNT; ++i)
                    if (jce_postfx_is_enabled(pfx, (JcePostFXType)i)) {
                        any_effect = true; break;
                    }
                if (any_effect) {
                    jce_postfx_resize(pfx, sw, sh);
                    JceTextureHandle color = {
                        jce_offscreen_target_get_color_texture(s_post_target) };
                    JceTextureHandle depth = {
                        jce_offscreen_target_get_depth_texture(s_post_target) };
                    if (jce_gfx_texture_valid(color)) {
                        jce_postfx_apply(pfx, color, depth);
                        if (jce_gfx_texture_valid(jce_postfx_get_output(pfx))) {
                            jce_postfx_present(pfx, sw, sh);
                            present_done = true;
                        }
                    }
                }
            }
        }
    }
    if (!present_done) {
        jce_renderer_begin_frame_3d(svc->renderer, svc->window,
                                    s_camera, JCE_VIEW_MAIN_3D);
        JceSceneRenderConfig cfg = s_default_scene_cfg();
        /* Direct-to-backbuffer: scene_frame_buffer stays UINT16_MAX (backbuffer),
         * which is exactly where the color pass draws — the occlusion proxy view
         * binds to the same backbuffer.  Give it the window rect so the proxy
         * raster matches. */
        if (sw > 0 && sh > 0) { cfg.viewport_width = sw; cfg.viewport_height = sh; }
        jce_scene_renderer_render(s_scene_renderer, s_scene, s_camera,
                                  JCE_VIEW_MAIN_3D, s_last_dt, &cfg);
    }

    /* ECS-UI overlay on top of the 3D scene, into the backbuffer on the
     * dedicated UI view (FEATURE 4.1).  While the cursor is captured for
     * FPS-look the OS pointer is pinned/hidden, so authored UI is purely
     * presentational (HUD / labels / backgrounds) and we feed NULL.  When the
     * player frees the cursor (Tab → !s_cursor_captured) we build a real
     * JceUIPointer from the input system — exactly like the editor Game View's
     * pointer (jce_panel_game_view.cpp) — so authored UIButtons hover / press /
     * click.  A click is then drained from the canvas and dispatched to the
     * gameplay script VM through the runtime, making shipped in-game buttons
     * actually do something. */
    if (s_ui_canvas && svc->window) {
        uint32_t sw = 0, sh = 0;
        jce_window_get_size(svc->window, &sw, &sh);
        if (sw > 0 && sh > 0) {
            JceUIPointer ptr;
            const JceUIPointer *ptr_arg = NULL;
            if (!s_cursor_captured && svc->input) {
                float mx = 0.0f, my = 0.0f;
                jce_input_mouse_pos(svc->input, &mx, &my);
                ptr.x     = mx;
                ptr.y     = my;
                ptr.down  = jce_input_mouse_button(svc->input,
                                                   JCE_MOUSE_BUTTON_LEFT);
                ptr.valid = true;
                ptr_arg   = &ptr;
            }
            /* ── InputField text/edit channel (single-line text entry) ──
             * Forward editing keys to the focused ECS-UI InputField using the
             * polling input API (these scancodes are pollable), then toggle OS
             * text input as focus changes.  We feed keys BEFORE the render so
             * they apply to the focus established last frame, and the render
             * below re-evaluates focus from this frame's pointer.
             *
             * NOTE: the polling JceInput API exposes no UTF-8 character stream
             * (only key state), so the *character* channel below is a clearly
             * marked hook: when this drop-in main is replaced with a project
             * main.c that registers a JceAppDesc.on_event callback, route
             *   JCE_EVENT_TEXT_INPUT  → jce_ui_canvas_text_input(s_ui_canvas, ev.text.text)
             *   JCE_EVENT_KEY_DOWN     → jce_ui_canvas_key_edit(s_ui_canvas, ev.key.scancode, ev.key.mod)
             *   JCE_EVENT_MOUSE_WHEEL  → jce_ui_canvas_scroll(s_ui_canvas, ev.wheel.x, ev.wheel.y)
             * (the reference wiring).  Starting OS text input here means SDL is
             * already emitting those text events for that future callback.
             * See deviations/followups. */
            if (svc->input && jce_ui_canvas_focused_input(s_ui_canvas)) {
                static const struct { int key; } s_edit_keys[] = {
                    { JCE_KEY_BACKSPACE }, { JCE_KEY_DELETE },
                    { JCE_KEY_LEFT }, { JCE_KEY_RIGHT },
                    { JCE_KEY_HOME }, { JCE_KEY_END },
                    { JCE_KEY_RETURN }, { JCE_KEY_KP_ENTER },
                    { JCE_KEY_ESCAPE },
                };
                for (size_t i = 0; i < sizeof(s_edit_keys)/sizeof(s_edit_keys[0]); ++i)
                    if (jce_input_key_pressed(svc->input, s_edit_keys[i].key))
                        jce_ui_canvas_key_edit(s_ui_canvas, s_edit_keys[i].key, 0);
            }

            jce_ui_canvas_render(s_ui_canvas, s_scene, JCE_VIEW_UI, UINT16_MAX,
                                 (float)sw, (float)sh, ptr_arg, s_last_dt);

            /* ── ScrollView wheel channel ──────────────────────────────
             * Feed the (vertical) mouse wheel to the scroll view under the
             * pointer, AFTER the render so the canvas has resolved this frame's
             * hovered scroll view.  The polling JceInput exposes only a vertical
             * wheel (+y = up), matching jce_ui_canvas_scroll's dy convention; a
             * project main.c with an on_event callback can additionally forward
             * ev.wheel.x for horizontal scrolling (see reference wiring above).
             * Fire-and-forget: a no-op when no scroll view is hovered. */
            if (ptr_arg && svc->input) {
                float wheel = jce_input_mouse_wheel(svc->input);
                if (wheel != 0.0f)
                    jce_ui_canvas_scroll(s_ui_canvas, 0.0f, wheel);
            }

            /* OS text-input follows InputField focus (toggle on the edge so we
             * don't spam the platform layer). */
            {
                static bool s_text_input_on = false;
                bool want = jce_ui_canvas_focused_input(s_ui_canvas) != 0;
                if (want != s_text_input_on) {
                    if (want) jce_window_start_text_input(svc->window);
                    else      jce_window_stop_text_input(svc->window);
                    s_text_input_on = want;
                }
            }

            /* Drain the click the canvas state machine recorded this frame
             * (set only on the release frame, over the same button) and fire
             * the button's authored on_click_handler through the script VM.
             * No-op when nothing was clicked / no handler / no runtime. */
            if (ptr_arg && s_runtime && s_scene) {
                uint64_t clicked = jce_ui_canvas_last_clicked(s_ui_canvas);
                if (clicked) {
                    JceUIButtonComponent *bt =
                        jce_scene_get_ui_button(s_scene, (JceEntity)clicked);
                    if (bt)
                        jce_runtime_dispatch_ui_click(s_runtime, clicked,
                                                      bt->on_click_handler);
                }
                /* Slider drag / toggle flip / dropdown select → on_value_changed;
                 * InputField edits → on_value_changed; RETURN → on_submit.  The
                 * runtime resolves the widget on its own scene and fires the
                 * authored handler; each is a clean no-op when none authored. */
                uint64_t vc = jce_ui_canvas_last_value_changed(s_ui_canvas);
                if (vc) jce_runtime_dispatch_ui_value_changed(s_runtime, vc);
                uint64_t tc = jce_ui_canvas_last_text_changed(s_ui_canvas);
                if (tc) jce_runtime_dispatch_ui_text_changed(s_runtime, tc);
                uint64_t sub = jce_ui_canvas_last_submitted(s_ui_canvas);
                if (sub) jce_runtime_dispatch_ui_submit(s_runtime, sub);
            }
        }
    }
}

static void app_exit(void *ud)
{
    (void)ud;
    /* Streamer first: destroying it removes its streamed entities from
     * s_scene and joins all in-flight chunk tasks (jce_task_wait) before
     * detaching from the fs.  Only then destroy the worker pool (also
     * waits-for-all on shutdown) and the fs the workers were reading from. */
    if (s_world_streamer) { jce_world_streamer_destroy(s_world_streamer);  s_world_streamer = NULL; }
    if (s_stream_pool)    { jce_thread_pool_destroy(s_stream_pool);        s_stream_pool    = NULL; }
    if (s_stream_fs)      { jce_fs_destroy(s_stream_fs);                   s_stream_fs      = NULL; }
    if (s_runtime)        { jce_runtime_destroy(s_runtime);              s_runtime        = NULL; }
    if (s_ui_canvas)      { jce_ui_canvas_destroy(s_ui_canvas);          s_ui_canvas      = NULL; }
    /* Occlusion culler holds bgfx resources (proxy geom + query handles) —
     * destroy before the renderer/bgfx shut down. */
    if (s_occlusion_culler) { jce_occlusion_culler_destroy(s_occlusion_culler); s_occlusion_culler = NULL; }
    /* Offscreen postfx target borrows the renderer — destroy before it. */
    if (s_post_target)    { jce_offscreen_target_destroy(s_post_target);  s_post_target    = NULL; }
    if (s_scene_renderer) { jce_scene_renderer_destroy(s_scene_renderer); s_scene_renderer = NULL; }
    /* Destroy cached meshes (owned here) before tearing the rest down. */
    for (int i = 0; i < s_mesh_cache_count; ++i) {
        if (s_mesh_cache[i].used && s_mesh_cache[i].mesh)
            jce_mesh_destroy(s_mesh_cache[i].mesh);
    }
    s_mesh_cache_count = 0;
    if (s_camera)         { jce_camera_destroy(s_camera);                 s_camera         = NULL; }
    if (s_scene)          { jce_scene_destroy(s_scene);                   s_scene          = NULL; }
    jce_default_unmount_project_bundles();
    if (s_project)        { jce_project_free(s_project);                  s_project        = NULL; }
    s_svc = NULL;
}

#endif /* JCE_DEFAULT_MAIN_INC_H */
