/* Auto-generated by .tmp_gen_morph.py — embedded in-memory glTF for the
 * morph-target import test (test_jce_morph.c).  This is a string-literal
 * fragment included between the opening `=` and the closing `;` of a
 * `static const char[]` definition, so it must contain ONLY adjacent string
 * literals (C concatenates them).  Do not add a trailing comma or semicolon.
 *
 * Contents: a glTF 2.0 scene with one 3-vertex mesh (POSITION + NORMAL +
 * indices), two morph targets (target 0: POSITION +X & NORMAL +Y; target 1:
 * POSITION +2Y), mesh base weights [0.25, 0.75], and a LINEAR "weights"
 * animation channel with keys (t=0 -> (0,0)) and (t=1 -> (1.0, 0.5)). */
    "{\"asset\":{\"version\":\"2.0\"},\"scene\":0,\"scenes\":[{\"nodes\":[0]}],\"nodes\":[{\""
    "mesh\":0,\"name\":\"morphnode\"}],\"meshes\":[{\"name\":\"morphmesh\",\"weights\":[0.25,"
    "0.75],\"primitives\":[{\"attributes\":{\"POSITION\":0,\"NORMAL\":1},\"indices\":2,\"targ"
    "ets\":[{\"POSITION\":3,\"NORMAL\":4},{\"POSITION\":5}]}]}],\"animations\":[{\"name\":\"m"
    "orphanim\",\"samplers\":[{\"input\":6,\"output\":7,\"interpolation\":\"LINEAR\"}],\"chan"
    "nels\":[{\"sampler\":0,\"target\":{\"node\":0,\"path\":\"weights\"}}]}],\"buffers\":[{\""
    "byteLength\":212,\"uri\":\"data:application/octet-stream;base64,AAAAAAAAAAAAAAAAAACAPwAA"
    "AAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAABAAIAAAAAAIA/"
    "AAAAAAAAAAAAAIA/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAACAPwAAAAAAAAAAAACAPwAA"
    "AAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAACAPwAAAAAAAAAAAACAPwAAAD8=\"}]"
    ",\"bufferViews\":[{\"buffer\":0,\"byteOffset\":0,\"byteLength\":36},{\"buffer\":0,\"byte"
    "Offset\":36,\"byteLength\":36},{\"buffer\":0,\"byteOffset\":72,\"byteLength\":6},{\"buff"
    "er\":0,\"byteOffset\":80,\"byteLength\":36},{\"buffer\":0,\"byteOffset\":116,\"byteLengt"
    "h\":36},{\"buffer\":0,\"byteOffset\":152,\"byteLength\":36},{\"buffer\":0,\"byteOffset\""
    ":188,\"byteLength\":8},{\"buffer\":0,\"byteOffset\":196,\"byteLength\":16}],\"accessors"
    "\":[{\"bufferView\":0,\"componentType\":5126,\"count\":3,\"type\":\"VEC3\",\"min\":[0,0,"
    "0],\"max\":[1,1,0]},{\"bufferView\":1,\"componentType\":5126,\"count\":3,\"type\":\"VEC3"
    "\"},{\"bufferView\":2,\"componentType\":5123,\"count\":3,\"type\":\"SCALAR\"},{\"bufferV"
    "iew\":3,\"componentType\":5126,\"count\":3,\"type\":\"VEC3\"},{\"bufferView\":4,\"compon"
    "entType\":5126,\"count\":3,\"type\":\"VEC3\"},{\"bufferView\":5,\"componentType\":5126,"
    "\"count\":3,\"type\":\"VEC3\"},{\"bufferView\":6,\"componentType\":5126,\"count\":2,\"ty"
    "pe\":\"SCALAR\",\"min\":[0.0],\"max\":[1.0]},{\"bufferView\":7,\"componentType\":5126,\""
    "count\":4,\"type\":\"SCALAR\"}]}"
