/*
 * jce_shader_variants.h  --  GENERATED by tools/shadergen/gen_shader_variants.py -- DO NOT EDIT.
 *
 * WHICH PROGRAM A DRAW GETS, as a pair of coordinates instead of a name. The
 * VERTEX VARIANT is what the draw path is -- static, instanced, skinned, and
 * the three instanced forms that carry extra per-instance data. The KEYWORD
 * BITS are what the material and the frame ask for.
 * jce_renderer_get_program_variant turns the pair into a program, and it is
 * the ONLY place that decision is made.
 *
 * Adding an axis is one entry in contracts/shader-keywords.json. It used to
 * be nine files, and the last attempt wired six of seven selection sites and
 * silently did nothing on the seventh -- which is why the sites no longer
 * choose at all.
 *
 * Layer: renderer (Layer 3) -- public, generated.
 */
#ifndef JCE_SHADER_VARIANTS_H
#define JCE_SHADER_VARIANTS_H

#include <jce/os/core/jce_defs.h>

JCE_EXTERN_C_BEGIN

#define JCE_SHADER_AXIS_COUNT 2
#define JCE_SHADER_VARIANT_COUNT 6
#define JCE_SHADER_KEY_COUNT 4

/*
 * Clustered lighting. Swaps sampler stage 14 from s_iesLut to s_cluster,
 * replaces the 16-light brute-force loop with a per-froxel one, and drops
 * the per-spot IES profile -- a stated tradeoff that keeps WebGL2/GLES3 at
 * 16 fragment samplers. Selected only when the r.forwardplus cvar is on.
 */
#define JCE_SHADER_KEY_FWDPLUS (1u << 0u)
/*
 * Drops the cascade block for a material that does not receive shadows.
 * MEASURED, which is why it is the axis that proves this machinery: fs_pbr
 * is 8311 instructions and CSM is 6766 of them (81.4%), so this is the only
 * axis worth an entry file at all -- a Unity-style pile of material keywords
 * would have been spent on the other 18.6%. No #else is needed: `shadow` is
 * 1.0 above the guarded block and the prologue the rest of the shader
 * consumes stays outside it.
 */
#define JCE_SHADER_KEY_NOSHADOW (1u << 1u)

typedef enum {
    /* Static mesh, one draw. */
    JCE_SHADER_VV_PBR = 0,
    /* GPU-instanced copies of one mesh. */
    JCE_SHADER_VV_PBR_INST = 1,
    /* Skinned mesh; the bone palette is the only difference the fragment sees, which is none. */
    JCE_SHADER_VV_PBR_SKINNED = 2,
    /* Instanced copies that differ only by baseColor. */
    JCE_SHADER_VV_PBR_INST_TINT = 3,
    /* Instanced copies mid LOD-band transition. */
    JCE_SHADER_VV_PBR_INST_FADE = 4,
    /* Instanced copies that differ by albedo texture. */
    JCE_SHADER_VV_PBR_INST_TEX_ARRAY = 5,
} JceShaderVertexVariant;

JCE_EXTERN_C_END

#endif /* JCE_SHADER_VARIANTS_H */
