/* lua_case_runner.c — the LUA half of the cross-language differential.
 *
 * Not a unit test: it is a recorder.  It installs the shared mock host into a
 * real jce_script VM, runs a chunk of manifest-derived cases that
 * differential.py wrote, and prints the recorded stream on stdout.  The Python
 * half drives the SAME cases through the ctypes binding over the SAME mock and
 * prints the same stream; differential.py compares the two texts.
 *
 * WHY THE CHUNK COMES FROM A FILE AND NOT FROM HERE.  The cases must be
 * derived from contracts/script-api.json — never from either emitter —
 * or the expectation would be generated by the thing under test.  Python
 * already reads that file, so the case book lives there and this program stays
 * a transport with no opinion about what a case is.
 *
 * WHY jce.log IS THE WIRE.  This runner deliberately does not link lua::lua or
 * include the engine's private script header: everything it needs to observe
 * is either something the script says (through jce.log, whose mock body
 * appends to the trace) or something the host was asked to do (every other
 * mock body, appending to the same buffer).  One ordered buffer is what makes
 * "the free happened AFTER the string was pushed" a comparable fact rather
 * than two facts that have to be correlated afterwards.
 */

#include <jce/middleware/script/jce_script.h>

#include "jce_script_py_mock.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char *read_all(const char *path, size_t *out_len)
{
    FILE *f = fopen(path, "rb");
    long  n;
    char *buf;

    if (!f)
        return NULL;
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return NULL;
    }
    n = ftell(f);
    if (n < 0) {
        fclose(f);
        return NULL;
    }
    rewind(f);
    buf = (char *)malloc((size_t)n + 1u);
    if (!buf) {
        fclose(f);
        return NULL;
    }
    *out_len = fread(buf, 1, (size_t)n, f);
    buf[*out_len] = '\0';
    fclose(f);
    return buf;
}

int main(int argc, char **argv)
{
    const char   *chunk_path;
    int           mode;
    size_t        len = 0u;
    char         *src;
    JceScript    *s;
    JceScriptInstance inst;

    if (argc != 3 && argc != 4) {
        fprintf(stderr,
                "usage: lua_case_runner <chunk.lua> <mode> [long_strings]\n");
        return 2;
    }
    chunk_path = argv[1];
    mode = atoi(argv[2]);

    src = read_all(chunk_path, &len);
    if (!src) {
        fprintf(stderr, "lua_case_runner: cannot read %s\n", chunk_path);
        return 2;
    }

    jce_mock_reset(mode);
    /* Set AFTER reset: reset does not touch the long-string switch, but
     * ordering it this way keeps the two sides' setup sequence identical to
     * differential.py's, so a future reset that DID clear it would fail on
     * both sides rather than on one. */
    jce_mock_set_long_strings(argc == 4 ? atoi(argv[3]) : 0);

    /* jce_script_create_sized with the MOCK's own sizeof, not this file's.
     * Both are the same struct here, but taking it from the object that
     * defines the host is the habit the short-struct ABI requires: the size
     * must come from the allocator of the table, never from the consumer. */
    s = jce_script_create_sized(jce_mock_host(mode), jce_mock_host_size());
    if (!s) {
        fprintf(stderr, "lua_case_runner: jce_script_create_sized failed\n");
        free(src);
        return 2;
    }

    /* A chunk that fails to compile or fails to return a table yields 0, and
     * every case then "passes" by never running.  That is the exact failure
     * batch 1's harness shipped with -- six hand-written cases whose error
     * strings matched on both sides because neither side ran -- so this is a
     * hard error, not a warning. */
    inst = jce_script_instantiate_source(s, "@jce_py_differential", src, 1u);
    free(src);
    if (inst == 0) {
        fprintf(stderr, "lua_case_runner: the case chunk did not run "
                        "(compile error, or it returned no table)\n");
        fputs(jce_mock_trace_text(), stdout);
        jce_script_destroy(s);
        return 3;
    }

    fputs(jce_mock_trace_text(), stdout);
    printf("LIVE %d\n", jce_mock_live_strings());
    fflush(stdout);

    jce_script_destroy(s);
    return 0;
}
