/*
 * jce_component_registry_internal.h  Registration side of the component
 * registry (INTERNAL — carries cJSON in fn signatures, never installed).
 *
 * The single registration site is jce_scene_components_register_all() in
 * jce_scene_components_json.c, where every component's parse_x and ser_x
 * function is visible.  jce_scene_create() calls it once (self-guarded).
 */

#ifndef JCE_COMPONENT_REGISTRY_INTERNAL_H
#define JCE_COMPONENT_REGISTRY_INTERNAL_H

#include <jce/middleware/scene/jce_component_registry.h>

typedef struct cJSON cJSON;

/* Accessors reuse the public per-type functions generated by
 * JCE_COMP_IMPL (jce_scene_has_x / jce_scene_remove_x). */
typedef bool (*JceCompHasFn)(const JceScene *s, JceEntity e);
typedef void (*JceCompRemoveFn)(JceScene *s, JceEntity e);

/* Parse one component object's properties into the entity.  `props` is
 * the resolved property object (the "properties" child when nested). */
typedef void (*JceCompParseFn)(JceScene *s, JceEntity e, const cJSON *props);

/* Append this component's serialized object(s) — including the "type"
 * field — to `out_array` when present on the entity.  Only called when
 * the row's `has` returned true. */
typedef void (*JceCompSerFn)(JceScene *s, JceEntity e, cJSON *out_array);

/* Type-erased raw accessors over the per-type jce_scene_get_x /
 * jce_scene_set_x functions (registered through strictly-conforming thin
 * adapter functions, never function-pointer casts).  `get` returns the
 * live component pointer or NULL; `set` copies struct_size bytes in,
 * adding the component when absent.  NULL for rows without a direct
 * accessor (unified Light, entity-level Tag/Layer, retired rows). */
typedef void *(*JceCompGetFn)(JceScene *s, JceEntity e);
typedef void  (*JceCompSetFn)(JceScene *s, JceEntity e, const void *data);

typedef struct {
    const char     *name;        /* canonical JSON "type" string */
    const char     *aliases[4];  /* extra accepted spellings (NULL-padded) */
    uint64_t        legacy_flag; /* JCE_COMP_FLAG_* bit; 0 = post-64 row */
    JceCompHasFn    has;
    JceCompRemoveFn remove;
    JceCompParseFn  parse;       /* NULL = no standalone parse (derived) */
    JceCompSerFn    serialize;   /* NULL = serialized elsewhere (derived) */
    JceCompGetFn    get;         /* NULL = no direct accessor */
    JceCompSetFn    set;         /* NULL = no direct setter */
    uint32_t        struct_size; /* sizeof(T); 0 when get/set are NULL */
} JceComponentDesc;

/* Returns the new comp_id, or JCE_COMP_ID_INVALID on a full table /
 * duplicate name.  Registration order defines serialization order —
 * register Transform first. */
int jce_component_register(const JceComponentDesc *d);

/* Full row access for the serializer/editor dispatch loops. */
const JceComponentDesc *jce_component_desc(int comp_id);

/* One-shot registration of every engine component (idempotent).
 * Defined in jce_scene_components_json.c. */
void jce_scene_components_register_all(void);

#endif /* JCE_COMPONENT_REGISTRY_INTERNAL_H */
