$input v_texcoord0, v_worldpos, v_normal, v_tangent, v_bitangent, v_viewdepth, v_localpos, v_tint

/*
 * fs_pbr_tint.sc  --  GENERATED by tools/shadergen/gen_shader_variants.py -- DO NOT EDIT.
 *
 * Per-instance tint. The body multiplies base albedo by v_tint exactly where
 * a solo draw applies u_baseColorFactor, so an instanced tinted copy is
 * bit-identical to the same mesh drawn solo with that colour while still
 * collapsing into one instanced submit.
 *
 * $input MUST stay in this file: shaderc strips the leading $input only from
 * the MAIN .sc, never from an #include'd one. The whole body lives in
 * fs_pbr_body.sh so every variant is built from ONE source of truth by
 * adding defines -- that is what makes an axis one line in
 * contracts/shader-keywords.json instead of a file per family.
 */

#define JCE_INST_TINT
#include "fs_pbr_body.sh"
