$input v_texcoord0, v_worldpos, v_normal, v_tangent, v_bitangent, v_viewdepth, v_localpos, v_tint

/*
 * fs_pbr_tint_noshadow.sc  --  GENERATED by tools/shadergen/gen_shader_variants.py -- DO NOT EDIT.
 *
 * Per-instance tint. The body multiplies base albedo by v_tint exactly where
 * a solo draw applies u_baseColorFactor, so an instanced tinted copy is
 * bit-identical to the same mesh drawn solo with that colour while still
 * collapsing into one instanced submit.
 *
 * +NOSHADOW: Drops the cascade block for a material that does not receive
 * shadows. MEASURED, which is why it is the axis that proves this machinery:
 * fs_pbr is 8311 instructions and CSM is 6766 of them (81.4%), so this is
 * the only axis worth an entry file at all -- a Unity-style pile of material
 * keywords would have been spent on the other 18.6%. No #else is needed:
 * `shadow` is 1.0 above the guarded block and the prologue the rest of the
 * shader consumes stays outside it.
 *
 * $input MUST stay in this file: shaderc strips the leading $input only from
 * the MAIN .sc, never from an #include'd one. The whole body lives in
 * fs_pbr_body.sh so every variant is built from ONE source of truth by
 * adding defines -- that is what makes an axis one line in
 * contracts/shader-keywords.json instead of a file per family.
 */

#define JCE_INST_TINT
#define JCE_NO_CSM 1
#include "fs_pbr_body.sh"
