$input v_texcoord0, v_worldpos, v_normal, v_tangent, v_bitangent, v_viewdepth, v_localpos, v_tint

/*
 * fs_pbr_inst_tex_array.sc  --  GENERATED by tools/shadergen/gen_shader_variants.py -- DO NOT EDIT.
 *
 * Texture-diverse instancing. s_albedo is a SAMPLER2DARRAY and the instance
 * carries its layer, so copies of one mesh that differ by their albedo
 * TEXTURE -- not just a baseColor factor -- batch into one instanced submit.
 *
 * $input MUST stay in this file: shaderc strips the leading $input only from
 * the MAIN .sc, never from an #include'd one. The whole body lives in
 * fs_pbr_body.sh so every variant is built from ONE source of truth by
 * adding defines -- that is what makes an axis one line in
 * contracts/shader-keywords.json instead of a file per family.
 */

#define JCE_TEX_ARRAY
#include "fs_pbr_body.sh"
