$input v_texcoord0, v_worldpos, v_normal, v_tangent, v_bitangent, v_viewdepth, v_localpos

/*
 * fs_pbr_fwdplus.sc  --  GENERATED by tools/shadergen/gen_shader_variants.py -- DO NOT EDIT.
 *
 * The BASE fragment family: the 16-light brute-force point loop with
 * s_iesLut on stage 14. With no axis set it compiles byte-identically to the
 * historical hand-written fs_pbr.sc, which is the property that let this
 * family be generated without changing a pixel.
 *
 * +FWDPLUS: Clustered lighting. Swaps sampler stage 14 from s_iesLut to
 * s_cluster, replaces the 16-light brute-force loop with a per-froxel one,
 * and drops the per-spot IES profile -- a stated tradeoff that keeps
 * WebGL2/GLES3 at 16 fragment samplers. Selected only when the r.forwardplus
 * cvar is on.
 *
 * $input MUST stay in this file: shaderc strips the leading $input only from
 * the MAIN .sc, never from an #include'd one. The whole body lives in
 * fs_pbr_body.sh so every variant is built from ONE source of truth by
 * adding defines -- that is what makes an axis one line in
 * contracts/shader-keywords.json instead of a file per family.
 */

#define JCE_FORWARDPLUS 1
#include "fs_pbr_body.sh"
