$input v_texcoord0, v_worldpos, v_normal, v_tangent, v_bitangent, v_viewdepth, v_localpos

/*
 * fs_pbr.sc  --  GENERATED by tools/shadergen/gen_shader_variants.py -- DO NOT EDIT.
 *
 * The BASE fragment family: the 16-light brute-force point loop with
 * s_iesLut on stage 14. With no axis set it compiles byte-identically to the
 * historical hand-written fs_pbr.sc, which is the property that let this
 * family be generated without changing a pixel.
 *
 * $input MUST stay in this file: shaderc strips the leading $input only from
 * the MAIN .sc, never from an #include'd one. The whole body lives in
 * fs_pbr_body.sh so every variant is built from ONE source of truth by
 * adding defines -- that is what makes an axis one line in
 * contracts/shader-keywords.json instead of a file per family.
 */

#include "fs_pbr_body.sh"
