/*
 * es_palettes.h — GENERATED by build/gen_palettes_h.py from es_palettes.json
 * (extracted from the Elemental-Serenity reference). Do not edit by hand.
 *
 * Index: [season * 2 + tod] with season {0=spring,1=winter,2=autumn,3=rainy}
 * and tod {0=day,1=night}. All colors are LINEAR floats.
 */
#ifndef ES_PALETTES_H
#define ES_PALETTES_H

typedef struct {
    float dome_zenith[3], dome_mid[3], dome_horizon[3], dome_ground[3];
    float body_color[3], glow_color[3];   /* sun (day) / moon (night) disk  */
    float disk_on;                        /* 1 = disk visible (ES gating)    */
    float fog_color[3];
    float ambient[3], ambient_intensity;
    float key_color[3], key_intensity;
    float fill_color[3], fill_intensity;
    float lamp_intensity;                 /* tent lantern                    */
    float water_shallow[3], water_deep[3];
    float shore_ripple, ice_ratio;
    float grass_root[3], grass_tip[3];
    float rocks_tint[3];
    float leaf_tint[3];                   /* bush/canopy card tint           */
    const char *ground_tex;               /* baked ground albedo (PAK path)  */
} EsPreset;

enum { ES_SEASON_SPRING = 0, ES_SEASON_WINTER, ES_SEASON_AUTUMN, ES_SEASON_RAINY };
enum { ES_TOD_DAY = 0, ES_TOD_NIGHT };

static const EsPreset ES_PRESETS[8] = {
    { /* spring / day */
        .dome_zenith  = { 0.000000f, 0.092210f, 0.596921f }, .dome_mid = { 0.112087f, 0.325511f, 1.191752f },
        .dome_horizon = { 0.142193f, 0.404716f, 1.300000f }, .dome_ground = { 0.003420f, 0.196636f, 0.282479f },
        .body_color   = { 1.300000f, 0.972625f, 0.100135f }, .glow_color = { 1.300000f, 0.267150f, 0.000000f }, .disk_on = 1.0f,
        .fog_color    = { 0.248236f, 1.300000f, 1.300000f },
        .ambient      = { 1.000000f, 0.972549f, 0.941176f }, .ambient_intensity = 0.4000f,
        .key_color    = { 1.000000f, 0.956863f, 0.901961f }, .key_intensity = 2.0000f,
        .fill_color   = { 0.529412f, 0.807843f, 0.921569f }, .fill_intensity = 0.6000f,
        .lamp_intensity = 0.0000f,
        .water_shallow = { 0.060000f, 0.500000f, 0.510000f }, .water_deep = { 0.033000f, 0.275000f, 0.280500f },
        .shore_ripple = 1.0f, .ice_ratio = 0.0f,
        .grass_root   = { 0.036548f, 0.236900f, 0.023526f }, .grass_tip = { 0.164490f, 0.309199f, 0.021667f },
        .rocks_tint   = { 0.965000f, 0.840000f, 0.480000f }, .leaf_tint = { 0.100000f, 0.340000f, 0.080000f },
        .ground_tex   = "textures/ground_baked2/spring_day.png",
    },
    { /* spring / night */
        .dome_zenith  = { 0.006000f, 0.015000f, 0.045000f }, .dome_mid = { 0.010500f, 0.022500f, 0.060000f },
        .dome_horizon = { 0.015000f, 0.030000f, 0.075000f }, .dome_ground = { 0.030000f, 0.045000f, 0.090000f },
        .body_color   = { 0.950000f, 0.950000f, 1.000000f }, .glow_color = { 0.450980f, 0.556863f, 0.768627f }, .disk_on = 1.0f,
        .fog_color    = { 0.000000f, 0.003300f, 0.011700f },
        .ambient      = { 0.290196f, 0.333333f, 0.407843f }, .ambient_intensity = 0.0176f,
        .key_color    = { 0.239216f, 0.352941f, 0.478431f }, .key_intensity = 0.2750f,
        .fill_color   = { 0.239216f, 0.352941f, 0.478431f }, .fill_intensity = 0.0330f,
        .lamp_intensity = 0.4000f,
        .water_shallow = { 0.018000f, 0.150000f, 0.180000f }, .water_deep = { 0.009900f, 0.082500f, 0.099000f },
        .shore_ripple = 0.5f, .ice_ratio = 0.0f,
        .grass_root   = { 0.000000f, 0.743910f, 0.000000f }, .grass_tip = { 0.384583f, 0.531223f, 0.000000f },
        .rocks_tint   = { 0.202500f, 0.172500f, 0.094500f }, .leaf_tint = { 0.050000f, 0.160000f, 0.050000f },
        .ground_tex   = "textures/ground_baked2/spring_night.png",
    },
    { /* winter / day */
        .dome_zenith  = { 0.113193f, 0.235141f, 1.034472f }, .dome_mid = { 0.414835f, 0.584045f, 1.300000f },
        .dome_horizon = { 0.536462f, 0.713287f, 1.300000f }, .dome_ground = { 1.034472f, 1.253971f, 1.300000f },
        .body_color   = { 1.300000f, 1.300000f, 1.300000f }, .glow_color = { 0.536462f, 1.034472f, 1.300000f }, .disk_on = 0.0f,
        .fog_color    = { 1.300000f, 1.300000f, 1.300000f },
        .ambient      = { 0.960784f, 0.980392f, 1.000000f }, .ambient_intensity = 0.4000f,
        .key_color    = { 0.941176f, 0.972549f, 1.000000f }, .key_intensity = 2.0000f,
        .fill_color   = { 0.839216f, 0.909804f, 1.000000f }, .fill_intensity = 0.6000f,
        .lamp_intensity = 0.0000f,
        .water_shallow = { 0.050000f, 0.280000f, 0.500000f }, .water_deep = { 0.027500f, 0.154000f, 0.275000f },
        .shore_ripple = 0.0f, .ice_ratio = 1.0f,
        .grass_root   = { 0.072675f, 0.126277f, 0.147264f }, .grass_tip = { 0.173951f, 0.298889f, 0.264321f },
        .rocks_tint   = { 0.875000f, 0.925000f, 0.975000f }, .leaf_tint = { 0.860000f, 0.900000f, 0.920000f },
        .ground_tex   = "textures/ground_baked2/winter_day.png",
    },
    { /* winter / night */
        .dome_zenith  = { 0.003000f, 0.009000f, 0.036000f }, .dome_mid = { 0.006000f, 0.016500f, 0.048000f },
        .dome_horizon = { 0.009000f, 0.024000f, 0.060000f }, .dome_ground = { 0.024000f, 0.036000f, 0.075000f },
        .body_color   = { 1.000000f, 1.000000f, 1.000000f }, .glow_color = { 0.800000f, 0.900000f, 1.000000f }, .disk_on = 1.0f,
        .fog_color    = { 0.000000f, 0.002100f, 0.011700f },
        .ambient      = { 0.227451f, 0.290196f, 0.352941f }, .ambient_intensity = 0.0317f,
        .key_color    = { 0.101961f, 0.227451f, 0.352941f }, .key_intensity = 0.4752f,
        .fill_color   = { 0.164706f, 0.290196f, 0.415686f }, .fill_intensity = 0.0594f,
        .lamp_intensity = 0.4000f,
        .water_shallow = { 0.090000f, 0.120000f, 0.240000f }, .water_deep = { 0.049500f, 0.066000f, 0.132000f },
        .shore_ripple = 0.0f, .ice_ratio = 1.0f,
        .grass_root   = { 0.000000f, 0.947944f, 1.261167f }, .grass_tip = { 0.000279f, 0.309367f, 0.510143f },
        .rocks_tint   = { 0.202500f, 0.217500f, 0.232500f }, .leaf_tint = { 0.550000f, 0.620000f, 0.720000f },
        .ground_tex   = "textures/ground_baked2/winter_night.png",
    },
    { /* autumn / day */
        .dome_zenith  = { 0.235141f, 0.113193f, 0.041556f }, .dome_mid = { 0.106182f, 0.257201f, 0.281806f },
        .dome_horizon = { 0.092210f, 0.293323f, 0.371813f }, .dome_ground = { 1.300000f, 0.342698f, 0.113193f },
        .body_color   = { 1.300000f, 1.300000f, 0.101131f }, .glow_color = { 1.300000f, 0.183115f, 0.000000f }, .disk_on = 1.0f,
        .fog_color    = { 0.128108f, 0.681504f, 1.016450f },
        .ambient      = { 1.000000f, 0.949020f, 0.901961f }, .ambient_intensity = 0.5000f,
        .key_color    = { 1.000000f, 0.917647f, 0.839216f }, .key_intensity = 2.4000f,
        .fill_color   = { 1.000000f, 0.600000f, 0.400000f }, .fill_intensity = 0.8000f,
        .lamp_intensity = 0.0000f,
        .water_shallow = { 0.070000f, 0.640000f, 0.720000f }, .water_deep = { 0.038500f, 0.352000f, 0.396000f },
        .shore_ripple = 1.0f, .ice_ratio = 0.0f,
        .grass_root   = { 0.121625f, 0.065925f, 0.077149f }, .grass_tip = { 0.303767f, 0.148832f, 0.069618f },
        .rocks_tint   = { 0.925000f, 0.725000f, 0.525000f }, .leaf_tint = { 0.950000f, 0.420000f, 0.050000f },
        .ground_tex   = "textures/ground_baked2/autumn_day.png",
    },
    { /* autumn / night */
        .dome_zenith  = { 0.024000f, 0.012000f, 0.024000f }, .dome_mid = { 0.034500f, 0.018000f, 0.030000f },
        .dome_horizon = { 0.045000f, 0.024000f, 0.036000f }, .dome_ground = { 0.075000f, 0.045000f, 0.060000f },
        .body_color   = { 1.000000f, 0.500000f, 0.210000f }, .glow_color = { 0.898039f, 0.647059f, 0.364706f }, .disk_on = 1.0f,
        .fog_color    = { 0.005882f, 0.002353f, 0.003529f },
        .ambient      = { 0.301961f, 0.227451f, 0.168627f }, .ambient_intensity = 0.0264f,
        .key_color    = { 0.419608f, 0.266667f, 0.137255f }, .key_intensity = 0.0660f,
        .fill_color   = { 0.352941f, 0.239216f, 0.164706f }, .fill_intensity = 0.0484f,
        .lamp_intensity = 0.4000f,
        .water_shallow = { 0.108000f, 0.498000f, 0.516000f }, .water_deep = { 0.059400f, 0.273900f, 0.283800f },
        .shore_ripple = 0.5f, .ice_ratio = 0.0f,
        .grass_root   = { 0.296319f, 0.061942f, 0.000000f }, .grass_tip = { 1.061718f, 0.851860f, 0.000000f },
        .rocks_tint   = { 0.202500f, 0.157500f, 0.112500f }, .leaf_tint = { 0.450000f, 0.200000f, 0.030000f },
        .ground_tex   = "textures/ground_baked2/autumn_night.png",
    },
    { /* rainy / day */
        .dome_zenith  = { 0.056732f, 0.073523f, 0.113193f }, .dome_mid = { 0.104333f, 0.149051f, 0.213308f },
        .dome_horizon = { 0.113193f, 0.164471f, 0.235141f }, .dome_ground = { 0.164471f, 0.235141f, 0.342698f },
        .body_color   = { 1.300000f, 1.300000f, 1.300000f }, .glow_color = { 0.235141f, 0.235141f, 0.342698f }, .disk_on = 0.0f,
        .fog_color    = { 0.173870f, 0.284605f, 0.426117f },
        .ambient      = { 0.141176f, 0.235294f, 0.360784f }, .ambient_intensity = 1.5000f,
        .key_color    = { 0.141176f, 0.388235f, 0.541176f }, .key_intensity = 0.1500f,
        .fill_color   = { 0.701961f, 0.850980f, 1.000000f }, .fill_intensity = 0.1000f,
        .lamp_intensity = 0.0000f,
        .water_shallow = { 0.058000f, 0.390000f, 0.500000f }, .water_deep = { 0.031900f, 0.214500f, 0.275000f },
        .shore_ripple = 1.0f, .ice_ratio = 0.0f,
        .grass_root   = { 0.112971f, 0.071916f, 0.037449f }, .grass_tip = { 0.108843f, 0.104989f, 0.044762f },
        .rocks_tint   = { 0.575000f, 0.525000f, 0.475000f }, .leaf_tint = { 0.050000f, 0.200000f, 0.060000f },
        .ground_tex   = "textures/ground_baked2/rainy_day.png",
    },
    { /* rainy / night */
        .dome_zenith  = { 0.009000f, 0.015000f, 0.024000f }, .dome_mid = { 0.013500f, 0.022500f, 0.034500f },
        .dome_horizon = { 0.018000f, 0.030000f, 0.045000f }, .dome_ground = { 0.030000f, 0.045000f, 0.060000f },
        .body_color   = { 0.600000f, 0.700000f, 0.800000f }, .glow_color = { 0.500000f, 0.600000f, 0.800000f }, .disk_on = 1.0f,
        .fog_color    = { 0.001176f, 0.003529f, 0.005882f },
        .ambient      = { 0.164706f, 0.227451f, 0.290196f }, .ambient_intensity = 0.0330f,
        .key_color    = { 0.058824f, 0.121569f, 0.247059f }, .key_intensity = 0.2420f,
        .fill_color   = { 0.101961f, 0.164706f, 0.290196f }, .fill_intensity = 0.0550f,
        .lamp_intensity = 0.4000f,
        .water_shallow = { 0.048000f, 0.120000f, 0.180000f }, .water_deep = { 0.026400f, 0.066000f, 0.099000f },
        .shore_ripple = 0.5f, .ice_ratio = 0.0f,
        .grass_root   = { 0.000000f, 0.423265f, 0.000000f }, .grass_tip = { 0.028740f, 0.417407f, 0.194391f },
        .rocks_tint   = { 0.112500f, 0.106500f, 0.097500f }, .leaf_tint = { 0.030000f, 0.100000f, 0.040000f },
        .ground_tex   = "textures/ground_baked2/rainy_night.png",
    },
};

#define ES_PRESET(season, tod) (&ES_PRESETS[(season) * 2 + (tod)])

#endif /* ES_PALETTES_H */
