/*
 * es_script_langs.c — turn on the language backends this project's scene
 * uses, before anything in the scene is instantiated.
 *
 * ══ THE ANSWER TO "WHAT MUST A PROJECT DO TO GET PYTHON / JAVA / C++" ══
 *
 * Nothing in the engine does this for you and nothing can.  The engine
 * registers exactly ONE language for itself — the built-in Lua VM, lazily, on
 * first use (jce_script_vm.h, JCE_SCRIPT_VM_DEFAULT_LANGUAGE).  Every other
 * backend registers itself, from a function the APPLICATION calls, and if the
 * application never calls it the backend is not merely off: the extension is
 * unclaimed, jce_script_vm_language_for_path() returns NULL, and every entity
 * carrying such a script is REFUSED — loudly, but at runtime, with the scene
 * otherwise working perfectly.
 *
 * So the whole contract is four bullets, and each one of them is a thing that
 * fails on its own:
 *
 *   1. BUILD the backend.  JCE_BUILD_SCRIPT_JAVA defaults OFF; Python's target
 *      exists only where CMake found an embeddable CPython; the cpp backend
 *      needs no toolchain but does need its module compiled into something.
 *      See CMakeLists.txt in this directory's parent.
 *   2. LINK it, and link jce_script_api beside it — the shared library the
 *      Python and Java bindings CALL.  A missing DLL is a loader failure
 *      before main() and prints nothing.
 *   3. CALL its register().  That is this file.
 *   4. TELL IT WHERE ITS RUNTIME LIVES.  CPython needs the `jce_script`
 *      package on sys.path; the JVM needs an absolute jvm.dll, a class path,
 *      and the absolute path of the JNI shim.  None of the four is
 *      discoverable by the backend itself.
 *
 * ORDER MATTERS AND IT IS NOT ARBITRARY.  This function must run before
 * app_init() loads the startup scene, because the scene's Script components
 * are instantiated inside jce_runtime_create() and a language registered
 * afterwards is a language the scene has already been refused by.  es_app_init
 * in main.c calls it as its first statement, before app_init().
 *
 * NOTHING HERE FAILS THE PROCESS.  Every refusal is reported by name on
 * stderr and the run continues, so the failure surfaces as "python: 0 starts"
 * in the probe report rather than as a window that never opened.  A refusal
 * that killed the process would tell you less.
 */

#include "es_script_langs.h"

#include <jce/api.h>
#include <stdlib.h>

static JceLibrary s_runtime_preload;

/* Deployment may supply a dependency of its external language runtime. */
static void es_preload_runtime(void)
{
    const char *path = getenv("ES_RUNTIME_PRELOAD");
    if (!s_runtime_preload && path && path[0]) {
        s_runtime_preload = jce_library_open(path);
        if (!s_runtime_preload)
            LOG_WARN("es_script", "external runtime dependency failed: %s", path);
    }
}

void es_script_langs_shutdown(void)
{
    jce_library_close(s_runtime_preload);
    s_runtime_preload = NULL;
}
#include <jce/script_vm/jce_script_vm_cpp.h>
#include <jce/script_vm/jce_script_vm_c.h>

/* ══ SUPERSEDED FOR THE SHIPPING BUILD ══════════════════════════════
 *
 * Everything below this guard is the hand-written version of the four steps,
 * and it is kept only for the in-tree branch that still configures that way.
 * The four steps are now engine-side: jce_script_enable() in the SDK links
 * the backends, bakes the runtime inputs and generates the registration shim,
 * and this file just calls it.
 *
 * WHY THIS MATTERS AND NOT JUST TIDINESS.  The hand-written version was
 * written into the IN-TREE CMake branch and not the SDK-consumer one this
 * project ships from, so the shipped executable ran Lua and nothing else
 * while the editor ran four languages -- with no build error anywhere.  A
 * per-project copy of a four-step contract is a copy that can be complete in
 * one branch and absent in another. */
#if defined(ES_SCRIPT_ENABLE_SHIM)
#  include <jce_script_register_linked.h>
#  if defined(JCE_SCRIPT_LINKED_CPP)
extern bool es_flower_sway_register(void);
#  endif
#  if defined(JCE_SCRIPT_LINKED_C)
extern bool es_prop_surface_register(void);
#  endif

/* The one thing that stays project code: the classes are this project's. */
static void es_publish_native_modules(void)
{
#  if defined(JCE_SCRIPT_LINKED_CPP)
    (void)es_flower_sway_register();
#  endif
#  if defined(JCE_SCRIPT_LINKED_C)
    (void)es_prop_surface_register();
#  endif
}

void es_script_langs_register(void)
{
    es_preload_runtime();
    (void)jce_script_register_linked_languages(es_publish_native_modules);
}
#else

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(ES_HAVE_SCRIPT_PYTHON)
#  include "jce_script_vm_python.h"
#endif
#if defined(ES_HAVE_SCRIPT_JAVA)
#  include <jce/script_vm/jce_script_vm_java.h>
/* Generated by this project's CMakeLists: the absolute jvm library derived
 * from the JDK the backend's jni.h came from, the class path holding
 * com.jce.script.*, and the absolute path of the JNI shim. */
#  include "es_script_java_paths.gen.h"
#endif
#if defined(ES_HAVE_SCRIPT_CPP)
#  include <jce/script_vm/jce_script_vm_cpp.h>
/* Defined in es_flower_sway.cpp: publishes the C++ module. */
extern bool es_flower_sway_register(void);
#endif
#if defined(ES_HAVE_SCRIPT_C)
#  include <jce/script_vm/jce_script_vm_c.h>
/* Defined in es_prop_surface.c: publishes the C module. */
extern bool es_prop_surface_register(void);
#endif

#if defined(_WIN32)
#  define ES_SCRIPT_API_LIB "jce_script_api.dll"
#  define es_setenv(k, v) _putenv_s((k), (v))
#elif defined(__APPLE__)
#  define ES_SCRIPT_API_LIB "libjce_script_api.dylib"
#  define es_setenv(k, v) setenv((k), (v), 1)
#else
#  define ES_SCRIPT_API_LIB "libjce_script_api.so"
#  define es_setenv(k, v) setenv((k), (v), 1)
#endif

void es_script_langs_register(void)
{
    es_preload_runtime();
#if defined(ES_HAVE_SCRIPT_PYTHON) || defined(ES_HAVE_SCRIPT_JAVA)
    char base[1024];
    char api_lib[1024 + sizeof ES_SCRIPT_API_LIB];
    api_lib[0] = '\0';
    if (jce_fs_host_get_base_path(base, (uint32_t)sizeof base) && base[0])
        snprintf(api_lib, sizeof api_lib, "%s%s", base, ES_SCRIPT_API_LIB);
#endif

#if defined(ES_HAVE_SCRIPT_PYTHON)
    /* CPython writes __pycache__ next to whatever it imports, and the
     * `jce_script` package is imported FROM THE REPOSITORY here.  Stale .pyc
     * is invalidated on (mtime, size), so a same-size edit inside one mtime
     * second leaves the OLD bytecode running — a real failure this worktree
     * has already had.  Set before Py_InitializeFromConfig, which has not run
     * yet: the interpreter does not exist until the first create. */
    es_setenv("PYTHONDONTWRITEBYTECODE", "1");
    if (api_lib[0])
        es_setenv("JCE_SCRIPT_API", api_lib);

    /* The one path CPython cannot discover: the directory holding the
     * `jce_script` package.  Without it `import jce_script.vm` fails and
     * instantiate returns 0 — the script is silently absent, not degraded. */
    if (!jce_script_vm_python_add_path(ES_SCRIPT_PYTHON_PACKAGE_DIR))
        fprintf(stderr,
                "ES scripting: sys.path refused '%s' — every .py in this "
                "scene will fail to instantiate\n",
                ES_SCRIPT_PYTHON_PACKAGE_DIR);
    if (!jce_script_vm_python_register())
        fprintf(stderr, "ES scripting: python register REFUSED — .py will "
                        "resolve to no language\n");
#endif

#if defined(ES_HAVE_SCRIPT_JAVA)
    {
        JceScriptVmJavaConfig cfg;
        static char           lib_opt[1024];
        const char           *opts[1];

        /* -Djce.script.library must be ABSOLUTE.  com.jce.script.JceScript's
         * static initialiser otherwise falls back to System.loadLibrary()
         * against a java.library.path this process never arranged, and the
         * shim is built beside jce_script_api rather than beside the exe. */
        snprintf(lib_opt, sizeof lib_opt, "-Djce.script.library=%s",
                 ES_SCRIPT_JAVA_SCRIPT_LIB);
        opts[0] = lib_opt;

        memset(&cfg, 0, sizeof cfg);
        /* An ABSOLUTE jvm library, because jce_library_open() attaches to an
         * already-resident module of the same bare name on Windows — "jvm.dll"
         * would bind to whichever JVM something else loaded first, with
         * somebody else's options.  configure() refuses a bare name for
         * exactly that reason. */
        cfg.jvm_library  = ES_SCRIPT_JAVA_JVM_LIBRARY;
        cfg.class_path   = ES_SCRIPT_JAVA_CLASS_PATH;
        cfg.options      = opts;
        cfg.option_count = 1;

        if (!jce_script_vm_java_configure(&cfg, sizeof cfg))
            fprintf(stderr,
                    "ES scripting: java configure REFUSED (jvm=%s, "
                    "classpath=%s) — jce_script_vm_create(\"java\") will "
                    "fail\n",
                    ES_SCRIPT_JAVA_JVM_LIBRARY, ES_SCRIPT_JAVA_CLASS_PATH);
        if (!jce_script_vm_java_register())
            fprintf(stderr, "ES scripting: java register REFUSED — .java "
                            "will resolve to no language\n");
    }
#endif

#if defined(ES_HAVE_SCRIPT_CPP)
    /* Order: register the LANGUAGE first, then the module and the extension
     * claim.  jce_script_vm_register_extension() refuses a claim for a
     * language that is not registered yet — deliberately, so that "backend
     * not linked" never turns into "extension resolves to a VM that does not
     * exist". */
    if (!jce_script_vm_cpp_register())
        fprintf(stderr, "ES scripting: cpp register REFUSED\n");
    else
        (void)es_flower_sway_register();
#endif

#if defined(ES_HAVE_SCRIPT_C)
    /* "c" IS A SEPARATE CALL AND A SEPARATE LANGUAGE.  It is not registered
     * by jce_script_vm_cpp_register() and it does not register that one:
     * a host that wants both calls both.  What the two SHARE is the native
     * class registry — one registry, because a compiled class has no language
     * at run time (it is a table of C function pointers) — which is why the
     * module below is published through jce_script_vm_cpp_add_module() even
     * though it is C.  jce_script_vm_c.h states the whole arrangement.
     *
     * TWO MODULES, NOT ONE WITH TWO CLASSES: one module descriptor is one
     * translation unit, and a translation unit is C or C++. */
    if (!jce_script_vm_c_register())
        fprintf(stderr, "ES scripting: c register REFUSED — .jcec will "
                        "resolve to no language\n");
    else
        (void)es_prop_surface_register();
#endif

    /* One line saying what this executable can actually run.  It is the
     * cheapest possible answer to "is the backend in this build at all",
     * which is the question every other symptom in this area reduces to. */
    {
        int i;
        int n = jce_script_vm_count();
        fprintf(stderr, "ES scripting: %d language(s) registered:", n);
        for (i = 0; i < n; ++i)
            fprintf(stderr, " %s", jce_script_vm_language_at(i));
        fprintf(stderr, "\nES scripting: extension claims:");
        n = jce_script_vm_extension_count();
        for (i = 0; i < n; ++i)
            fprintf(stderr, " .%s=%s", jce_script_vm_extension_at(i),
                    jce_script_vm_extension_language_at(i));
        fprintf(stderr, "\n");
    }
}
#endif /* ES_SCRIPT_ENABLE_SHIM */
