/*
 * elemental_serenity — application entry point.
 *
 * Stylized nature-diorama replica of Elemental-Serenity. The stock app body
 * lives in <jce/application/jce_default_main.inc.h> (loads the project's
 * startup scene from jce_project.json "startup_scene" and runs
 * jce_runtime_step every frame, matching editor Play).
 *
 * ALL content logic (seasons x day/night tween, weather, lightning, wind,
 * audio, reveal, HUD) lives in the scene-bound Lua director
 * (resources/assets/scripts/es_director.lua) so editor Play and this exe
 * simulate identically. The app keeps only the ES_AUTOSHOOT verification
 * harness, which walks the 8 season/tod states through the director's global
 * handlers and saves labelled shots.
 * Window/UX chrome (ALT cursor, ESC-2s quit, F11 fullscreen, F12 shot,
 * F9 recording) comes from the default_main runtime presets.
 */

#include "_embedded_bundles.h"           /* generated by CMake */
#include <jce/api.h>
#include <jce/application/jce_default_main.inc.h>

#include <jce/api_platform.h>

#include "es_scene_orchestrator.h"
#include "es_aid_mood.h"
#include "es_camera.h"   /* left-drag orbit + wheel zoom → BeautyCam vcam */
#include "es_perf.h"     /* [P] perf panel — win-x64 vs wasm comparison */
#include "es_script_langs.h"  /* register python/java/cpp BEFORE app_init */
#include "es_script_probe.h"  /* counted proof each language's script ran */

#include <stdlib.h>   /* getenv: pre-boot env snapshot (see below) */
#include <stdio.h>    /* snprintf — explicit for strict wasm clang */

#define ES_WINDOW_W 1280
#define ES_WINDOW_H 720

/* ── ES_AUTOSHOOT: autonomous visual-verification walk ──────────────────
 * Steps the 8 season/tod states via the Lua director's global setters
 * (the same functions the HUD buttons call), captures one labelled
 * screenshot per state beside the exe, then quits. */
static bool  s_shoot_enabled = false;
static int   s_shoot_idx     = -1;
static float s_shoot_t       = 0.0f;
static bool  s_shot_taken    = false;
static EsSceneOrchestrator *s_ai_orchestrator = NULL;
static EsAidMood           *s_aid_mood        = NULL;
static bool  s_aid_throttle_off = false;  /* ES_AID_NO_THROTTLE=1 to disable */
static uint32_t s_aid_throttle_ms = 66;   /* ES_AID_THROTTLE_MS override (per-frame sleep during gen) */

static const char *ES_SHOOT_PLAN[8] = {
    "spring_night", "spring_day", "winter_night", "winter_day",
    "autumn_night", "autumn_day", "rainy_night",  "rainy_day",
};

static void es_autoshoot_update(float dt)
{
    if (!s_shoot_enabled || !s_runtime) return;
    s_shoot_t += dt;

    if (s_shoot_idx < 0) {           /* settle the boot state first */
        if (s_shoot_t < 6.5f) return;   /* wait out the reveal dissolve */
        s_shoot_idx = 0;
        s_shoot_t   = 0.0f;
        s_shot_taken = false;
        char fn[128];
        snprintf(fn, sizeof fn, "es_state_%s", ES_SHOOT_PLAN[0]);
        jce_runtime_dispatch_ui_click(s_runtime, 0, fn);
        return;
    }

    /* 3s per state: tween finishes ~1s, shoot at 2.7s, advance at 3s. */
    if (!s_shot_taken && s_shoot_t >= 2.7f) {
        char path[256];
        snprintf(path, sizeof path, "shot_%s.png", ES_SHOOT_PLAN[s_shoot_idx]);
        jce_screenshot_save(path, JCE_SCREENSHOT_PNG);
        s_shot_taken = true;
    }
    if (s_shoot_t >= 3.0f) {
        s_shoot_idx++;
        if (s_shoot_idx >= 8) { jce_engine_request_quit(); return; }
        s_shoot_t    = 0.0f;
        s_shot_taken = false;
        char fn[128];
        snprintf(fn, sizeof fn, "es_state_%s", ES_SHOOT_PLAN[s_shoot_idx]);
        jce_runtime_dispatch_ui_click(s_runtime, 0, fn);
    }
}

static bool es_app_init(const JceServices *svc, void *ud)
{
    /* FIRST STATEMENT, AND THE ORDER IS LOAD-BEARING.  app_init() loads the
     * startup scene and calls jce_runtime_create(), and the scene's Script
     * components are instantiated inside that call — so a language registered
     * after this line is a language every entity has already been refused by,
     * with "no script VM claims its extension" in the log and nothing on
     * screen to say which entity lost.  The engine registers only Lua, and it
     * registers that lazily; every other backend is the application's job. */
    es_script_langs_register();

    if (!app_init(svc, ud))
        return false;
    /* The probe entities are SCENE entities, so they can only be resolved
     * after the scene exists.  Reported by name here when one is missing —
     * "the probe is not in the scene" and "the script never ran" produce the
     * same zero, and they have different fixes. */
    es_script_probe_init(s_scene);
    /* App-wide UI font: LXGW WenKai (霞鹜文楷) for both the HUD and any UIText
     * that leaves its font_path empty (perf panel, mood buttons).  App-scoped —
     * the editor and other apps keep the built-in default. */
    jce_ui_canvas_set_default_font("fonts/LXGWWenKai-Regular.ttf");
    s_ai_orchestrator = es_scene_orchestrator_create(s_runtime,
                                                     s_runtime_fs);
    if (!s_ai_orchestrator) {
        app_exit(ud);
        return false;
    }
    if (!es_scene_orchestrator_request_next(s_ai_orchestrator)) {
        es_scene_orchestrator_destroy(s_ai_orchestrator);
        s_ai_orchestrator = NULL;
        app_exit(ud);
        return false;
    }
    /* ai_dispatch grass-mood experience: NULL when the SDK has no private
     * module -- that is "feature absent", never a startup failure. */
    s_aid_mood = es_aid_mood_create(s_runtime, s_scene);
    /* Orbit camera (left-drag rotate, wheel zoom — reference OrbitControls) now
     * lives in the scene's Lua director (update_camera), NOT here: the director
     * runs in editor Play AND the shipped runtime, so both drive the BeautyCam
     * identically.  default_main feeds raw pointer input into the runtime's
     * Script VM (see the "Diorama/orbit projects" block), so the Lua path has
     * everything es_camera.c used to read from svc->input. */
    /* [P] perf panel: FPS / frame / cpu-gpu / draws / memory with the active
     * backend in the title — identical readout on win-x64 and wasm so the two
     * platforms can be compared from screenshots alone. */
    es_perf_init(s_scene);
    return true;
}

static void es_app_update(float dt, void *ud)
{
    app_update(dt, ud);                  /* runtime step = Lua director  */
    if (s_ai_orchestrator && s_svc && s_svc->input &&
        jce_input_key_pressed(s_svc->input, JCE_KEY_N))
        es_scene_orchestrator_request_next(s_ai_orchestrator);
    es_scene_orchestrator_update(s_ai_orchestrator, dt);
    es_aid_mood_update(s_aid_mood, dt,
                       (s_svc && s_svc->input) ? s_svc->input : NULL);
    /* on-screen AI panel: "Generate New Scene" + 8 place-type buttons +
     * progress/status.  Builds itself on first call; polls the canvas
     * default_main owns (s_ui_canvas).  No-op in a stub (no SDK module). */
    es_aid_mood_ui(s_aid_mood, s_ui_canvas, dt);
    /* Orbit camera now lives in the Lua director (update_camera) so editor Play
     * and this runtime drive the BeautyCam identically — do NOT also run the
     * app-side es_camera here or the two would fight over the same vcam. */
    es_perf_update(s_scene, dt,
                   (s_svc && s_svc->input) ? s_svc->input : NULL);
    es_script_probe_update(s_scene, dt);
    es_autoshoot_update(dt);

    /* While an AI request is in flight, cap the render loop to ~30 FPS.  The
     * gateway/LLM call runs on a worker thread, so an uncapped diorama (hundreds
     * of FPS) would hog the GPU the local inference server shares, dropping it
     * from ~50 to ~10-20 tok/s and pushing a generation past 10 s.  Yielding the
     * GPU for the ~6 s wait keeps inference near full speed; normal frames are
     * untouched.  Disable with ES_AID_NO_THROTTLE=1. */
    if (!s_aid_throttle_off && s_aid_throttle_ms &&
        es_aid_mood_is_generating(s_aid_mood))
        jce_thread_sleep_ms(s_aid_throttle_ms);
}

/* Draw = stock scene/postfx/UI, then the AI placement debug overlay on top
 * (no-op unless ES_AID_DEBUG_VIZ=1).  s_camera/s_svc come from default_main. */
static void es_app_draw(const JceServices *svc, void *ud)
{
    app_draw(svc, ud);
    if (s_aid_mood && svc && svc->renderer && svc->window)
        es_aid_mood_debug_draw(s_aid_mood, svc->renderer, svc->window,
                               s_camera);
}

static void es_app_exit(void *ud)
{
    /* The last word, and the only one that is a COUNT.  Printed before
     * anything is torn down so a language that stopped being updated halfway
     * through the run is still distinguishable from one that never started. */
    es_script_probe_report("exit");
    es_aid_mood_destroy(s_aid_mood);
    s_aid_mood = NULL;
    es_scene_orchestrator_destroy(s_ai_orchestrator);
    s_ai_orchestrator = NULL;
    app_exit(ud);
    es_script_langs_shutdown();
}

static JceAppDesc elemental_serenity_get_desc(void)
{
    /* Snapshot env flags BEFORE any engine/scene work: a getenv issued
     * after scene+runtime init intermittently AVs inside the CRT env
     * access (heap corruption from a third-party region — PageHeap hunt
     * pending; see project notes). */
    {
        const char *as = getenv("ES_AUTOSHOOT");
        s_shoot_enabled = (as && as[0] == '1');
        const char *nt = getenv("ES_AID_NO_THROTTLE");
        s_aid_throttle_off = (nt && nt[0] == '1');
        const char *tm = getenv("ES_AID_THROTTLE_MS");
        if (tm && tm[0]) {
            int v = atoi(tm);
            if (v >= 0 && v <= 500) s_aid_throttle_ms = (uint32_t)v;
        }
    }

    JceAppDesc d = (JceAppDesc){0};
    d.name          = "Elemental Serenity";
    d.init          = es_app_init;
    d.update        = es_app_update;
    d.draw          = es_app_draw;
    d.exit          = es_app_exit;
    d.window_width  = ES_WINDOW_W;
    d.window_height = ES_WINDOW_H;
    return d;
}

JCE_MAIN(elemental_serenity_get_desc)
