/*
 * jce_pak_key.cpp  Project asset-encryption key management.
 *
 * See jce_pak_key.h for the contract.  All file I/O goes through the
 * engine host-FS layer so behaviour matches the rest of the editor.
 */

#include "jce_pak_key.h"

#include <cstdio>
#include <cstring>

extern "C" {
#include <jce/os/core/jce_filesystem.h>
#include <jce/os/core/jce_log.h>
#include <jce/os/platform/jce_entropy.h>
#include <jce/resource/jce_archive.h>
}

#define LOG_TAG "pak_key"

namespace {

/* ── Paths ────────────────────────────────────────────────────────── */

std::string dotjce_dir(const std::string &project_root)
{
    return project_root + "/.jce";
}

/* ── CSPRNG ───────────────────────────────────────────────────────── */

/* Fill `out` with `n` random bytes via the OS-platform entropy shim.
 * Returns false when only the shim's dev-only fallback (time + pointer
 * mix — NOT cryptographically secure) was available; the bytes are still
 * filled so callers can proceed with a warning. */
bool csprng_fill(uint8_t *out, size_t n)
{
    return jce_host_random_bytes(out, n);
}

/* ── Hex codec ────────────────────────────────────────────────────── */

int hex_nibble(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

/* Parse exactly 64 hex chars (whitespace tolerated anywhere) into 32 bytes. */
bool parse_hex_key(const char *text, size_t len, uint8_t out_key[32])
{
    int nibbles = 0;
    for (size_t i = 0; i < len; ++i) {
        char c = text[i];
        if (c == ' ' || c == '\t' || c == '\r' || c == '\n') continue;
        int v = hex_nibble(c);
        if (v < 0) return false;
        if (nibbles >= 64) return false; /* too long */
        if ((nibbles & 1) == 0) out_key[nibbles / 2] = (uint8_t)(v << 4);
        else                    out_key[nibbles / 2] |= (uint8_t)v;
        nibbles++;
    }
    return nibbles == 64;
}

void key_to_hex(const uint8_t key[32], char out_hex[65])
{
    static const char d[] = "0123456789abcdef";
    for (int i = 0; i < 32; ++i) {
        out_hex[i * 2 + 0] = d[key[i] >> 4];
        out_hex[i * 2 + 1] = d[key[i] & 0xF];
    }
    out_hex[64] = '\0';
}

/* ── .jce/.gitignore seeding ──────────────────────────────────────────
 * Keep the key out of version control without hiding the rest of .jce
 * (project-settings.json intentionally travels with the project).
 * Precedent: the bundle packer seeds .bundles/.gitignore. */
void seed_gitignore(const std::string &project_root)
{
    const std::string gi = dotjce_dir(project_root) + "/.gitignore";
    static const char kEntry[] = "pak_key.hex";

    uint64_t sz = 0;
    char *raw = (char *)jce_fs_host_read_all(gi.c_str(), &sz);
    if (raw) {
        std::string text(raw, raw + sz);
        jce_fs_buffer_free(raw);
        if (text.find(kEntry) != std::string::npos)
            return; /* already covered */
        if (!text.empty() && text.back() != '\n')
            text += "\n";
        text += "# Asset encryption key — never commit (regenerating breaks "
                "previously encrypted archives).\n";
        text += kEntry;
        text += "\n";
        jce_fs_host_write_all(gi.c_str(), text.data(), (uint64_t)text.size());
        return;
    }

    static const char kBody[] =
        "# Auto-generated by the JCE editor.\n"
        "# Asset encryption key — never commit (regenerating breaks "
        "previously encrypted archives).\n"
        "pak_key.hex\n";
    jce_fs_host_write_all(gi.c_str(), kBody, (uint64_t)(sizeof(kBody) - 1));
}

bool write_key_file(const std::string &project_root, const uint8_t key[32],
                    std::string *err)
{
    const std::string dir = dotjce_dir(project_root);
    if (!jce_fs_host_create_directory(dir.c_str())) {
        if (err) *err = "cannot create " + dir;
        return false;
    }

    char hex[65];
    key_to_hex(key, hex);
    char line[68];
    std::snprintf(line, sizeof(line), "%s\n", hex);

    const std::string path = jce_pak_key_path(project_root);
    if (!jce_fs_host_write_all(path.c_str(), line, (uint64_t)std::strlen(line))) {
        if (err) *err = "cannot write " + path;
        return false;
    }
    seed_gitignore(project_root);
    return true;
}

} // namespace

/* ── Public API ───────────────────────────────────────────────────── */

std::string jce_pak_key_path(const std::string &project_root)
{
    return dotjce_dir(project_root) + "/pak_key.hex";
}

bool jce_pak_key_load(const std::string &project_root, uint8_t out_key[32])
{
    if (project_root.empty()) return false;
    const std::string path = jce_pak_key_path(project_root);
    uint64_t sz = 0;
    char *raw = (char *)jce_fs_host_read_all(path.c_str(), &sz);
    if (!raw) return false;
    bool ok = parse_hex_key(raw, (size_t)sz, out_key);
    jce_fs_buffer_free(raw);
    if (!ok)
        LOG_WARN(LOG_TAG, "malformed key file (expected 64 hex chars): %s",
                 path.c_str());
    return ok;
}

bool jce_pak_key_exists(const std::string &project_root)
{
    uint8_t key[32];
    return jce_pak_key_load(project_root, key);
}

bool jce_pak_key_generate(const std::string &project_root, bool overwrite,
                          std::string *err)
{
    if (project_root.empty()) {
        if (err) *err = "no project open";
        return false;
    }
    if (!overwrite && jce_pak_key_exists(project_root)) {
        if (err) *err = "key already exists (regenerate requires confirmation)";
        return false;
    }

    uint8_t key[32];
    if (!csprng_fill(key, sizeof(key))) {
        std::memset(key, 0, sizeof(key));
        if (err) *err = "OS CSPRNG unavailable; refusing to create an "
                        "asset key";
        LOG_ERROR(LOG_TAG, "%s", err ? err->c_str() :
                  "OS CSPRNG unavailable");
        return false;
    }
    bool ok = write_key_file(project_root, key, err);
    if (ok)
        LOG_INFO(LOG_TAG, "asset encryption key %s: %s",
                 overwrite ? "regenerated" : "generated",
                 jce_pak_key_path(project_root).c_str());
    std::memset(key, 0, sizeof(key));
    return ok;
}

bool jce_pak_key_import(const std::string &project_root,
                        const std::string &src_file, std::string *err)
{
    if (project_root.empty()) {
        if (err) *err = "no project open";
        return false;
    }
    uint64_t sz = 0;
    char *raw = (char *)jce_fs_host_read_all(src_file.c_str(), &sz);
    if (!raw) {
        if (err) *err = "cannot read " + src_file;
        return false;
    }
    uint8_t key[32];
    bool ok = parse_hex_key(raw, (size_t)sz, key);
    jce_fs_buffer_free(raw);
    if (!ok) {
        if (err) *err = "not a valid key file (expected 64 hex chars)";
        return false;
    }
    ok = write_key_file(project_root, key, err);
    std::memset(key, 0, sizeof(key));
    return ok;
}

uint64_t jce_pak_key_fingerprint(const uint8_t key[32])
{
    /* jce_archive_hash_normalized is a thin public XXH3-64 wrapper — reuse
     * it instead of adding a direct xxhash link dependency to the editor. */
    return jce_archive_hash_normalized((const char *)key, 32);
}

bool jce_pak_key_fingerprint_of(const std::string &project_root,
                                uint64_t *out_fp)
{
    uint8_t key[32];
    if (!jce_pak_key_load(project_root, key)) return false;
    if (out_fp) *out_fp = jce_pak_key_fingerprint(key);
    std::memset(key, 0, sizeof(key));
    return true;
}

void jce_pak_key_install_process(const std::string &project_root)
{
    uint8_t key[32];
    if (!project_root.empty() && jce_pak_key_load(project_root, key)) {
        const uint64_t fp = jce_pak_key_fingerprint(key);
        jce_archive_set_process_key(key);
        std::memset(key, 0, sizeof(key));
        LOG_INFO(LOG_TAG, "project asset key installed (fp %08x)",
                 (unsigned)(fp >> 32));
    } else {
        jce_archive_set_process_key(nullptr);
    }
}

bool jce_pak_key_write_shares_c(const std::string &project_root,
                                const std::string &out_c_path,
                                std::string *err)
{
    uint8_t key[32];
    if (!jce_pak_key_load(project_root, key)) {
        if (err) *err = "asset encryption key missing: " +
                        jce_pak_key_path(project_root);
        return false;
    }

    uint8_t share_a[32];
    if (!csprng_fill(share_a, sizeof(share_a))) {
        std::memset(key, 0, sizeof(key));
        std::memset(share_a, 0, sizeof(share_a));
        if (err) *err = "OS CSPRNG unavailable; refusing to emit weak key "
                        "shares";
        return false;
    }

    uint8_t shares[64];
    for (int i = 0; i < 32; ++i) {
        shares[i]      = share_a[i];
        shares[32 + i] = (uint8_t)(key[i] ^ share_a[i]);
    }
    std::memset(key, 0, sizeof(key));
    std::memset(share_a, 0, sizeof(share_a));

    std::string src;
    src.reserve(1024);
    src += "/* Auto-generated by the JCE editor — DO NOT EDIT, DO NOT COMMIT.\n"
           " * Two XOR shares of the project asset key (share_a ^ share_b =\n"
           " * key) so the raw key never appears as a contiguous 32-byte\n"
           " * constant in the binary.  Regenerated with a fresh mask every\n"
           " * build (NOTE: this is what makes encrypted executables non-bit-\n"
           " * reproducible).  The authenticated archive still cannot make\n"
           " * client-delivered data secret from a determined attacker. */\n"
           "const unsigned char jce_embedded_pak_key_shares[64] = {\n";
    char buf[16];
    for (int i = 0; i < 64; ++i) {
        std::snprintf(buf, sizeof(buf), "%s0x%02X%s",
                      (i % 8 == 0) ? "    " : "",
                      shares[i],
                      (i == 63) ? "\n" : ((i % 8 == 7) ? ",\n" : ", "));
        src += buf;
    }
    src += "};\n"
           "const int jce_embedded_pak_key_present = 1;\n";
    std::memset(shares, 0, sizeof(shares));

    if (!jce_fs_host_write_all(out_c_path.c_str(), src.data(),
                               (uint64_t)src.size())) {
        if (err) *err = "cannot write " + out_c_path;
        return false;
    }
    return true;
}
