#include "jce_binary_embed.h"

extern "C" {
#include <jce/os/core/jce_filesystem.h>
}

#include <cstdio>
#include <vector>

bool jce_binary_embed_write_c_source(const std::string &path,
                                     const std::string &symbol,
                                     const uint8_t *data, size_t size)
{
    std::string head;
    if (size != 0 && !data)
        return false;
    if (size == 0) {
        head = "#include <stddef.h>\n"
               "const unsigned char " + symbol + "[1] = {0};\n"
               "const size_t " + symbol + "_size = 0;\n";
        return jce_fs_host_write_all(path.c_str(), head.data(),
                                     (uint64_t)head.size());
    }

    head = "/* Auto-generated by JCE Editor -- DO NOT EDIT */\n"
           "#include <stddef.h>\n"
           "const unsigned char " + symbol + "[] = {\n";
    if (!jce_fs_host_write_all(path.c_str(), head.data(),
                               (uint64_t)head.size()))
        return false;

    std::string chunk;
    chunk.reserve(65536);
    for (size_t i = 0; i < size; ++i) {
        char cell[8];
        if (i % 12 == 0)
            chunk += "    ";
        std::snprintf(cell, sizeof(cell), "0x%02x", (unsigned)data[i]);
        chunk += cell;
        chunk += (i + 1 == size) ? "\n" : ", ";
        if (i % 12 == 11)
            chunk += "\n";
        if (chunk.size() > 60000) {
            if (!jce_fs_host_append(path.c_str(), chunk.data(),
                                    (uint64_t)chunk.size()))
                return false;
            chunk.clear();
        }
    }
    chunk += "};\nconst size_t " + symbol + "_size = ";
    chunk += std::to_string(size);
    chunk += ";\n";
    return jce_fs_host_append(path.c_str(), chunk.data(),
                              (uint64_t)chunk.size());
}

static void byte_push(std::vector<uint8_t> &out, uint8_t value)
{
    out.push_back(value);
}

static void byte_append(std::vector<uint8_t> &out, const void *data,
                        size_t size)
{
    if (!data || size == 0)
        return;
    const uint8_t *bytes = static_cast<const uint8_t *>(data);
    out.insert(out.end(), bytes, bytes + size);
}

static void byte_le16(std::vector<uint8_t> &out, uint16_t value)
{
    byte_push(out, (uint8_t)value);
    byte_push(out, (uint8_t)(value >> 8));
}

static void byte_le32(std::vector<uint8_t> &out, uint32_t value)
{
    byte_push(out, (uint8_t)value);
    byte_push(out, (uint8_t)(value >> 8));
    byte_push(out, (uint8_t)(value >> 16));
    byte_push(out, (uint8_t)(value >> 24));
}

static uint16_t coff_machine(const std::string &arch)
{
    if (arch == "x64" || arch == "x86_64" || arch == "amd64")
        return 0x8664u;
    if (arch == "x86" || arch == "i686")
        return 0x014cu;
    if (arch == "arm64" || arch == "aarch64")
        return 0xaa64u;
    if (arch == "arm")
        return 0x01c4u;
    return 0;
}

static int coff_pointer_size(uint16_t machine)
{
    return machine == 0x8664u || machine == 0xaa64u ? 8 : 4;
}

bool jce_binary_embed_write_coff(const std::string &path,
                                 const std::string &symbol,
                                 const uint8_t *data, size_t size,
                                 const std::string &arch)
{
    uint16_t machine = coff_machine(arch);
    if (!machine || (size && !data))
        return false;

    const int pointer_size = coff_pointer_size(machine);
    const uint64_t size_offset =
        ((uint64_t)size + (uint64_t)pointer_size - 1u) &
        ~((uint64_t)pointer_size - 1u);
    const uint64_t rdata_size = size_offset + (uint64_t)pointer_size;
    const uint64_t rdata_aligned = (rdata_size + 3u) & ~(uint64_t)3;

    const std::string size_symbol = symbol + "_size";
    const uint32_t string_data_offset = 4;
    const uint32_t string_size_offset =
        string_data_offset + (uint32_t)symbol.size() + 1u;
    const uint32_t string_table_size =
        string_size_offset + (uint32_t)size_symbol.size() + 1u;
    const uint32_t coff_header_size = 20;
    const uint32_t section_header_size = 40;
    const uint32_t section_data_offset =
        coff_header_size + section_header_size;
    if (rdata_aligned > 0xffffffffull)
        return false;
    const uint64_t symbol_table_offset64 =
        section_data_offset + rdata_aligned;
    if (symbol_table_offset64 > 0xffffffffull ||
        rdata_size > 0xffffffffull)
        return false;
    const uint32_t symbol_table_offset =
        (uint32_t)symbol_table_offset64;

    std::vector<uint8_t> object;
    object.reserve((size_t)symbol_table_offset + 36u + string_table_size);
    byte_le16(object, machine);
    byte_le16(object, 1);
    byte_le32(object, 0);
    byte_le32(object, symbol_table_offset);
    byte_le32(object, 2);
    byte_le16(object, 0);
    byte_le16(object, 0);

    const char section_name[8] = {'.', 'r', 'd', 'a', 't', 'a', 0, 0};
    byte_append(object, section_name, sizeof(section_name));
    byte_le32(object, 0);
    byte_le32(object, 0);
    byte_le32(object, (uint32_t)rdata_size);
    byte_le32(object, section_data_offset);
    byte_le32(object, 0);
    byte_le32(object, 0);
    byte_le16(object, 0);
    byte_le16(object, 0);
    byte_le32(object, 0x40500040u);

    byte_append(object, data, size);
    while (object.size() < (size_t)(section_data_offset + size_offset))
        byte_push(object, 0);
    for (int i = 0; i < pointer_size; ++i)
        byte_push(object, (uint8_t)((uint64_t)size >> (i * 8)));
    while (object.size() < (size_t)symbol_table_offset)
        byte_push(object, 0);

    byte_le32(object, 0);
    byte_le32(object, string_data_offset);
    byte_le32(object, 0);
    byte_le16(object, 1);
    byte_le16(object, 0);
    byte_push(object, 2);
    byte_push(object, 0);
    byte_le32(object, 0);
    byte_le32(object, string_size_offset);
    byte_le32(object, (uint32_t)size_offset);
    byte_le16(object, 1);
    byte_le16(object, 0);
    byte_push(object, 2);
    byte_push(object, 0);

    byte_le32(object, string_table_size);
    byte_append(object, symbol.c_str(), symbol.size() + 1u);
    byte_append(object, size_symbol.c_str(), size_symbol.size() + 1u);
    return jce_fs_host_write_all(path.c_str(), object.data(),
                                 (uint64_t)object.size());
}

static std::string asm_escape_path(std::string path)
{
    for (char &value : path) {
        if (value == '\\')
            value = '/';
    }
    std::string escaped;
    escaped.reserve(path.size() + 8);
    for (char value : path) {
        if (value == '\\' || value == '"')
            escaped.push_back('\\');
        escaped.push_back(value);
    }
    return escaped;
}

bool jce_binary_embed_write_incbin(const std::string &path,
                                   const std::string &symbol,
                                   const std::string &input_path,
                                   size_t size)
{
    std::string text;
    text += "/* Auto-generated by JCE Editor -- DO NOT EDIT */\n";
    text += ".section .rodata\n";
    text += ".global " + symbol + "\n";
    text += ".global " + symbol + "_size\n";
    text += ".p2align 4\n";
    text += symbol + ":\n";
    text += "    .incbin \"" + asm_escape_path(input_path) + "\"\n";
    text += ".p2align 3\n";
    text += symbol + "_size:\n";
    text += "    .quad " + std::to_string(size) + "\n";
    return jce_fs_host_write_all(path.c_str(), text.data(),
                                 (uint64_t)text.size());
}
