/*
 * jce_net_vars.h  Declarative per-field network synchronisation
 * (Photon NetVar / Mirror SyncVar parity).
 *
 * A NetVar is a typed pointer registration into a global table.
 * Producer code marks the var dirty when it writes; once per tick
 * the network layer's snapshot builder pulls every dirty var,
 * encodes its value into the diff stream alongside B6 entity-state
 * snapshots, and clears the dirty bit.
 *
 * Reads on the receive side: `jce_netvar_apply_incoming` parses a
 * diff blob and writes values back into the registered pointers.
 *
 * Type set is intentionally minimal — bool / int32 / uint32 / float /
 * vec3 / quat / string (≤64) / uint64 (entity handle).  Custom
 * structs go through a serializer hook (function pointer).
 *
 * Layer: middleware/net (Layer 4) — public.
 */

#ifndef JCE_NET_VARS_H
#define JCE_NET_VARS_H

#include <jce/os/core/jce_defs.h>

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

JCE_EXTERN_C_BEGIN

#define JCE_NETVAR_REGISTRY_MAX 1024
#define JCE_NETVAR_NAME_LEN     32
#define JCE_NETVAR_STRING_LEN   64
#define JCE_NETVAR_DIFF_BUF_MAX 65536

typedef enum {
    JCE_NETVAR_BOOL    = 0,
    JCE_NETVAR_INT32   = 1,
    JCE_NETVAR_UINT32  = 2,
    JCE_NETVAR_FLOAT   = 3,
    JCE_NETVAR_VEC3    = 4,
    JCE_NETVAR_QUAT    = 5,
    JCE_NETVAR_STRING  = 6,
    JCE_NETVAR_ENTITY  = 7,
} JceNetVarType;

typedef enum {
    JCE_NETVAR_REL_RELIABLE = 0, /* always delivered */
    JCE_NETVAR_REL_UNREL    = 1, /* may drop; last-writer-wins */
} JceNetVarReliability;

typedef struct {
    /* Unique identifier — entity_id, field_id pair encoded as uint64
     * so wire format compacts. */
    uint64_t            net_id;
    char                name[JCE_NETVAR_NAME_LEN];
    JceNetVarType       type;
    JceNetVarReliability reliability;
    void               *value_ptr;       /* live pointer to data */
    /* Cached "last snapshot" copy — diff is generated by comparing
     * value_ptr against this. */
    uint8_t             cached_value[JCE_NETVAR_STRING_LEN];
    bool                dirty;
    bool                active;
} JceNetVarSlot;

/* ── Registry ────────────────────────────────────────────────── */

JCE_API void     jce_netvar_clear(void);
JCE_API uint32_t jce_netvar_register(uint64_t net_id, const char *name,
                                       JceNetVarType type,
                                       JceNetVarReliability reliability,
                                       void *value_ptr);
JCE_API bool     jce_netvar_unregister(uint64_t net_id);

JCE_API void     jce_netvar_mark_dirty(uint64_t net_id);
JCE_API void     jce_netvar_mark_all_dirty(void);

JCE_API uint32_t jce_netvar_count(void);
JCE_API const JceNetVarSlot *jce_netvar_at(uint32_t idx);

/* ── Snapshot encode / decode ───────────────────────────────── */

/* Encode every dirty var into `out_buf`.  Wire format:
 *   uint16  count
 *   for each var:
 *     uint64 net_id
 *     uint8  type
 *     value bytes (type-dependent)
 * Returns bytes written; clears dirty flags on success.  When
 * `reliability_filter < 0`, includes all dirty vars; otherwise
 * only those matching the given reliability. */
JCE_API uint32_t jce_netvar_collect_diffs(uint8_t *out_buf, uint32_t cap,
                                            int reliability_filter);

/* Apply a diff blob produced by collect_diffs on the receiving end.
 * Looks up each net_id in the local registry and writes the new
 * value through value_ptr. */
JCE_API bool jce_netvar_apply_incoming(const uint8_t *buf, uint32_t len);

JCE_EXTERN_C_END

#endif /* JCE_NET_VARS_H */
