/*
 * SnakeSeven — application entry point.
 *
 * Kept small, but NOT the stock shim: this game has scripts in six languages
 * and two of them are compiled native modules, and neither fact can be
 * arranged from a scene file.  Both of the things added here are the ones
 * scripting/README.md says an APPLICATION must do and that nothing will do
 * for it:
 *
 *   1. REGISTER THE BACKENDS.  The engine registers exactly one language for
 *      itself -- the built-in Lua VM.  Every other backend registers from a
 *      call the app makes.  Skip it and the scene still loads, the Lua module
 *      still runs, and every Python / Java / JavaScript entity is refused by
 *      name in the log: the game is missing half its behaviour and nothing
 *      failed.  jce_script_enable() in CMakeLists.txt links them and
 *      generates jce_script_register_linked_languages(); this calls it.
 *
 *   2. PUBLISH THE NATIVE MODULES, before the first scene loads, because a
 *      scene's Script components are instantiated inside jce_runtime_create()
 *      and a language registered after that point is a language every entity
 *      has already been refused by.  The C and C++ "scripts" are classes in
 *      compiled modules, not files the engine opens, so somebody has to hand
 *      the registry the .dll.  In the EDITOR that happens on project-open;
 *      a shipped game has no project-open, so it happens here.
 *
 * The paths are baked at configure time rather than searched for at runtime:
 * jce_script_vm_cpp_load_library() refuses a relative path on purpose (a bare
 * name binds to whatever module of that name is already resident), and a
 * game that guessed would bind to the wrong build without saying so.
 */

#include "_embedded_bundles.h"           /* generated by CMake */
#include <jce/application/jce_default_main.inc.h>

#include <jce/script_vm/jce_script_vm_cpp.h>
#include <jce/script_vm/jce_script_vm_c.h>
#if defined(SNAKE_HAVE_CSHARP)
#  include <jce/script_vm/jce_script_vm_csharp.h>
#endif
#include <jce/middleware/script/jce_script_vm.h>
#include <jce_script_register_linked.h>  /* generated by jce_script_enable() */

/* LOG_INFO compiles to ((void)0) in a release build (jce_log.h:191,212), and
 * this demo's whole point is that a RELEASE executable can be shown to run
 * six languages.  A verification line that disappears in the configuration
 * under test is not a verification line, so this goes through the function
 * the macro would have called. */
#define SNAKE_SAY(...)     jce_log_write(JCE_LOG_LEVEL_INFO, "snake", __FILE__, __LINE__, __VA_ARGS__)

/* Published to the ONE native class registry that serves both the c and the
 * cpp language -- there is no separate jce_script_vm_c_add_module, and that
 * is deliberate: a compiled class has no language at run time. */
/* The two native script modules, LINKED IN.
 *
 * Each JCE_C/CPP_MODULE_END emits an accessor for exactly this use, and the
 * header is explicit that a statically linked module needs no exported entry
 * (jce_script_cpp.hpp:566).  Shipping them as .dll files beside the exe was a
 * choice I made and it was the wrong one: it turned "a single executable"
 * into four files, and it put the module ABI behind a runtime path lookup
 * that can silently bind to yesterday's build.
 *
 * Compiled in, the module cannot be missing, cannot be stale, and cannot be
 * the wrong architecture. */
extern const JceCppModuleDesc *snake_cpp_module(void);
extern const JceCModuleDesc   *snake_c_module(void);

static void snake_publish_native_modules(void)
{
#if !defined(SNAKE_HAVE_NATIVE_MODULES)
    /* c/cpp are not in this build: their classes would call
     * jce_script_api, which is the one shared object a single-file build
     * is trying not to need. */
    return;
#else
    /* ONE registry serves both languages -- there is no
     * jce_script_vm_c_add_module, and that is deliberate: a compiled class
     * has no language at run time, only a table of function pointers. */
    if (!jce_script_vm_cpp_add_module(snake_cpp_module()))
        LOG_ERROR("snake", "the C++ script module was refused by the registry "
                           "-- the body will not follow the head.");
    else
        SNAKE_SAY("%s", "C++ script module: linked in");

    /* No cast: jce_script_vm_c.h:205 is `typedef JceCppModuleDesc
     * JceCModuleDesc` -- the two languages genuinely share one descriptor,
     * and a cast here would only hide a future divergence. */
    if (!jce_script_vm_cpp_add_module(snake_c_module()))
        LOG_ERROR("snake", "the C script module was refused by the registry "
                           "-- the score bar will not move.");
    else
        SNAKE_SAY("%s", "C script module: linked in");
#endif
}

static void snake_vm_log(void *user, const char *msg)
{
    (void)user;
    LOG_ERROR("snake.csharp", "%s", msg ? msg : "(null)");
}

static void snake_load_csharp_assembly(void)
{
    char buf[1024];
    const char *path;
    const JceScriptVM *vm;
    JceScriptHost host;
    JceScript *s;

#if !defined(SNAKE_CS_ASSEMBLY) || !defined(SNAKE_HAVE_CSHARP)
    /* csharp was not linked into this build (single-file mode
     * drops it: .NET is not ours to embed). */
    return;
#else
    {   /* Beside the exe first, then the configure-time path: a shipped
         * directory has no source tree to point at. */
        char base[1024];
        path = SNAKE_CS_ASSEMBLY;
        if (jce_fs_host_get_base_path(base, sizeof base) && base[0]) {
            snprintf(buf, sizeof buf, "%sSnakeScripts.dll", base);
            if (jce_fs_host_exists_file(buf)) path = buf;
        }
    }
    vm = jce_script_vm_find("csharp");
    if (!vm || !vm->create_sized) {
        LOG_ERROR("snake", "no csharp VM is registered in this build -- "
                           "the HUD will not update.");
        return;
    }
    memset(&host, 0, sizeof host);
    /* A LOG SINK, because a zeroed host has none and the managed side reports
     * a failed load through host.log.  The first attempt passed {0} and the
     * load came back false with NO explanation anywhere -- the VM had no way
     * to speak.  An instrument that cannot report is indistinguishable from
     * one that found nothing. */
    host.log = snake_vm_log;
    s = vm->create_sized(&host, sizeof host);
    if (!s) {
        LOG_ERROR("snake", "could not open a csharp VM to load %s", path);
        return;
    }
    if (jce_script_vm_csharp_load_assembly(s, path))
        SNAKE_SAY("C# game assembly loaded: %s", path);
    else
        LOG_ERROR("snake",
                  "C# game assembly did not load: %s -- the HUD will not update.  If this is a fresh checkout, check that the assembly beside the exe is the one this build produced: MSBuild's default output path follows the Platform property, so it can land in bin/x64/Release while a consumer looks in bin/Release, and the build reports success either way.", path);
    if (vm->destroy) vm->destroy(s);
#endif
}

static bool snake_init(const JceServices *svc, void *ud)
{
    /* BEFORE app_init(), which is what loads the first scene. */
    const int n = jce_script_register_linked_languages(snake_publish_native_modules);
    SNAKE_SAY("script backends registered: %d (lua is built in and not "
              "counted)", n);
    snake_load_csharp_assembly();
    return app_init(svc, ud);
}

static JceAppDesc SnakeSeven_get_desc(void)
{
    JceAppDesc d = (JceAppDesc){0};
    d.name          = "SnakeSeven";
    d.init          = snake_init;
    d.update        = app_update;
    d.draw          = app_draw;
    d.exit          = app_exit;
    d.window_width  = 1280;
    d.window_height = 720;
    return d;
}

JCE_MAIN(SnakeSeven_get_desc)
