#!/usr/bin/env python3
"""
check_readme_facts.py -- the front page's numbers must still be true.

THE FAILURE THIS GUARDS, and it had already happened when this was written:
README.md listed FIFTEEN public umbrella headers.  The tree had twenty-three.
Nobody typed it wrongly -- the tree moved, over roughly a month, and the README
did not.  Then the repository was made public, and that table became the first
thing a stranger read about the API surface.

It is the same defect this codebase keeps catching in its own gates and
ledgers: A NUMBER THAT IS PRINTED BUT NOT DERIVED STOPS BEING TRUE AND SAYS
NOTHING WHEN IT DOES.  The README is the worst place for it, because it is the
one file a reader consults BEFORE they are able to check anything themselves.

So the volatile half of the README is generated by tools/report_readme_facts.py
between two markers, and this regenerates it and compares.  Drift is a FAIL with
the exact command to fix it.  The prose around the block stays hand-written;
prose is not data and this checker does not touch it.

WHY IT IMPORTS THE GENERATOR RATHER THAN RE-DERIVING.  A checker that computed
the facts a second way would be a second implementation of the same thing, and
the two would eventually disagree -- at which point the README would be "wrong"
according to a rule nobody could satisfy.  One producer, one consumer.

NOT CHECKED, said here rather than left to be discovered: whether the PROSE is
true.  "The engine has zero JCE_EDITOR conditionals" is a sentence in the same
file and this checker cannot read it.  That particular claim has its own gate
(check_engine_cxx_bridges.py and the editor-purity checkers); most of the rest
is ordinary prose and carries ordinary risk.
"""
import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
README = REPO_ROOT / "README.md"
GENERATOR = REPO_ROOT / "tools/report_readme_facts.py"


def load_generator():
    spec = importlib.util.spec_from_file_location("jce_readme_facts", GENERATOR)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    if not README.is_file():
        print("check_readme_facts: FAIL - README.md is missing.",
              file=sys.stderr)
        return 1
    if not GENERATOR.is_file():
        print("check_readme_facts: FAIL - %s is missing; the generated block "
              "has no producer." % GENERATOR.name, file=sys.stderr)
        return 1

    gen = load_generator()
    src = README.read_text(encoding="utf-8")

    if gen.BEGIN not in src or gen.END not in src:
        print("check_readme_facts: FAIL - README.md has no generated block.\n"
              "  The at-a-glance figures and the public-API table are DERIVED, "
              "not typed. Restore the markers and regenerate:\n"
              "    %s\n    %s\n    python tools/report_readme_facts.py --write"
              % (gen.BEGIN, gen.END), file=sys.stderr)
        return 1

    have = src.split(gen.BEGIN, 1)[1].split(gen.END, 1)[0]
    want = gen.block().split(gen.BEGIN, 1)[1].split(gen.END, 1)[0]

    if have != want:
        # Name the lines that moved.  "The README is stale" sends a reader to
        # diff two blocks by eye; "23 umbrellas, the README says 15" does not.
        hl = have.strip().splitlines()
        wl = want.strip().splitlines()
        diffs = []
        for i in range(max(len(hl), len(wl))):
            a = hl[i] if i < len(hl) else "(missing)"
            b = wl[i] if i < len(wl) else "(removed)"
            if a != b:
                diffs.append((a, b))
        print("check_readme_facts: FAIL - README.md's generated block is stale "
              "(%d line(s) differ):" % len(diffs), file=sys.stderr)
        for a, b in diffs[:12]:
            print("    README : %s" % a.strip()[:110], file=sys.stderr)
            print("    tree   : %s" % b.strip()[:110], file=sys.stderr)
        if len(diffs) > 12:
            print("    ... and %d more" % (len(diffs) - 12), file=sys.stderr)
        print("  Fix: python tools/report_readme_facts.py --write",
              file=sys.stderr)
        return 1

    print("check_readme_facts: OK (README.md's generated block matches the "
          "tree; %d line(s) derived)" % len(want.strip().splitlines()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
