# Validate actual MSVC symbol providers, not only requested libraries.
if(NOT MAP_FILE OR NOT EXISTS "${MAP_FILE}")
    message(FATAL_ERROR "JCE codec link check: fresh linker map is required")
endif()
file(STRINGS "${MAP_FILE}" _lines
    REGEX "[ 	]dav1d_(open|send_data|get_picture|data_create|picture_unref)[ 	]")
foreach(_symbol open send_data get_picture data_create picture_unref)
    set(_found FALSE)
    foreach(_line IN LISTS _lines)
        if(_line MATCHES "[ 	]dav1d_${_symbol}[ 	]")
            if(NOT _line MATCHES "[ 	](dav1d|jce_av1_codec):")
                message(FATAL_ERROR "JCE codec link check: unexpected AV1 provider: ${_line}")
            endif()
            set(_found TRUE)
        endif()
    endforeach()
    if(NOT _found)
        message(FATAL_ERROR "JCE codec link check: missing dav1d_${_symbol}")
    endif()
endforeach()
message(STATUS "JCE codec link check: canonical AV1 provider verified")
