/* test_jce_script_cpp_contract.cpp — the wrapper's own contracts, and the
 * places where it deliberately does NOT match Lua.
 *
 * HAND-WRITTEN.  The generated half is the sweep: every manifest entry, both
 * languages, result and trace.  What is here is everything that is a
 * statement ABOUT the wrapper rather than a case OF it —
 *
 *   * the C++ types the header promises, as static_asserts, so a shape that
 *     regressed to a raw pointer or a copyable handle fails to COMPILE;
 *   * the second host call a long owned string costs, measured rather than
 *     described;
 *   * the caller's host_size reaching the C ABI, with the vacuity check that
 *     proves the truncation withholds anything at all;
 *   * the C++20 std::span overload, CALLED -- it is a non-template member, so
 *     including the header at C++20 type-checks it and nothing ran it;
 *   * two places where the C ABI and the Lua binding genuinely disagree.
 *     Neither is this backend's to fix — the C ABI is generated by a different
 *     tool and is not mine to edit — so each is PINNED here by name.  An
 *     unpinned known divergence is an immune mutation with a silent reason.
 *
 * doctest's main lives in THIS translation unit, not in the generated one: a
 * generated file that owns main() is a generated file that owns the test
 * runner's configuration.
 */
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

#include "jce_script_cpp_differential.hpp"

#include <cstddef>
#include <cstring>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

using jce::script::Api;
using jce::script::CStr;
using jce::script::Entity;

/* ------------------------------------------------------------------ *
 *  1. The types the header promises.
 *
 *  These are static_asserts and not TEST_CASEs on purpose: every one of them
 *  is a claim about a TYPE, and the moment a type stops holding, this file
 *  stops compiling.  A runtime check of a compile-time fact is a check that
 *  runs after the damage.
 * ------------------------------------------------------------------ */

/* The RAII handle is move-only.  Two owners would close one handle twice. */
static_assert(!std::is_copy_constructible<Api>::value,
              "Api must not be copyable -- two owners, one jce_script_api_close");
static_assert(!std::is_copy_assignable<Api>::value, "Api must not be copy-assignable");
static_assert(std::is_move_constructible<Api>::value, "Api must be movable");
static_assert(std::is_move_assignable<Api>::value, "Api must be move-assignable");
static_assert(std::is_nothrow_destructible<Api>::value,
              "~Api closes a handle and must not throw");
static_assert(std::is_default_constructible<Api>::value,
              "a default-constructed Api is the empty handle every method "
              "still accepts");

/* The owned-string shape.  THE point of this wrapper: no char *, no buffer
 * size, nothing for the caller to free.  If either of these ever becomes a
 * pointer again, the leak this shape removed is back. */
static_assert(std::is_same<decltype(std::declval<const Api &>()
                                        .comp_get(Entity{}, CStr{})),
                           std::optional<std::string>>::value,
              "comp_get must hand back an owned optional<string>");
static_assert(std::is_same<decltype(std::declval<const Api &>().render_get()),
                           std::optional<std::string>>::value,
              "render_get must hand back an owned optional<string>");

/* The other shapes, one representative each — the sweep compares their
 * VALUES, and these pin the TYPE the sweep's projection is keyed on. */
static_assert(std::is_same<decltype(std::declval<const Api &>()
                                        .get_position(Entity{})),
                           std::optional<std::array<float, 3>>>::value,
              "fallible_out with one array out is optional<array>");
static_assert(std::is_same<decltype(std::declval<const Api &>().move_axis()),
                           std::array<float, 2>>::value,
              "void_out_array is a fixed-size array, not an out parameter");
static_assert(std::is_same<decltype(std::declval<const Api &>()
                                        .find_by_prefix(CStr{})),
                           std::vector<Entity>>::value,
              "entity_table is a vector");
static_assert(std::is_same<decltype(std::declval<const Api &>()
                                        .find_by_name(CStr{})),
                           jce::script::FirstAndCount>::value,
              "first_and_count keeps the 'or nil' in the type");
static_assert(std::is_same<decltype(std::declval<const Api &>().tr(CStr{})),
                           std::string>::value,
              "a const char * return becomes an owned string, as Lua's "
              "lua_pushstring copy does");

/* CStr converts from the two things that are already NUL-terminated and from
 * nothing else.  The string_view exclusion is the design decision; a
 * static_assert is what keeps it from being un-made by accident. */
static_assert(std::is_convertible<const char *, CStr>::value, "");
static_assert(std::is_convertible<const std::string &, CStr>::value, "");
static_assert(!std::is_constructible<CStr, std::string_view>::value,
              "CStr must NOT accept a string_view: a view is not "
              "NUL-terminated, so accepting one would make this wrapper copy "
              "every string argument to add a NUL -- a heap allocation per "
              "call inside on_update");

/* ------------------------------------------------------------------ *
 *  2. The caller's host_size is what reaches the C ABI.
 * ------------------------------------------------------------------ */

static bool g_poison_called;

extern "C" {
/* The exact signature of the member the truncation withholds, so this is a
 * real call and not a cast through an incompatible function type. */
static void poison_set_locale(void *user, const char *locale)
{
    (void)user;
    (void)locale;
    g_poison_called = true;
}
}

TEST_CASE("the caller's host_size is what reaches the C ABI")
{
    JceScriptHost full;
    jce::diff::install_recording_host(&full);

    /* Truncate at the LAST member.  As the struct grows this point moves with
     * it, so the test keeps withholding a real tail instead of testing a
     * member that stopped being last. */
    const std::size_t trunc = offsetof(JceScriptHost, loc_set_locale);
    REQUIRE(trunc < sizeof(JceScriptHost));

    typedef void (*SetLocaleFn)(void *, const char *);
    SetLocaleFn poison = poison_set_locale;

    const std::size_t tail_slots = 8;
    std::vector<unsigned char> shorter(trunc + tail_slots * sizeof poison, 0);
    std::memcpy(shorter.data(), &full, trunc);
    for (std::size_t i = 0; i < tail_slots; ++i)
        std::memcpy(shorter.data() + trunc + i * sizeof poison,
                    &poison, sizeof poison);

    const JceScriptHost *as_host =
        reinterpret_cast<const JceScriptHost *>(shorter.data());

    SUBCASE("the honest size is honoured")
    {
        g_poison_called = false;
        {
            Api api = Api::open(*as_host, trunc);
            REQUIRE(static_cast<bool>(api));
            api.set_locale("zh_cn");
        }
        CHECK_FALSE(g_poison_called);
    }

    SUBCASE("and the truncation really withholds something")
    {
        /* The vacuity check.  Hand the SAME buffer over claiming the full
         * size and the poison DOES fire -- so the assertion above is about
         * host_size and not about a truncation that withheld nothing.  This
         * is the shape batch 1's "the truncation point withholds nothing --
         * this test has gone vacuous" assertion exists for. */
        g_poison_called = false;
        {
            Api api = Api::open(*as_host, sizeof(JceScriptHost));
            REQUIRE(static_cast<bool>(api));
            api.set_locale("zh_cn");
        }
        CHECK(g_poison_called);
    }
}

/* ------------------------------------------------------------------ *
 *  3. A long owned string costs a second host call.
 * ------------------------------------------------------------------ */

TEST_CASE("a long owned string costs a second host call")
{
    JceScriptHost h;
    jce::diff::install_recording_host(&h);
    jce::diff::g_mode = jce::diff::MOCK_LONG;

    std::string lua_out = jce::diff::run_lua_case(&h, sizeof h,
                                                  "jce.comp_get(41, 'x')");
    std::string lua_trace = jce::diff::trace_text();
    INFO("lua said: " << lua_out.substr(0, 64));
    REQUIRE(jce::diff::last_run_ok());

    jce::diff::trace_reset();
    std::optional<std::string> cpp_out;
    {
        Api api = Api::open(h);
        REQUIRE(static_cast<bool>(api));
        cpp_out = api.comp_get(41, "x");
    }
    std::string cpp_trace = jce::diff::trace_text();
    jce::diff::g_mode = jce::diff::MOCK_OK;

    const std::string expect = jce::diff::long_json_text();

    /* The VALUE survives the round trip on both sides.  This is the half that
     * matters to a user. */
    REQUIRE(cpp_out.has_value());
    CHECK(*cpp_out == expect);
    CHECK(lua_out == "1|string:" + expect);

    /* The COST does not survive it, and this is where it is written down.
     * Lua's binding pushes the host's pointer straight into the VM, so one
     * call suffices; the C ABI copies into a caller buffer and releases
     * before returning, so a result that did not fit is only reachable by
     * asking again.  Measured, not asserted from the code. */
    CHECK(jce::diff::trace_calls(lua_trace, "comp_get_json") == 1);
    CHECK(jce::diff::trace_calls(cpp_trace, "comp_get_json") == 2);
    CHECK(jce::diff::trace_calls(lua_trace, "json_free") == 1);
    CHECK(jce::diff::trace_calls(cpp_trace, "json_free") == 2);
}

TEST_CASE("a short owned string costs exactly one host call")
{
    /* The other side of the same measurement: without this, "two calls" above
     * could be the ONLY behaviour and the inline buffer would be doing
     * nothing at all. */
    JceScriptHost h;
    jce::diff::install_recording_host(&h);
    jce::diff::g_mode = jce::diff::MOCK_OK;

    jce::diff::trace_reset();
    std::optional<std::string> cpp_out;
    {
        Api api = Api::open(h);
        cpp_out = api.comp_get(41, "x");
    }
    REQUIRE(cpp_out.has_value());
    CHECK(cpp_out->size() < (std::size_t)Api::kOwnedStringInlineBytes);
    CHECK(jce::diff::trace_calls(jce::diff::trace_text(), "comp_get_json") == 1);
}

/* ------------------------------------------------------------------ *
 *  3b. The C++20 span overload, RUN and not merely compiled.
 *
 *  The header and the README both say C++20 is USED and never required, and
 *  that what a C++20 consumer gains is exactly this overload.  Until this
 *  test existed, that was a promise nothing enforced: the overload is a
 *  non-template member of a non-template class, so including the header at
 *  C++20 type-checks its body and NOTHING CALLED IT -- the shape this repo
 *  keeps rediscovering as built-but-unwired.
 *
 *  The floor TU asserts JCE_SCRIPT_CPP_HAS_SPAN == 0 at C++17.  This is the
 *  other half of that pair.
 * ------------------------------------------------------------------ */

static_assert(JCE_SCRIPT_CPP_HAS_SPAN == 1,
              "this TU is built at C++20 (tests/scripting/cpp/CMakeLists.txt) "
              "so <span> must be available here; if this fires, the "
              "__cpp_lib_span guard is refusing a toolchain that HAS span and "
              "the allocation-free overload has silently disappeared from "
              "every C++20 consumer");

TEST_CASE("the C++20 span overload passes the CALLER's capacity, and allocates nothing")
{
    JceScriptHost h;
    jce::diff::install_recording_host(&h);
    jce::diff::g_mode = jce::diff::MOCK_OK;

    /* Four slots, a span over the first three.  The recording mock writes
     * exactly three entries whatever `max` says, so the fourth slot is a
     * canary for the WRAPPER writing past the span it was handed. */
    Entity buf[4] = { 0u, 0u, 0u, 0xFEEDu };

    /* WHAT THE MOCK PRODUCES IS DERIVED, so it is read and not written down.
     * The generator numbers each mock's entity ids by the member's position in
     * the manifest, so this test used to hardcode 164/165/166 and any APPEND to
     * JceScriptHost -- the one change the ABI rules explicitly permit -- broke
     * it by three assertions that named no cause.  Probe the raw host once,
     * before the trace is armed, and compare against that. */
    Entity probe[3] = { 0u, 0u, 0u };
    const int probe_n = h.find_by_prefix(h.user, "x", probe, 3);
    REQUIRE(probe_n == 3);

    jce::diff::trace_reset();
    int n = 0;
    {
        Api api = Api::open(h);
        n = api.find_by_prefix("x", std::span<Entity>(buf, 3));
    }
    const std::string trace = jce::diff::trace_text();

    CHECK(n == 3);
    CHECK(buf[0] == probe[0]);
    CHECK(buf[1] == probe[1]);
    CHECK(buf[2] == probe[2]);
    CHECK(buf[3] == 0xFEEDu);

    /* The SPAN'S SIZE is what reached the host as `max`.  A wrapper that
     * passed its own out_capacity of 1024, or 0, would fill this buffer and
     * return 3 either way -- the trace is the only place that difference is
     * visible, which is the same reason the differential compares it. */
    CHECK(trace == "find_by_prefix|x|3\n");

    /* ONE host call: the vector overload's allocate-fill-copy is not
     * happening behind this one, which is the whole point of the overload. */
    CHECK(jce::diff::trace_calls(trace, "find_by_prefix") == 1);
}

/* ------------------------------------------------------------------ *
 *  4. Known divergences, pinned.
 *
 *  Each of these is a real difference between what a Lua script sees and what
 *  a C++ caller sees.  Neither is fixable from here: the C ABI is generated
 *  by tools/scriptgen/gen_script_c_abi.py, which this backend does not own.
 *  Pinning them means the next person finds them as a named test instead of
 *  as a surprise, and that a CHANGE to either side goes red.
 * ------------------------------------------------------------------ */

TEST_CASE("a producer with no releaser: Lua answers, the C ABI refuses")
{
    /* A partial host -- comp_get_json present, json_free absent.  The Lua
     * binding pushes the string and SKIPS the release (it leaks, knowingly:
     * that is what the hand-written original did).  The C ABI refuses the
     * whole call rather than leak, so it never reaches the host at all.
     *
     * The C ABI's choice is the better one.  It is recorded here because it
     * is a DIFFERENT SURFACE, not because it is wrong. */
    JceScriptHost h;
    jce::diff::install_recording_host(&h);
    h.json_free = nullptr;
    jce::diff::g_mode = jce::diff::MOCK_OK;

    std::string lua_out = jce::diff::run_lua_case(&h, sizeof h,
                                                  "jce.comp_get(41, 'x')");
    std::string lua_trace = jce::diff::trace_text();
    INFO("lua said: " << lua_out);
    REQUIRE(jce::diff::last_run_ok());

    jce::diff::trace_reset();
    std::optional<std::string> cpp_out;
    {
        Api api = Api::open(h);
        cpp_out = api.comp_get(41, "x");
    }
    std::string cpp_trace = jce::diff::trace_text();

    CHECK(lua_out.rfind("1|string:", 0) == 0);
    CHECK(jce::diff::trace_calls(lua_trace, "comp_get_json") == 1);

    CHECK_FALSE(cpp_out.has_value());
    CHECK(jce::diff::trace_calls(cpp_trace, "comp_get_json") == 0);
}

/* Not a divergence -- and it is here because I predicted one and was wrong.
 *
 * get_touch_count carries `clamp_min` precisely because a host CAN answer a
 * negative count, so the same question about find_by_prefix is not
 * hypothetical.  The C++ wrapper clamps.  The Lua binding does not: it passes
 * the raw count to lua_createtable, which looked like a request for ~4 billion
 * slots.  MEASURED: lua_createtable guards its size hint with `narray > 0`,
 * so a negative count yields an EMPTY table and the loop after it does not
 * run.  Both sides answer the empty list.
 *
 * The sweep in the generated half now covers this case too, and this test is
 * NOT redundant with it: the sweep proves the two AGREE, and this pins the
 * value they agree on.  Two implementations agreeing on a wrong value is
 * still a wrong value, and the sweep structurally cannot say which. */
TEST_CASE("a negative entity_table count is the empty list on both sides")
{
    JceScriptHost h;
    jce::diff::install_recording_host(&h);
    jce::diff::g_mode = jce::diff::MOCK_NEGATIVE;

    std::string lua_out = jce::diff::run_lua_case(&h, sizeof h,
                                                  "jce.find_by_prefix('x')");
    std::string lua_trace = jce::diff::trace_text();
    INFO("lua said: " << lua_out);
    REQUIRE(jce::diff::last_run_ok());

    jce::diff::trace_reset();
    jce::diff::Slots s;
    {
        Api api = Api::open(h);
        jce::diff::record(s, api.find_by_prefix("x"));
    }
    std::string cpp_trace = jce::diff::trace_text();
    jce::diff::g_mode = jce::diff::MOCK_OK;

    CHECK(s.str() == "1|table:[]");
    CHECK(lua_out == s.str());
    CHECK(lua_trace == cpp_trace);
}
