/* jce_embedded_assets.h — extern declarations for PAK blob symbols.
 *
 * The actual data is provided by the executable (caged_kingdom or editor)
 * which links the PAK blob object generated by jce_pak.
 *
 * On Emscripten the PAK is not linked in; the runtime opens it via
 * pak_open_file("/game_assets.pak") from the Emscripten virtual FS.
 *
 * On Android and JNI desktop mode the PAK is loaded from external file
 * at runtime to avoid duplicating ~290 MB per platform/architecture.
 */
#pragma once

#if !defined(__EMSCRIPTEN__) && !defined(__ANDROID__) && !defined(JCE_BUILD_JNI)

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char assets_pak_data[];
extern const size_t        assets_pak_data_size;

#ifdef __cplusplus
}
#endif

#endif /* !__EMSCRIPTEN__ && !__ANDROID__ && !JCE_BUILD_JNI */
