/*
 * @JCE_PROJECT_NAME@ — application entry point.
 *
 * This file is intentionally TINY: the real app body lives in the SDK
 * header `<jce/application/jce_default_main.inc.h>` so engine upgrades
 * reach this project automatically on the next Build — no need to
 * regenerate or hand-merge changes to main.c.
 *
 * To deeply customise the boot flow (custom camera, multiple scenes,
 * splash screen, …) use Project Settings → Eject main.c.  That
 * replaces this shim with the inlined body and stops tracking engine
 * upgrades for this file — by design.
 */

#include "_embedded_bundles.h"           /* generated by CMake */
#include <jce/application/jce_default_main.inc.h>

static JceAppDesc @JCE_PROJECT_NAME@_get_desc(void)
{
    JceAppDesc d = (JceAppDesc){0};
    d.name          = "@JCE_PROJECT_NAME@";
    d.init          = app_init;
    d.update        = app_update;
    d.draw          = app_draw;
    d.exit          = app_exit;
    d.window_width  = 1280;
    d.window_height = 720;
    return d;
}

JCE_MAIN(@JCE_PROJECT_NAME@_get_desc)
