#!/usr/bin/env python3
"""Emit every PBR fragment entry .sc and the key->program table from
contracts/shader-keywords.json.

WHY A GENERATOR AND NOT NINE MORE FILES.  A static-switch axis in this engine
used to cost a new fs_*.sc per fragment family, a JceShaderSet member, a
renderer field, a getter, a destroy, and a selection site per draw path.  The
engine HAS an axis that works and was measured -- JCE_NO_CSM takes fs_pbr from
8311 instructions to 1549 -- and it was reverted, because the version that
wired six of the seven selection sites silently did nothing on the seventh.
That is the failure this file exists to make impossible: the table below is
the only list of programs, and jce_shader_variants.c is the only code that
picks one.

NO ARGUMENTS = CHECK MODE, read-only, exit 1 on any drift.  --write rewrites.
Same shape as tools/scriptgen/*, and for the same reason: a generator whose
check mode needs a flag gets run with the flag missing.
"""
from __future__ import annotations

import argparse
import io
import itertools
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "contracts" / "shader-keywords.json"

BANNER = "GENERATED by tools/shadergen/gen_shader_variants.py -- DO NOT EDIT."


def wrap(text: str, width: int = 74, indent: str = " * ") -> list[str]:
    out, line = [], ""
    for word in text.split():
        if line and len(line) + 1 + len(word) > width:
            out.append(indent + line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        out.append(indent + line)
    return out


def load() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def axes_for(family: str, axes: list[dict]) -> list[dict]:
    """The axes that apply to one fragment family, in bit order."""
    out = [a for a in axes
           if "*" in a["families"] or family in a["families"]]
    return sorted(out, key=lambda a: a["bit"])


def fs_name(family: str, combo: tuple[dict, ...]) -> str:
    return "fs_" + family + "".join(a["suffix"] for a in combo)


def emit_sc(m: dict, fam: dict, combo: tuple[dict, ...]) -> str:
    varyings = m["varying_sets"][fam["varyings"]]
    lines = [f"$input {varyings}", ""]
    lines.append("/*")
    lines.append(f" * {fs_name(fam['name'], combo)}.sc  --  {BANNER}")
    lines.append(" *")
    lines += wrap(fam["why"])
    for a in combo:
        lines.append(" *")
        lines += wrap(f"+{a['name'].upper()}: {a['why']}")
    lines.append(" *")
    lines += wrap(
        "$input MUST stay in this file: shaderc strips the leading $input "
        "only from the MAIN .sc, never from an #include'd one. The whole body "
        "lives in " + m["body"] + " so every variant is built from ONE source "
        "of truth by adding defines -- that is what makes an axis one line in "
        "contracts/shader-keywords.json instead of a file per family.")
    lines.append(" */")
    lines.append("")
    for d in fam["defines"]:
        lines.append(f"#define {d}")
    for a in combo:
        lines.append(f"#define {a['define']}")
    lines.append(f'#include "{m["body"]}"')
    return "\n".join(lines) + "\n"


def combos(fam: dict, axes: list[dict]) -> list[tuple[dict, ...]]:
    applicable = axes_for(fam["name"], axes)
    out: list[tuple[dict, ...]] = []
    for r in range(len(applicable) + 1):
        out.extend(itertools.combinations(applicable, r))
    return out


def bits_of(combo: tuple[dict, ...]) -> int:
    v = 0
    for a in combo:
        v |= 1 << a["bit"]
    return v


def emit_public_header(m: dict) -> str:
    axes = m["axes"]
    vvs = m["vertex_variants"]
    nbits = max(a["bit"] for a in axes) + 1
    L: list[str] = []
    L.append("/*")
    L.append(f" * jce_shader_variants.h  --  {BANNER}")
    L.append(" *")
    L += wrap(
        "WHICH PROGRAM A DRAW GETS, as a pair of coordinates instead of a "
        "name. The VERTEX VARIANT is what the draw path is -- static, "
        "instanced, skinned, and the three instanced forms that carry extra "
        "per-instance data. The KEYWORD BITS are what the material and the "
        "frame ask for. jce_renderer_get_program_variant turns the pair into "
        "a program, and it is the ONLY place that decision is made.")
    L.append(" *")
    L += wrap(
        "Adding an axis is one entry in contracts/shader-keywords.json. It "
        "used to be nine files, and the last attempt wired six of seven "
        "selection sites and silently did nothing on the seventh -- which is "
        "why the sites no longer choose at all.")
    L.append(" *")
    L += wrap("Layer: renderer (Layer 3) -- public, generated.")
    L.append(" */")
    L.append("#ifndef JCE_SHADER_VARIANTS_H")
    L.append("#define JCE_SHADER_VARIANTS_H")
    L.append("")
    L.append("#include <jce/os/core/jce_defs.h>")
    L.append("")
    L.append("JCE_EXTERN_C_BEGIN")
    L.append("")
    L.append(f"#define JCE_SHADER_AXIS_COUNT {nbits}")
    L.append(f"#define JCE_SHADER_VARIANT_COUNT {len(vvs)}")
    L.append(f"#define JCE_SHADER_KEY_COUNT {1 << nbits}")
    L.append("")
    for a in sorted(axes, key=lambda x: x["bit"]):
        L.append("/*")
        L += wrap(a["why"])
        L.append(" */")
        L.append(f"#define JCE_SHADER_KEY_{a['name'].upper()} "
                 f"(1u << {a['bit']}u)")
    L.append("")
    L.append("typedef enum {")
    for i, vv in enumerate(vvs):
        L.append(f"    /* {vv['why']} */")
        L.append(f"    JCE_SHADER_VV_{vv['name'].upper()} = {i},")
    L.append("} JceShaderVertexVariant;")
    L.append("")
    L.append("JCE_EXTERN_C_END")
    L.append("")
    L.append("#endif /* JCE_SHADER_VARIANTS_H */")
    return chr(10).join(L) + chr(10)


def emit_table(m: dict) -> str:
    axes = m["axes"]
    fams = {f["name"]: f for f in m["fs_families"]}
    vvs = m["vertex_variants"]
    nbits = max(a["bit"] for a in axes) + 1

    L: list[str] = []
    L.append("/*")
    L.append(f" * jce_shader_variants_table.inc  --  {BANNER}")
    L.append(" *")
    L += wrap(
        "The ONE list of PBR programs. A program is (vertex variant, keyword "
        "bits); the vertex variant picks its fragment family because the "
        "varyings have to match, and the keyword bits are what the material "
        "and the frame ask for. An entry whose fragment family does not carry "
        "an axis maps to the same program as without it -- stated here rather "
        "than left to a fallback nobody reads, so the table is TOTAL: every "
        "(variant, bits) pair has a row.")
    L.append(" *")
    L += wrap("The enum and the key macros are in the PUBLIC header "
              "<jce/renderer/jce_shader_variants.h>; this file is only the "
              "name table, which no caller outside jce_shaders.c needs.")
    L.append(" */")
    L.append("")
    L.append('#include <jce/renderer/jce_shader_variants.h>')
    L.append("")
    L.append("static const char *const jce_shader_vv_name"
             "[JCE_SHADER_VARIANT_COUNT] = {")
    for vv in vvs:
        L.append(f'    "{vv["name"]}",')
    L.append("};")
    L.append("")
    L.append("/* [vertex variant][keyword bits] -> fragment program base name,")
    L.append(" * WITHOUT the fs_ prefix, because that is what")
    L.append(" * shader_load_program_named takes -- it prefixes vs_/fs_ itself. */")
    L.append("static const char *const jce_shader_fs_for"
             "[JCE_SHADER_VARIANT_COUNT][JCE_SHADER_KEY_COUNT] = {")
    for vv in vvs:
        fam = fams[vv["fs_family"]]
        applicable = {a["bit"] for a in axes_for(fam["name"], axes)}
        row = []
        for key in range(1 << nbits):
            kept = tuple(sorted(
                (a for a in axes if (key >> a["bit"]) & 1
                 and a["bit"] in applicable),
                key=lambda a: a["bit"]))
            # the loader prefixes fs_ itself, so the table carries the base
            row.append(f'"{fs_name(fam["name"], kept)[3:]}"')
        L.append(f"    /* {vv['name']} */ {{ " + ", ".join(row) + " },")
    L.append("};")
    return "\n".join(L) + "\n"


def wanted(m: dict) -> dict[Path, str]:
    out: dict[Path, str] = {}
    sdir = ROOT / m["shader_dir"]
    for fam in m["fs_families"]:
        for combo in combos(fam, m["axes"]):
            out[sdir / (fs_name(fam["name"], combo) + ".sc")] = emit_sc(m, fam, combo)
    out[ROOT / m["public_header_out"]] = emit_public_header(m)
    out[ROOT / m["table_out"]] = emit_table(m)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true",
                    help="rewrite the generated files (default: check only)")
    args = ap.parse_args()

    m = load()
    files = wanted(m)
    drift: list[str] = []
    for path, text in files.items():
        cur = path.read_text(encoding="utf-8") if path.exists() else None
        if cur == text:
            continue
        rel = path.relative_to(ROOT).as_posix()
        drift.append(f"{'MISSING' if cur is None else 'STALE  '}  {rel}")
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            with io.open(path, "wb") as f:
                f.write(text.encode("utf-8"))

    if args.write:
        print(f"gen_shader_variants: {len(files)} file(s) generated, "
              f"{len(drift)} rewritten")
        return 0

    if drift:
        print("gen_shader_variants: FAIL - generated output does not match "
              "contracts/shader-keywords.json:")
        for d in drift:
            print("  " + d)
        print("  Fix: python tools/shadergen/gen_shader_variants.py --write")
        return 1
    print(f"gen_shader_variants: OK - {len(files)} generated file(s) match "
          "the manifest")
    return 0


if __name__ == "__main__":
    sys.exit(main())
