# jce_script/_generated.pyi — GENERATED. DO NOT EDIT.
#
#   python tools/scriptgen/gen_script_bindings.py --write
#
# PEP 561 stubs for _generated.py, emitted from the same manifest as the
# module itself.  This file is most of the value of the binding: an editor that
# completes `api.` with 71 entries, their argument names and their return
# shapes is what makes a generated surface usable, and the contract was already
# machine-readable — writing the stubs by hand would be a second copy of it.
#
# A stub SHADOWS its module for type checkers, so everything public in
# _generated.py is declared here, with the SAME signature.  Byte-identity
# against a fresh emit cannot see the two emitters drift apart — both files
# would still be fresh — so they are compared to EACH OTHER by
# tests/scripting/python/test_emit_python.py's
# test_stub_declares_every_public_name.

from __future__ import annotations

import ctypes
from typing import Sequence

SCRIPT_API_VERSION: int
ENTRY_COUNT: int
ENTRY_NAMES: tuple[str, ...]
NOT_EXPOSED: dict[str, str]
OWNED_STRING_INITIAL_CAPACITY: int
OWNED_STRING_MAX_ATTEMPTS: int

class MissingExportError(AttributeError): ...

class _RaycastHit(ctypes.Structure):
    entity: int
    point_0: float
    point_1: float
    point_2: float
    normal_0: float
    normal_1: float
    normal_2: float
    distance: float

class _Entries:
    def __init__(self, lib: ctypes.CDLL) -> None: ...

class Api:
    def __init__(self, handle: int, entries: _Entries,
                 lib: ctypes.CDLL) -> None: ...
    @property
    def handle(self) -> int: ...
    def get_position(self, e: int) -> tuple[float, float, float] | None: ...
    def set_position(self, e: int, x: float, y: float, z: float) -> None: ...
    def get_rotation(self, e: int) -> tuple[float, float, float] | None: ...
    def set_rotation(self, e: int, x: float, y: float, z: float) -> None: ...
    def get_scale(self, e: int) -> tuple[float, float, float] | None: ...
    def get_world_position(self,
                           e: int) -> tuple[float, float, float] | None: ...
    def set_scale(self, e: int, x: float, y: float, z: float) -> None: ...
    def set_parent(self,
                   child: int,
                   parent: int,
                   preserve_world: bool) -> bool: ...
    def get_parent(self, child: int) -> int: ...
    def is_key_down(self, keycode: int) -> bool: ...
    def find_with_tag(self, tag: str) -> int: ...
    def destroy(self, e: int) -> None: ...
    def spawn(self,
              prefab_path: str,
              x: float | None = 0.0,
              y: float | None = 0.0,
              z: float | None = 0.0) -> int: ...
    def move_axis(self) -> tuple[float, float]: ...
    def jump_pressed(self) -> bool: ...
    def sprint(self) -> bool: ...
    def attack_pressed(self) -> bool: ...
    def set_time_scale(self, scale: float) -> None: ...
    def pause(self, paused: bool | None = True) -> None: ...
    def shake_camera(self, amount: float | None = 0.5) -> None: ...
    def music_set_intensity(self, intensity: float) -> None: ...
    def music_get_intensity(self) -> float: ...
    def music_request_transition(self, to_segment: int) -> float: ...
    def gas_activate(self, e: int, ability_id: int) -> bool: ...
    def gas_get(self, e: int, attr_name: str) -> tuple[float] | None: ...
    def gas_apply(self,
                  e: int,
                  attr_name: str,
                  op: int | None,
                  magnitude: float,
                  duration_seconds: float | None = 0.0) -> bool: ...
    def raycast(self,
                origin: Sequence[float],
                dir: Sequence[float],
                max_dist: float) -> tuple[int, float, float, float, float, float, float, float] | int: ...
    def raycast_filtered(self,
                         origin: Sequence[float],
                         dir: Sequence[float],
                         max_dist: float,
                         layer_mask: int | None = 0,
                         hit_triggers: bool | None = False) -> tuple[int, float, float, float, float, float, float, float] | int: ...
    def raycast_all(self,
                    origin: Sequence[float],
                    dir: Sequence[float],
                    max_dist: float,
                    layer_mask: int | None = 0,
                    hit_triggers: bool | None = False) -> list[int]: ...
    def apply_impulse(self, e: int, x: float, y: float, z: float) -> None: ...
    def set_velocity(self, e: int, x: float, y: float, z: float) -> None: ...
    def anim_set_float(self, e: int, name: str, v: float) -> None: ...
    def anim_set_int(self, e: int, name: str, v: int) -> None: ...
    def anim_set_bool(self, e: int, name: str, v: bool) -> None: ...
    def anim_set_trigger(self, e: int, name: str) -> None: ...
    def is_action_down(self, name: str) -> bool: ...
    def is_action_pressed(self, name: str) -> bool: ...
    def get_axis(self, name: str) -> float: ...
    def get_pointer_delta(self) -> tuple[float, float]: ...
    def get_pointer_wheel(self) -> float: ...
    def is_pointer_down(self, button: int) -> bool: ...
    def get_touch_count(self) -> int: ...
    def get_touch(self,
                  index: int) -> tuple[int, float, float, float] | None: ...
    def tr(self, key: str) -> str: ...
    def get_locale(self) -> str: ...
    def set_locale(self, locale: str) -> None: ...
    def get_velocity(self, e: int) -> tuple[float, float, float] | None: ...
    def vehicle_set_input(self,
                          e: int,
                          throttle: float,
                          brake: float,
                          steer: float) -> None: ...
    def vehicle_get_speed(self, e: int) -> float: ...
    def get_move(self) -> tuple[float, float, float]: ...
    def ui_get_slider(self, e: int) -> tuple[float] | None: ...
    def ui_set_slider(self, e: int, v: float) -> None: ...
    def ui_get_progress(self, e: int) -> tuple[float] | None: ...
    def ui_set_progress(self, e: int, v: float) -> None: ...
    def ui_get_toggle(self, e: int) -> tuple[bool] | None: ...
    def ui_set_toggle(self, e: int, v: bool) -> None: ...
    def ui_set_text(self, e: int, txt: str) -> None: ...
    def send_message(self,
                     target: int,
                     msg: str,
                     number_arg: float | None = 0.0,
                     str_arg: str | None = None) -> None: ...
    def broadcast(self,
                  msg: str,
                  number_arg: float | None = 0.0,
                  str_arg: str | None = None) -> None: ...
    def has_component(self, e: int, comp_name: str) -> bool: ...
    def is_component_enabled(self, e: int, comp_name: str) -> bool: ...
    def set_component_enabled(self,
                              e: int,
                              comp_name: str,
                              on: bool) -> None: ...
    def net_is_server(self) -> bool: ...
    def net_is_client(self) -> bool: ...
    def net_spawn(self,
                  prefab_path: str,
                  x: float,
                  y: float,
                  z: float) -> int: ...
    def rpc_send(self,
                 e: int,
                 event: str,
                 target: int | None = 0,
                 payload: str | None = None) -> bool: ...
    def particle_burst(self, e: int, count: int) -> None: ...
    def particle_set_emitting(self, e: int, on: bool) -> None: ...
    def particle_set_color(self,
                           e: int,
                           r: float,
                           g: float,
                           b: float) -> None: ...
    def find_by_name(self, name: str) -> tuple[int | None, int]: ...
    def find_by_prefix(self, prefix: str) -> list[int]: ...
    def comp_get(self, e: int, type: str) -> str | None: ...
    def comp_set(self, e: int, type: str, json: str) -> bool: ...
    def render_get(self) -> str | None: ...
    def render_set(self, json: str) -> bool: ...
    def audio_set_volume(self, e: int, volume: float) -> None: ...
    def ui_get_dropdown(self, e: int) -> tuple[int] | None: ...
    def ui_set_dropdown(self, e: int, index: int) -> None: ...
    def ui_get_input_text(self, e: int) -> str: ...
    def ui_set_input_text(self, e: int, text: str) -> None: ...
    def ui_get_scroll(self, e: int) -> tuple[float, float] | None: ...
    def ui_set_scroll(self, e: int, x: float, y: float) -> None: ...
    def world_get_hour(self) -> float: ...
    def world_set_hour(self, hour: float) -> None: ...
    def world_is_daytime(self) -> bool: ...
    def world_get_weather(self) -> int: ...
    def world_get_weather_intensity(self) -> float: ...
    def world_get_wind_speed(self) -> float: ...
    def request_scene(self, scene_path: str) -> bool: ...
    def is_transitioning(self) -> bool: ...
    def audio_play(self, e: int) -> bool: ...
    def audio_stop(self, e: int) -> bool: ...
    def audio_is_playing(self, e: int) -> bool: ...
    def save_game(self, path: str) -> bool: ...
    def load_game(self, path: str) -> bool: ...
    def overlap_sphere(self,
                       x: float,
                       y: float,
                       z: float,
                       radius: float,
                       layer_mask: int | None = 0) -> list[int]: ...
    def overlap_box(self,
                    x: float,
                    y: float,
                    z: float,
                    hx: float,
                    hy: float,
                    hz: float,
                    layer_mask: int | None = 0) -> list[int]: ...
    def get_param(self,
                  e: int,
                  name: str) -> tuple[int, float, int] | None: ...
    def get_param_text(self, e: int, name: str) -> str: ...
    def curve_eval(self,
                   path: str,
                   channel: str,
                   t: float) -> tuple[float] | None: ...
    def vcam_activate(self, name: str) -> int: ...
